import { env } from "cloudflare:workers";
import { assertAiRunAllowed, beginAiRun, completeAiRun, failAiRun, loadAiSettings, providerConfigured } from "@/lib/ai-governance";
import { accountPlanAnalysis, conversationAnalysis, hygieneAnalysis, negotiationAnalysis, normalizeWorkspaceAnalysis, workspaceAnalysisSchema, type WorkspaceAnalysis } from "@/lib/ai-workspace";
import { audit, can, crmUser, sha256, type CRMUser } from "@/lib/crm-auth";

type Row=Record<string,unknown>;
type Feature="conversation-intelligence"|"crm-hygiene"|"account-plan"|"negotiation-intelligence"|"crm-analysis";
const clean=(value:unknown,max=5000)=>String(value??"").trim().slice(0,max);
const rows=async(sql:string,...args:(string|number|null)[])=>(await env.DB.prepare(sql).bind(...args).all()).results as Row[];
const one=async(sql:string,...args:(string|number|null)[])=>env.DB.prepare(sql).bind(...args).first<Row>();
const parse=(value:unknown,fallback:unknown={})=>{try{return JSON.parse(String(value??""))}catch{return fallback}};
const id=(value:unknown,label="record")=>{const number=Number(value);if(!Number.isInteger(number)||number<1)throw new Error(`Choose a valid ${label}.`);return number};
const denied=(user:CRMUser|null,permission:"ai.view"|"ai.generate"|"ai.review")=>!user?Response.json({error:"Sign in is required."},{status:401}):!can(user,permission)?Response.json({error:`${permission} permission is required.`},{status:403}):null;
function outputText(response:Row){if(typeof response.output_text==="string")return response.output_text;return (Array.isArray(response.output)?response.output:[]).flatMap(item=>{const row=item as Row;return Array.isArray(row.content)?row.content:[]}).map(item=>{const row=item as Row;return row.type==="output_text"?clean(row.text,40000):""}).join("")}
function present(row:Row){return {id:clean(row.id,120),feature:clean(row.feature,120),entityType:clean(row.entity_type,80),entityId:clean(row.entity_id,120),reviewStatus:clean(row.review_status,40),content:normalizeWorkspaceAnalysis(parse(row.content_json)),confidence:Number(row.confidence||0),provider:clean(row.provider,120),model:clean(row.model,120),promptVersion:Number(row.prompt_version||1),generatedAt:clean(row.generated_at,80),generatedBy:clean(row.generated_by,240),sourceCount:Number(row.source_count||0),reviewedBy:row.reviewed_by?clean(row.reviewed_by,240):null,reviewedAt:row.reviewed_at?clean(row.reviewed_at,80):null};}
async function conversationData(dealId:number){const deal=await one("SELECT * FROM deals WHERE id=?",dealId);if(!deal)throw new Error("Deal not found.");const [messages,activities,meetings]=await Promise.all([rows("SELECT * FROM inbox_messages WHERE deal_id=? ORDER BY occurred_at DESC LIMIT 80",dealId),rows("SELECT * FROM deal_activities WHERE deal_id=? ORDER BY happened_at DESC LIMIT 80",dealId),rows("SELECT * FROM deal_meetings WHERE deal_id=? ORDER BY starts_at DESC LIMIT 30",dealId)]);return {deal,messages,activities,meetings};}
async function hygieneData(){const [contacts,companies,deals,duplicates]=await Promise.all([rows("SELECT id,first_name,last_name,email,company,title,updated_at FROM contacts ORDER BY updated_at DESC LIMIT 1000"),rows("SELECT id,name,domain,website,owner,industry,updated_at FROM companies ORDER BY updated_at DESC LIMIT 1000"),rows("SELECT id,name,company,status,owner,next_step,close_date,updated_at FROM deals ORDER BY updated_at DESC LIMIT 1000"),rows("SELECT a.id AS aId,a.name AS aName,b.id AS bId,b.name AS bName FROM companies a JOIN companies b ON a.id<b.id AND ((a.domain<>'' AND lower(a.domain)=lower(b.domain)) OR lower(a.name)=lower(b.name)) LIMIT 160")]);return {contacts,companies,deals,duplicates};}
async function accountData(companyId:number){const company=await one("SELECT * FROM companies WHERE id=?",companyId);if(!company)throw new Error("Company not found.");const [contacts,deals,signals,documents,plan]=await Promise.all([rows("SELECT * FROM contacts WHERE lower(company)=lower(?) ORDER BY updated_at DESC LIMIT 100",String(company.name)),rows("SELECT * FROM deals WHERE company_id=? OR lower(company)=lower(?) ORDER BY updated_at DESC LIMIT 100",companyId,String(company.name)),rows("SELECT * FROM account_signals WHERE company_id=? ORDER BY occurred_at DESC LIMIT 50",companyId),rows("SELECT d.*,v.filename FROM client_documents d LEFT JOIN document_versions v ON v.document_id=d.id AND v.version=d.latest_version WHERE d.company_id=? AND d.status='Active' ORDER BY d.updated_at DESC LIMIT 80",companyId),one("SELECT * FROM customer_success_plans WHERE company_id=?",companyId)]);return {company,contacts,deals,signals,documents,plan};}
async function negotiationData(dealId:number){const deal=await one("SELECT * FROM deals WHERE id=?",dealId);if(!deal)throw new Error("Deal not found.");const [proposals,lineItems,insights,documents]=await Promise.all([rows("SELECT * FROM deal_proposals WHERE deal_id=? ORDER BY updated_at DESC LIMIT 20",dealId),rows("SELECT * FROM deal_line_items WHERE deal_id=? ORDER BY updated_at DESC",dealId),rows("SELECT * FROM deal_insights WHERE deal_id=? ORDER BY updated_at DESC LIMIT 30",dealId),rows("SELECT d.*,v.filename FROM client_documents d LEFT JOIN document_versions v ON v.document_id=d.id AND v.version=d.latest_version WHERE d.deal_id=? AND d.status='Active' ORDER BY d.updated_at DESC LIMIT 80",dealId)]);return {deal,proposals,lineItems,insights,documents};}
async function liveQuery(question:string){
 const q=clean(question,800),lower=q.toLowerCase();let kind="Search",records:Row[]=[];
 if(/invoice/.test(lower)){kind="Invoices";records=await rows("SELECT i.id,i.document_number AS name,i.status,i.balance,i.due_date AS dueDate,d.name AS dealName,c.name AS companyName FROM quickbooks_invoices i JOIN deals d ON d.id=i.deal_id LEFT JOIN companies c ON c.id=i.company_id WHERE (? NOT LIKE '%open%' AND ? NOT LIKE '%overdue%') OR i.status IN ('Open','Overdue') ORDER BY i.due_date ASC LIMIT 80",lower,lower);}
 else if(/proposal/.test(lower)&&/(view|open|sign|accept)/.test(lower)){kind="Proposals";records=await rows("SELECT p.id,p.title AS name,p.status,p.opened_at AS openedAt,p.accepted_at AS acceptedAt,p.amount,d.name AS dealName,d.company FROM deal_proposals p JOIN deals d ON d.id=p.deal_id WHERE p.opened_at IS NOT NULL AND p.accepted_at IS NULL ORDER BY p.opened_at DESC LIMIT 80");}
 else if(/executive|decision.?maker|economic buyer/.test(lower)){kind="Stakeholder coverage";records=await rows("SELECT d.id,d.name,d.company,d.stage,d.owner,d.close_date AS closeDate FROM deals d WHERE d.status='Open' AND NOT EXISTS (SELECT 1 FROM deal_stakeholders s WHERE s.deal_id=d.id AND s.active=1 AND lower(s.role) IN ('decision-maker','economic buyer')) ORDER BY d.updated_at DESC LIMIT 80");}
 else if(/next step|follow.?up/.test(lower)){kind="Deals missing next steps";records=await rows("SELECT id,name,company,stage,owner,close_date AS closeDate FROM deals WHERE status='Open' AND trim(next_step)='' ORDER BY updated_at DESC LIMIT 80");}
 else if(/owner|unassigned/.test(lower)){kind="Unowned records";records=await rows("SELECT id,name,company,stage,owner,'Deal' AS recordType FROM deals WHERE status='Open' AND trim(owner)='' ORDER BY updated_at DESC LIMIT 80");}
 else if(/stale|quiet|inactive/.test(lower)){kind="Stale deals";records=await rows("SELECT id,name,company,stage,owner,round(julianday('now')-julianday(updated_at)) AS daysSinceUpdate FROM deals WHERE status='Open' AND julianday('now')-julianday(updated_at)>21 ORDER BY updated_at ASC LIMIT 80");}
 else {const term=q.replace(/["']/g,"").split(/\s+/).filter(item=>item.length>2).slice(0,4).join(" ");records=term?await rows("SELECT id,name,company,stage,owner,'Deal' AS recordType FROM deals WHERE lower(name) LIKE ? OR lower(company) LIKE ? UNION ALL SELECT id,first_name||' '||last_name AS name,company,stage,'' AS owner,'Contact' AS recordType FROM contacts WHERE lower(first_name||' '||last_name) LIKE ? OR lower(email) LIKE ? LIMIT 80",`%${term.toLowerCase()}%`,`%${term.toLowerCase()}%`,`%${term.toLowerCase()}%`,`%${term.toLowerCase()}%`):[];}
 return {question:q,kind,records};
}
async function modelAnalysis(feature:Feature,input:string,settings:Row,prompt:Row|null){const key=clean((env as unknown as Record<string,unknown>).OPENAI_API_KEY,1000),instructions={"conversation-intelligence":"Classify only supplied CRM conversations for commitments, objections, competitors, pricing pressure, sentiment changes, and buying signals. Never invent text or relationship meaning.","crm-hygiene":"Prioritize only supplied CRM data-quality findings. Do not invent duplicates, owners, or changes.","account-plan":"Draft an account-plan brief using only supplied CRM records. Clearly identify gaps instead of inventing objectives or stakeholder influence.","negotiation-intelligence":"Prepare a commercial negotiation brief from supplied CRM records. Do not provide legal advice or claim to interpret document text that was not supplied.","crm-analysis":"Summarize the supplied live CRM query result. Do not broaden or infer beyond the returned records."}[feature],response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({model:String(settings.model),input:[{role:"system",content:clean(prompt?.system_prompt,30000)||instructions},{role:"user",content:input}],max_output_tokens:2600,text:{format:{type:"json_schema",name:"clientrecord_workspace_analysis",strict:true,schema:workspaceAnalysisSchema}}})}),payload=await response.json() as Row;if(!response.ok)throw new Error(clean((payload.error as Row|undefined)?.message,1200)||`AI provider returned ${response.status}.`);const text=outputText(payload);if(!text)throw new Error("The AI provider returned no analysis.");return normalizeWorkspaceAnalysis(JSON.parse(text));}
function sourceGroups(data:Row,entityId:string){return Object.entries(data).map(([type,value])=>({type,id:`${entityId}:${type}`,value,excerpt:type==="question"?clean(value,240):`${type} source`}));}
async function generate(feature:Feature,user:CRMUser,payload:Row,force=false){
 const settings=await loadAiSettings();let entityType="workspace",entityId="current",data:Row,output:WorkspaceAnalysis;
 if(feature==="conversation-intelligence"){const dealId=id(payload.dealId,"deal");entityType="deal";entityId=String(dealId);data=await conversationData(dealId);output=conversationAnalysis(data as Awaited<ReturnType<typeof conversationData>>);} else if(feature==="crm-hygiene"){data=await hygieneData();output=hygieneAnalysis(data as Awaited<ReturnType<typeof hygieneData>>);} else if(feature==="account-plan"){const companyId=id(payload.companyId,"company");entityType="company";entityId=String(companyId);data=await accountData(companyId);output=accountPlanAnalysis(data as Awaited<ReturnType<typeof accountData>>);} else if(feature==="negotiation-intelligence"){const dealId=id(payload.dealId,"deal");entityType="deal";entityId=String(dealId);data=await negotiationData(dealId);output=negotiationAnalysis(data as Awaited<ReturnType<typeof negotiationData>>);} else {data=await liveQuery(clean(payload.question,800));entityType="query";entityId=await sha256(String(data.question));output=normalizeWorkspaceAnalysis({headline:`${data.kind}: ${data.records.length} live result${data.records.length===1?"":"s"}`,summary:`ClientRecord interpreted “${data.question}” as ${data.kind.toLowerCase()}. Results are live at the time of the query.`,findings:data.records.slice(0,6).map(record=>({kind:data.kind,title:clean(record.name||record.dealName||record.companyName||record.id,220),detail:Object.entries(record).filter(([key])=>!['id','name'].includes(key)).slice(0,5).map(([key,value])=>`${key}: ${String(value??"—")}`).join(" · "),severity:"Low",evidence:[]})),recommendations:data.records.length?["Open a result to review its underlying CRM record."]:['Try a more specific question, such as “open invoices”, “proposals viewed but not signed”, or “deals missing next steps”.'],confidence:"High",explanation:"This query uses a safe, predefined interpretation against live ClientRecord records; it does not run user-supplied SQL.",dataGaps:[],records:data.records});}
 const prompt=await one("SELECT * FROM ai_prompt_versions WHERE feature=? AND status='Active' ORDER BY version DESC LIMIT 1",feature),sources=sourceGroups(data,entityId),input=JSON.stringify({instruction:"Return a reviewable ClientRecord analysis. Use only this evidence.",feature,data}).slice(0,Number(settings.maxContextChars)),hashInput=JSON.stringify({input,promptVersion:Number(prompt?.version||1),model:settings.enabled?settings.model:`${feature}-rules-v1`}),inputHash=await sha256(hashInput);
 if(!force){const cached=await one("SELECT a.*,(SELECT count(*) FROM ai_artifact_sources s WHERE s.artifact_id=a.id) AS source_count FROM ai_artifacts a WHERE a.feature=? AND a.entity_type=? AND a.entity_id=? AND a.input_hash=? AND a.review_status!='Rejected' ORDER BY a.generated_at DESC LIMIT 1",feature,entityType,entityId,inputHash);if(cached)return {artifact:present(cached),cached:true};}
 let run:null|{id:string;startedAt:number}=null,provider="clientrecord",model=`${feature}-rules-v1`;if(Boolean(settings.enabled)&&providerConfigured()){const allowed=await assertAiRunAllowed(user);provider=String(allowed.provider);model=String(allowed.model);run=await beginAiRun({feature,entityType,entityId,requestedBy:user.email,provider,model,promptVersion:Number(prompt?.version||1),sourceCount:sources.length,input:hashInput});try{output=await modelAnalysis(feature,input,allowed,prompt);if(feature==="crm-analysis")output.records=(data.records as Row[]).slice(0,80);await completeAiRun(run,JSON.stringify(output));}catch(error){await failAiRun(run,error);throw error;}}
 const artifactId=crypto.randomUUID(),generatedAt=new Date().toISOString(),score=output.confidence==="High"?90:output.confidence==="Medium"?70:40,hashed=await Promise.all(sources.map(async source=>({...source,hash:await sha256(JSON.stringify(source.value))})));await env.DB.batch([env.DB.prepare("UPDATE ai_artifacts SET superseded_by=? WHERE feature=? AND entity_type=? AND entity_id=? AND superseded_by IS NULL").bind(artifactId,feature,entityType,entityId),env.DB.prepare("INSERT INTO ai_artifacts(id,run_id,feature,entity_type,entity_id,review_status,content_json,original_content_json,explanation,confidence,provider,model,prompt_version,rules_version,input_hash,generated_by,generated_at) VALUES (?,?,?,?,?,'Draft',?,?,?,?,?,?,?,?,?,?,?)").bind(artifactId,run?.id||null,feature,entityType,entityId,JSON.stringify(output),JSON.stringify(output),output.explanation,score,provider,model,Number(prompt?.version||1),`${feature}-v1`,inputHash,user.email,generatedAt),...hashed.map(source=>env.DB.prepare("INSERT INTO ai_artifact_sources(artifact_id,source_type,source_id,source_updated_at,content_hash,excerpt) VALUES (?,?,?,?,?,?)").bind(artifactId,source.type,source.id,null,source.hash,source.excerpt))]);return {artifact:present({id:artifactId,feature,entity_type:entityType,entity_id:entityId,review_status:"Draft",content_json:JSON.stringify(output),confidence:score,provider,model,prompt_version:Number(prompt?.version||1),generated_at:generatedAt,generated_by:user.email,source_count:sources.length}),cached:false};
}
export async function GET(request:Request){const user=await crmUser(request),error=denied(user,"ai.view");if(error||!user)return error;try{const [deals,companies,artifacts,learning]=await Promise.all([rows("SELECT id,name,company,stage,value,owner FROM deals WHERE status='Open' ORDER BY updated_at DESC LIMIT 400"),rows("SELECT id,name,industry,owner FROM companies ORDER BY name LIMIT 600"),rows("SELECT a.*,(SELECT count(*) FROM ai_artifact_sources s WHERE s.artifact_id=a.id) AS source_count FROM ai_artifacts a WHERE a.feature IN ('conversation-intelligence','crm-hygiene','account-plan','negotiation-intelligence','crm-analysis') ORDER BY a.generated_at DESC LIMIT 100"),rows("SELECT rule_key AS ruleKey,status,count(*) AS count FROM deal_recommendations GROUP BY rule_key,status ORDER BY count DESC LIMIT 100")]),settings=await loadAiSettings();return Response.json({deals,companies,artifacts:artifacts.map(present),learning,settings:{enabled:Boolean(settings.enabled)},providerConfigured:providerConfigured(),permissions:{generate:can(user,"ai.generate"),review:can(user,"ai.review")}})}catch(error){return Response.json({error:error instanceof Error?error.message:"AI workspace is unavailable."},{status:400})}}
export async function POST(request:Request){const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});try{const body=await request.json() as Row,action=clean(body.action,80),features:Record<string,Feature>={generateConversation:"conversation-intelligence",generateHygiene:"crm-hygiene",generateAccountPlan:"account-plan",generateNegotiation:"negotiation-intelligence",analyzeCRM:"crm-analysis"};if(features[action]){const error=denied(user,"ai.generate");if(error)return error;const result=await generate(features[action],user,body,body.force===true);await audit(user,`ai.${features[action]}.generate`,`ai_artifact`,result.artifact.id,result.cached?"Used current AI workspace analysis":"Generated AI workspace analysis",{feature:features[action],entityId:result.artifact.entityId,cached:result.cached,sourceCount:result.artifact.sourceCount});return Response.json({ok:true,...result});}if(action==="review"){const error=denied(user,"ai.review");if(error)return error;const artifactId=clean(body.artifactId,120),status=clean(body.status,20),record=await one("SELECT * FROM ai_artifacts WHERE id=? AND feature IN ('conversation-intelligence','crm-hygiene','account-plan','negotiation-intelligence','crm-analysis')",artifactId);if(!record)throw new Error("AI result was not found.");if(!["Accepted","Rejected"].includes(status))throw new Error("Choose accepted or rejected.");await env.DB.batch([env.DB.prepare("INSERT INTO ai_feedback_events(artifact_id,action,before_json,after_json,comment,actor,created_at) VALUES (?,?,?,?,?,?,datetime('now'))").bind(artifactId,status,JSON.stringify({reviewStatus:record.review_status}),JSON.stringify({reviewStatus:status}),clean(body.comment,1000),user.email),env.DB.prepare("UPDATE ai_artifacts SET review_status=?,reviewed_by=?,reviewed_at=datetime('now') WHERE id=?").bind(status,user.email,artifactId)]);await audit(user,"ai.workspace.review","ai_artifact",artifactId,`${status} AI workspace result`,{status});return Response.json({ok:true});}throw new Error("Unknown AI workspace action.");}catch(error){return Response.json({error:error instanceof Error?error.message:"The AI workspace action could not be completed."},{status:400})}}
