import { env } from "cloudflare:workers";
import { API_KEY_SCOPES, apiKeyUser, audit, can, crmUser, defaultPermissions, displayName, sha256, type CRMPermission, type CRMRole } from "@/lib/crm-auth";
import { createBackup, databaseHealth, maybeRunDailyMaintenance, restoreBackup, runDailyMaintenance, runDueAutomations, runStagnationAlerts } from "@/lib/operations";
import { encryptToken } from "@/lib/microsoft";
import { emitWebhook } from "@/lib/webhooks";

type Row=Record<string,unknown>;
const clean=(value:unknown)=>typeof value==="string"?value.trim():"";
const asRows=(result:D1Result<unknown>)=>result.results as Row[];
function token(prefix:string){const bytes=crypto.getRandomValues(new Uint8Array(30));let raw="";for(const byte of bytes)raw+=String.fromCharCode(byte);return `${prefix}${btoa(raw).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}`;}

async function analytics(){
  const [lifecycle,stageRows,aging,won,activity,attribution,forecast]=await Promise.all([
    env.DB.prepare("SELECT stage,count(*) AS count FROM contacts GROUP BY stage ORDER BY count DESC").all(),
    env.DB.prepare("SELECT from_stage AS fromStage,to_stage AS toStage,count(*) AS moves FROM deal_stage_history GROUP BY from_stage,to_stage ORDER BY moves DESC").all(),
    env.DB.prepare("SELECT stage,count(*) AS count,round(avg(julianday('now')-julianday(COALESCE(NULLIF(stage_entered_at,''),updated_at,created_at))),1) AS avgDays,max(round(julianday('now')-julianday(COALESCE(NULLIF(stage_entered_at,''),updated_at,created_at))),0) AS maxDays FROM deals WHERE status='Open' GROUP BY stage ORDER BY avgDays DESC").all(),
    env.DB.prepare("SELECT count(*) AS wonCount,COALESCE(avg(value),0) AS avgValue,COALESCE(avg(julianday(updated_at)-julianday(created_at)),0) AS avgDays FROM deals WHERE status='Won'").first<Row>(),
    env.DB.prepare("SELECT type,count(*) AS count FROM activities WHERE happened_at>=datetime('now','-30 days') GROUP BY type ORDER BY count DESC").all(),
    env.DB.prepare("SELECT COALESCE(NULLIF(lead_source,''),'Direct') AS source,COALESCE(NULLIF(campaign,''),'Unattributed') AS campaign,COALESCE(NULLIF(partner,''),'Direct') AS partner,count(*) AS deals,sum(CASE WHEN status='Won' THEN 1 ELSE 0 END) AS won,sum(CASE WHEN status='Won' THEN value ELSE 0 END) AS revenue FROM deals GROUP BY source,campaign,partner ORDER BY revenue DESC").all(),
    env.DB.prepare("SELECT COALESCE(sum(value*probability/100.0),0) AS forecast,COALESCE(sum(CASE WHEN status='Won' THEN value ELSE 0 END),0) AS actual FROM deals WHERE COALESCE(close_date,updated_at)>=date('now','-90 days')").first<Row>(),
  ]);
  const deals=Number(won?.wonCount||0),avgValue=Number(won?.avgValue||0),avgDays=Math.max(1,Number(won?.avgDays||0));
  const totalClosed=await env.DB.prepare("SELECT count(*) AS count FROM deals WHERE status IN ('Won','Lost')").first<{count:number}>(),winRate=Number(totalClosed?.count||0)?deals/Number(totalClosed?.count):0;
  const forecastValue=Number(forecast?.forecast||0),actual=Number(forecast?.actual||0);
  return {lifecycle:asRows(lifecycle),stageConversions:asRows(stageRows),aging:asRows(aging),salesVelocity:{wonDeals:deals,avgDealValue:avgValue,avgSalesCycleDays:avgDays,winRate:winRate*100,velocity:deals*avgValue*winRate/avgDays},activity:asRows(activity),attribution:asRows(attribution),forecast:{forecast:forecastValue,actual,accuracy:forecastValue?Math.max(0,100-Math.abs(actual-forecastValue)/forecastValue*100):null}};
}

async function today(email:string,name:string){
  const [tasks,dealTasks,notifications,hot,stalled,upcoming]=await Promise.all([
    env.DB.prepare("SELECT t.id,t.title,t.due_date AS dueDate,t.owner,t.contact_id AS contactId,c.first_name||' '||c.last_name AS contactName,c.company FROM tasks t JOIN contacts c ON c.id=t.contact_id WHERE t.completed=0 AND (lower(t.owner) IN (lower(?),lower(?)) OR t.owner='') ORDER BY CASE WHEN t.due_date<date('now') THEN 0 WHEN t.due_date=date('now') THEN 1 ELSE 2 END,t.due_date LIMIT 50").bind(name,email).all(),
    env.DB.prepare("SELECT t.id,t.title,t.due_date AS dueDate,t.owner,t.deal_id AS dealId,d.name AS dealName,d.company FROM deal_tasks t JOIN deals d ON d.id=t.deal_id WHERE t.completed=0 AND (lower(t.owner) IN (lower(?),lower(?)) OR t.owner='') ORDER BY t.due_date LIMIT 50").bind(name,email).all(),
    env.DB.prepare("SELECT id,kind,title,body,entity_type AS entityType,entity_id AS entityId,action_url AS actionUrl,created_at AS createdAt FROM notifications WHERE lower(owner_email)=lower(?) AND read_at IS NULL ORDER BY created_at DESC LIMIT 50").bind(email).all(),
    env.DB.prepare("SELECT id,name,owner,fit_score AS fitScore,intent_score AS intentScore,temperature FROM companies WHERE temperature='Hot' ORDER BY intent_score DESC,fit_score DESC LIMIT 20").all(),
    env.DB.prepare("SELECT d.id,d.name,d.company,d.stage,d.owner,round(julianday('now')-julianday(COALESCE(NULLIF(d.stage_entered_at,''),d.updated_at,d.created_at))) AS days FROM deals d WHERE d.status='Open' AND julianday('now')-julianday(COALESCE(NULLIF(d.stage_entered_at,''),d.updated_at,d.created_at))>=COALESCE((SELECT stagnation_days FROM operation_settings WHERE id=1),14) ORDER BY days DESC LIMIT 20").all(),
    env.DB.prepare("SELECT a.id,a.contact_id AS contactId,a.note,a.happened_at AS happenedAt,c.first_name||' '||c.last_name AS contactName,c.company FROM activities a JOIN contacts c ON c.id=a.contact_id WHERE lower(a.type) LIKE '%meeting%' AND a.happened_at BETWEEN datetime('now') AND datetime('now','+7 days') ORDER BY a.happened_at LIMIT 20").all(),
  ]);
  return {tasks:asRows(tasks),dealTasks:asRows(dealTasks),notifications:asRows(notifications),hotAccounts:asRows(hot),stalledDeals:asRows(stalled),upcomingMeetings:asRows(upcoming)};
}

async function operations(){
  const [health,backups,jobs,events,delivery,imports,keys,hooks,hookDeliveries,settings,members]=await Promise.all([
    databaseHealth(),env.DB.prepare("SELECT id,status,row_count AS rowCount,checksum,created_by AS createdBy,created_at AS createdAt,restored_at AS restoredAt FROM backup_snapshots ORDER BY created_at DESC LIMIT 30").all(),env.DB.prepare("SELECT id,job_type AS jobType,status,processed,failed,message,started_at AS startedAt,completed_at AS completedAt FROM job_runs ORDER BY started_at DESC LIMIT 50").all(),env.DB.prepare("SELECT id,severity,category,source,message,details,resolved_at AS resolvedAt,created_at AS createdAt FROM system_events ORDER BY created_at DESC LIMIT 100").all(),env.DB.prepare("SELECT id,provider,kind,status,recipient,subject,error,created_at AS createdAt FROM delivery_logs ORDER BY created_at DESC LIMIT 100").all(),env.DB.prepare("SELECT id,entity_type AS entityType,filename,created_count AS createdCount,updated_count AS updatedCount,status,created_by AS createdBy,created_at AS createdAt,rolled_back_at AS rolledBackAt FROM import_batches ORDER BY created_at DESC LIMIT 30").all(),env.DB.prepare("SELECT id,name,key_prefix AS keyPrefix,scopes,last_used_at AS lastUsedAt,expires_at AS expiresAt,revoked_at AS revokedAt,created_by AS createdBy,created_at AS createdAt FROM api_keys ORDER BY created_at DESC").all(),env.DB.prepare("SELECT id,name,url,events,active,last_status AS lastStatus,last_triggered_at AS lastTriggeredAt,created_at AS createdAt FROM webhook_endpoints ORDER BY created_at DESC").all(),env.DB.prepare("SELECT id,endpoint_id AS endpointId,event,status,response_status AS responseStatus,error,created_at AS createdAt FROM webhook_deliveries ORDER BY created_at DESC LIMIT 50").all(),env.DB.prepare("SELECT daily_backup_hour AS dailyBackupHour,stagnation_days AS stagnationDays,post_meeting_task_days AS postMeetingTaskDays,audit_retention_days AS auditRetentionDays,event_retention_days AS eventRetentionDays,delivery_retention_days AS deliveryRetentionDays,sync_retention_days AS syncRetentionDays,updated_at AS updatedAt FROM operation_settings WHERE id=1").first<Row>(),env.DB.prepare("SELECT id,email,name,role,permissions,active FROM team_members ORDER BY active DESC,name,email").all()]);
  return {health,backupStorage:Boolean(env.BUCKET),backups:asRows(backups),jobs:asRows(jobs),events:asRows(events),delivery:asRows(delivery),imports:asRows(imports),apiKeys:asRows(keys),webhooks:asRows(hooks),webhookDeliveries:asRows(hookDeliveries),members:asRows(members).map(member=>({...member,permissions:(()=>{try{const parsed=JSON.parse(String(member.permissions||"[]"));return Array.isArray(parsed)?parsed:defaultPermissions(member.role as CRMRole)}catch{return defaultPermissions(member.role as CRMRole)}})()})),settings:settings||{dailyBackupHour:2,stagnationDays:14,postMeetingTaskDays:1,auditRetentionDays:730,eventRetentionDays:90,deliveryRetentionDays:180,syncRetentionDays:365}};
}

export async function GET(request:Request){
  const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});
  try{await maybeRunDailyMaintenance(user.email);const [todayData,analyticsData,ops]=await Promise.all([today(user.email,await displayName(user)),analytics(),can(user,"settings.manage")?operations():Promise.resolve(null)]);return Response.json({account:user,today:todayData,analytics:analyticsData,operations:ops});}
  catch(error){console.error(error);return Response.json({error:error instanceof Error?error.message:"Operations data is unavailable."},{status:503});}
}

export async function POST(request:Request){
  const siwc=await crmUser(request),api=siwc?null:await apiKeyUser(request,"jobs.run"),user=siwc||api;if(!user)return Response.json({error:"Authentication is required."},{status:401});
  const body=await request.json().catch(()=>({})) as Row,action=clean(body.action);
  try{
    if(action==="runDaily"){if(!can(user,"jobs.run"))return Response.json({error:"Job runner access is required."},{status:403});return Response.json(await runDailyMaintenance(user.email));}
    if(action==="runSequences"){if(!can(user,"jobs.run"))return Response.json({error:"Job runner access is required."},{status:403});return Response.json(await runDueAutomations(user.email));}
    if(action==="runStagnation"){if(!can(user,"jobs.run"))return Response.json({error:"Job runner access is required."},{status:403});return Response.json({created:await runStagnationAlerts()});}
    if(!siwc)return Response.json({error:"This action requires an interactive administrator session."},{status:403});
    if(action==="markNotification"){await env.DB.prepare("UPDATE notifications SET read_at=datetime('now') WHERE id=? AND lower(owner_email)=lower(?)").bind(body.id,user.email).run();return Response.json({status:"read"});}
    if(!can(user,"settings.manage"))return Response.json({error:"Administrator access is required."},{status:403});
    if(action==="createBackup"){const result=await createBackup(user.email,"manual");await audit(user,action,"backup",result.id,"Created manual backup",{rowCount:result.rowCount});return Response.json(result,{status:201});}
    if(action==="restoreBackup"){if(clean(body.confirmation)!=="RESTORE")return Response.json({error:"Type RESTORE to confirm."},{status:400});const result=await restoreBackup(clean(body.id),user.email);await audit(user,action,"backup",body.id,"Restored CRM backup",{id:body.id});return Response.json(result);}
    if(action==="saveOperations"){const num=(key:string,fallback:number,min:number,max:number)=>Math.min(max,Math.max(min,Number(body[key]||fallback)));await env.DB.prepare("INSERT INTO operation_settings(id,daily_backup_hour,stagnation_days,post_meeting_task_days,audit_retention_days,event_retention_days,delivery_retention_days,sync_retention_days,updated_by,updated_at) VALUES (1,?,?,?,?,?,?,?,?,datetime('now')) ON CONFLICT(id) DO UPDATE SET daily_backup_hour=excluded.daily_backup_hour,stagnation_days=excluded.stagnation_days,post_meeting_task_days=excluded.post_meeting_task_days,audit_retention_days=excluded.audit_retention_days,event_retention_days=excluded.event_retention_days,delivery_retention_days=excluded.delivery_retention_days,sync_retention_days=excluded.sync_retention_days,updated_by=excluded.updated_by,updated_at=datetime('now')").bind(num("dailyBackupHour",2,0,23),num("stagnationDays",14,1,365),num("postMeetingTaskDays",1,0,30),num("auditRetentionDays",730,30,3650),num("eventRetentionDays",90,7,730),num("deliveryRetentionDays",180,7,730),num("syncRetentionDays",365,30,3650),user.email).run();await audit(user,action,"operation_settings",1,"Updated production and retention settings",body);return Response.json({status:"saved"});}
    if(action==="createApiKey"){const raw=token("cr_live_"),id=crypto.randomUUID(),name=clean(body.name)||"API key",scopes=(clean(body.scopes)||"jobs.run").split(",").map(scope=>scope.trim()).filter(Boolean).join(",");const unknown=scopes.split(",").filter(scope=>!API_KEY_SCOPES.includes(scope));if(unknown.length)return Response.json({error:`Unknown API key scope: ${unknown.join(", ")}. Allowed: ${API_KEY_SCOPES.join(", ")}.`},{status:400});if(scopes.split(",").includes("*")&&user.role!=="owner")return Response.json({error:"Only an owner can create an all-scope (*) API key."},{status:403});await env.DB.prepare("INSERT INTO api_keys(id,name,key_hash,key_prefix,scopes,expires_at,created_by,created_at) VALUES (?,?,?,?,?,?,?,datetime('now'))").bind(id,name,await sha256(raw),raw.slice(0,16),scopes,clean(body.expiresAt)||null,user.email).run();await audit(user,action,"api_key",id,`Created API key ${name}`,{name,scopes});return Response.json({id,key:raw,name,scopes},{status:201});}
    if(action==="revokeApiKey"){await env.DB.prepare("UPDATE api_keys SET revoked_at=datetime('now') WHERE id=?").bind(body.id).run();await audit(user,action,"api_key",body.id,"Revoked API key");return Response.json({status:"revoked"});}
    if(action==="saveWebhook"){const url=clean(body.url);if(!url.startsWith("https://"))return Response.json({error:"Webhook URL must use HTTPS."},{status:400});const id=crypto.randomUUID(),secret=token("whsec_"),events=clean(body.events)||"*";await env.DB.prepare("INSERT INTO webhook_endpoints(id,name,url,events,secret_encrypted,active,created_at) VALUES (?,?,?,?,?,1,datetime('now'))").bind(id,clean(body.name)||"Webhook",url,events,await encryptToken(secret)).run();await audit(user,action,"webhook",id,"Created outbound webhook",{url,events});return Response.json({id,secret},{status:201});}
    if(action==="disableWebhook"){await env.DB.prepare("UPDATE webhook_endpoints SET active=0 WHERE id=?").bind(body.id).run();await audit(user,action,"webhook",body.id,"Disabled outbound webhook");return Response.json({status:"disabled"});}
    if(action==="testWebhooks"){await emitWebhook("webhook.test",{message:"ClientRecord CRM webhook test"});return Response.json({status:"sent"});}
    if(action==="savePermissions"){if(user.role!=="owner")return Response.json({error:"Owner access is required."},{status:403});const role=(["admin","editor","viewer"].includes(clean(body.role))?clean(body.role):"viewer") as CRMRole,permissions=Array.isArray(body.permissions)?body.permissions as CRMPermission[]:defaultPermissions(role);await env.DB.prepare("UPDATE team_members SET role=?,permissions=?,updated_at=datetime('now') WHERE id=?").bind(role,JSON.stringify(permissions),body.id).run();await audit(user,action,"team_member",body.id,"Updated detailed permissions",{role,permissions});return Response.json({status:"saved"});}
    if(action==="rollbackImport"){const batch=await env.DB.prepare("SELECT * FROM import_batches WHERE id=? AND rolled_back_at IS NULL").bind(body.id).first<Row>();if(!batch)return Response.json({error:"Import is unavailable or already rolled back."},{status:409});const changes=(await env.DB.prepare("SELECT * FROM import_changes WHERE batch_id=? ORDER BY id DESC").bind(body.id).all<Row>()).results;for(const change of changes){if(change.change_type==="create")await env.DB.prepare(String(change.entity_id).includes("@")?"DELETE FROM contacts WHERE lower(email)=lower(?)":"DELETE FROM contacts WHERE id=?").bind(change.entity_id).run();else if(change.before_json){const before=JSON.parse(String(change.before_json)) as Row;await env.DB.prepare("UPDATE contacts SET first_name=?,last_name=?,email=?,company=?,title=?,phone=?,location=?,notes=?,lead_source=?,stage=?,tags=?,last_contact=?,next_follow_up=?,subscribed=?,suppression_reason=?,suppressed_at=?,updated_at=? WHERE id=?").bind(before.first_name,before.last_name,before.email,before.company,before.title,before.phone,before.location,before.notes,before.lead_source,before.stage,before.tags,before.last_contact,before.next_follow_up,before.subscribed,before.suppression_reason,before.suppressed_at,before.updated_at,before.id).run();}}await env.DB.prepare("UPDATE import_batches SET status='Rolled back',rolled_back_at=datetime('now') WHERE id=?").bind(body.id).run();await audit(user,action,"import_batch",body.id,"Rolled back contact import");return Response.json({status:"rolled back",changes:changes.length});}
    return Response.json({error:"Unknown action."},{status:400});
  }catch(error){console.error(error);return Response.json({error:error instanceof Error?error.message:"The operation failed."},{status:500});}
}
