import { env } from "cloudflare:workers";
import { audit, can, canAdmin, crmUser, sha256 } from "@/lib/crm-auth";

type Row = Record<string, unknown>;
const clean = (value: unknown, max = 12000) => String(value ?? "").trim().slice(0, max);
const number = (value: unknown, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const optionalId = (value: unknown) => number(value) > 0 ? number(value) : null;
const rows = async (sql: string, ...args: (string | number | null)[]) => (await env.DB.prepare(sql).bind(...args).all()).results as Row[];
const csv = (value: unknown) => clean(value, 2000).split(",").map(item => item.trim()).filter(Boolean);
const slug = (value: unknown) => clean(value, 160).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || crypto.randomUUID();
const cents = (value: unknown) => Math.round(number(value) * 100);
const hoursFromNow = (hours: number) => new Date(Date.now() + hours * 3600000).toISOString();

async function platformData(userEmail: string) {
  await env.DB.prepare("UPDATE service_cases SET status='Escalated',escalated_at=COALESCE(escalated_at,datetime('now')),escalation_reason=CASE WHEN escalation_reason='' THEN 'SLA breached' ELSE escalation_reason END,updated_at=datetime('now') WHERE status NOT IN ('Resolved','Closed','Escalated') AND resolution_due_at IS NOT NULL AND datetime(resolution_due_at)<datetime('now')").run();
  const [partners, partnerContacts, referrals, payouts, competitors, competitorDeals, cases, notes, articles, portalAccess, captures, companies, contacts, deals] = await Promise.all([
    rows("SELECT p.*,c.name AS crm_company_name,(SELECT count(*) FROM partner_contacts pc WHERE pc.partner_company_id=p.id) AS contact_count,(SELECT count(*) FROM partner_referrals pr WHERE pr.partner_company_id=p.id) AS referral_count FROM partner_companies p LEFT JOIN companies c ON c.id=p.company_id ORDER BY p.name"),
    rows("SELECT pc.*,p.name AS partner_name FROM partner_contacts pc JOIN partner_companies p ON p.id=pc.partner_company_id ORDER BY p.name,pc.first_name,pc.last_name"),
    rows("SELECT r.*,p.name AS partner_name,d.name AS deal_name,d.stage AS deal_stage,d.status AS deal_status FROM partner_referrals r JOIN partner_companies p ON p.id=r.partner_company_id LEFT JOIN deals d ON d.id=r.deal_id ORDER BY r.submitted_at DESC"),
    rows("SELECT py.*,p.name AS partner_name,d.name AS deal_name FROM partner_payouts py JOIN partner_companies p ON p.id=py.partner_company_id LEFT JOIN deals d ON d.id=py.deal_id ORDER BY COALESCE(py.due_date,py.created_at) DESC"),
    rows("SELECT c.*,(SELECT count(*) FROM deal_competitors dc WHERE dc.competitor_id=c.id) AS deal_count,(SELECT count(*) FROM deal_competitors dc WHERE dc.competitor_id=c.id AND dc.outcome='Won') AS wins,(SELECT count(*) FROM deal_competitors dc WHERE dc.competitor_id=c.id AND dc.outcome='Lost') AS losses FROM competitors c WHERE c.active=1 ORDER BY c.name"),
    rows("SELECT dc.*,c.name AS competitor_name,d.name AS deal_name,d.company,d.value,d.status AS current_deal_status FROM deal_competitors dc JOIN competitors c ON c.id=dc.competitor_id JOIN deals d ON d.id=dc.deal_id ORDER BY dc.mentioned_at DESC"),
    rows("SELECT sc.*,c.first_name||' '||c.last_name AS contact_name,co.name AS company_name,d.name AS deal_name,(SELECT count(*) FROM service_cases child WHERE child.parent_case_id=sc.id) AS child_count FROM service_cases sc LEFT JOIN contacts c ON c.id=sc.contact_id LEFT JOIN companies co ON co.id=sc.company_id LEFT JOIN deals d ON d.id=sc.deal_id ORDER BY CASE sc.priority WHEN 'Urgent' THEN 0 WHEN 'High' THEN 1 WHEN 'Normal' THEN 2 ELSE 3 END,sc.created_at DESC"),
    rows("SELECT * FROM case_notes ORDER BY created_at DESC LIMIT 500"),
    rows("SELECT * FROM knowledge_articles ORDER BY CASE status WHEN 'Published' THEN 0 ELSE 1 END,updated_at DESC"),
    rows("SELECT pa.id,pa.company_id,pa.contact_id,pa.status,pa.permissions_json,pa.expires_at,pa.last_used_at,pa.created_at,co.name AS company_name,c.first_name||' '||c.last_name AS contact_name,c.email FROM customer_portal_access pa JOIN companies co ON co.id=pa.company_id JOIN contacts c ON c.id=pa.contact_id ORDER BY pa.created_at DESC"),
    rows("SELECT fc.*,c.first_name||' '||c.last_name AS contact_name,co.name AS company_name FROM field_captures fc LEFT JOIN contacts c ON c.id=fc.contact_id LEFT JOIN companies co ON co.id=fc.company_id WHERE lower(fc.captured_by)=lower(?) ORDER BY fc.captured_at DESC LIMIT 100", userEmail),
    rows("SELECT id,name,owner,stage FROM companies ORDER BY name LIMIT 1000"),
    rows("SELECT id,first_name||' '||last_name AS name,email,company FROM contacts ORDER BY first_name,last_name LIMIT 1500"),
    rows("SELECT id,name,company,value,stage,status,partner FROM deals ORDER BY updated_at DESC LIMIT 1000"),
  ]);
  const openCases = cases.filter(item => !["Resolved", "Closed"].includes(String(item.status)));
  return { account:{email:userEmail}, partners, partnerContacts, referrals, payouts, competitors, competitorDeals, cases, caseNotes:notes, articles, portalAccess, captures, companies, contacts, deals, serviceSummary:{open:openCases.length,breached:openCases.filter(item=>String(item.status)==="Escalated").length,unassigned:openCases.filter(item=>!String(item.owner)).length} };
}

export async function GET(request: Request) {
  const user = await crmUser(request);
  if (!user) return Response.json({ error:"Sign in is required." }, { status:401 });
  if (!can(user, "records.view")) return Response.json({ error:"View access is required." }, { status:403 });
  try { return Response.json(await platformData(user.email)); }
  catch (error) { console.error(error); return Response.json({ error:"Partner, competitive, and service data could not load." }, { status:503 }); }
}

export async function POST(request: Request) {
  const user = await crmUser(request);
  if (!user) return Response.json({ error:"Sign in is required." }, { status:401 });
  if (!can(user, "records.edit")) return Response.json({ error:"Edit access is required." }, { status:403 });
  try {
    const body = await request.json() as Row, action = clean(body.action, 80), now = new Date().toISOString();
    if (action === "savePartner") {
      const id = clean(body.id, 80) || crypto.randomUUID(), name = clean(body.name, 240); if (!name) throw new Error("Partner name is required.");
      await env.DB.prepare("INSERT INTO partner_companies(id,company_id,name,domain,type,tier,status,owner,territory,commission_percent,permissions_json,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET company_id=excluded.company_id,name=excluded.name,domain=excluded.domain,type=excluded.type,tier=excluded.tier,status=excluded.status,owner=excluded.owner,territory=excluded.territory,commission_percent=excluded.commission_percent,permissions_json=excluded.permissions_json,notes=excluded.notes,updated_at=excluded.updated_at").bind(id,optionalId(body.companyId),name,clean(body.domain,240),clean(body.type,80)||"Referral",clean(body.tier,80)||"Registered",clean(body.status,80)||"Active",clean(body.owner,200)||user.email,clean(body.territory,160),Math.max(0,Math.min(100,number(body.commissionPercent,10))),JSON.stringify(csv(body.permissions)),clean(body.notes),now,now).run();
      await audit(user,"partner.save","partner_company",id,`Saved partner ${name}`,body); return Response.json({id},{status:201});
    }
    if (action === "savePartnerContact") {
      const id = clean(body.id, 80)||crypto.randomUUID(), partnerId=clean(body.partnerCompanyId,80), email=clean(body.email,320).toLowerCase(); if(!partnerId||!email)throw new Error("Partner and email are required.");
      await env.DB.prepare("INSERT INTO partner_contacts(id,partner_company_id,contact_id,first_name,last_name,email,title,phone,role,portal_access,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET partner_company_id=excluded.partner_company_id,contact_id=excluded.contact_id,first_name=excluded.first_name,last_name=excluded.last_name,email=excluded.email,title=excluded.title,phone=excluded.phone,role=excluded.role,portal_access=excluded.portal_access,updated_at=excluded.updated_at").bind(id,partnerId,optionalId(body.contactId),clean(body.firstName,120),clean(body.lastName,120),email,clean(body.title,200),clean(body.phone,80),clean(body.role,100)||"Partner rep",body.portalAccess?1:0,now,now).run();
      await audit(user,"partner.contact.save","partner_contact",id,"Saved partner contact",body); return Response.json({id},{status:201});
    }
    if (action === "saveReferral") {
      const id=clean(body.id,80)||crypto.randomUUID(),partnerId=clean(body.partnerCompanyId,80),prospect=clean(body.prospectCompany,240);if(!partnerId||!prospect)throw new Error("Partner and prospect company are required.");
      await env.DB.prepare("INSERT INTO partner_referrals(id,partner_company_id,partner_contact_id,deal_id,prospect_company,prospect_contact,prospect_email,status,protection_status,protection_expires_at,attribution_percent,estimated_value,owner,notes,submitted_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET partner_company_id=excluded.partner_company_id,partner_contact_id=excluded.partner_contact_id,deal_id=excluded.deal_id,prospect_company=excluded.prospect_company,prospect_contact=excluded.prospect_contact,prospect_email=excluded.prospect_email,status=excluded.status,protection_status=excluded.protection_status,protection_expires_at=excluded.protection_expires_at,attribution_percent=excluded.attribution_percent,estimated_value=excluded.estimated_value,owner=excluded.owner,notes=excluded.notes,updated_at=excluded.updated_at").bind(id,partnerId,clean(body.partnerContactId,80)||null,optionalId(body.dealId),prospect,clean(body.prospectContact,240),clean(body.prospectEmail,320).toLowerCase(),clean(body.status,80)||"Submitted",clean(body.protectionStatus,80)||"Pending",clean(body.protectionExpiresAt,40)||null,Math.max(0,Math.min(100,number(body.attributionPercent,100))),cents(body.estimatedValue),clean(body.owner,200)||user.email,clean(body.notes),now,now).run();
      await audit(user,"partner.referral.save","partner_referral",id,`Registered referral for ${prospect}`,body); return Response.json({id},{status:201});
    }
    if (action === "savePayout") {
      const id=clean(body.id,80)||crypto.randomUUID(),partnerId=clean(body.partnerCompanyId,80);if(!partnerId||number(body.amount)<=0)throw new Error("Partner and payout amount are required.");
      await env.DB.prepare("INSERT INTO partner_payouts(id,partner_company_id,referral_id,deal_id,amount,status,due_date,paid_at,reference,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET amount=excluded.amount,status=excluded.status,due_date=excluded.due_date,paid_at=excluded.paid_at,reference=excluded.reference,updated_at=excluded.updated_at").bind(id,partnerId,clean(body.referralId,80)||null,optionalId(body.dealId),cents(body.amount),clean(body.status,80)||"Accrued",clean(body.dueDate,40)||null,clean(body.status)==="Paid"?now:null,clean(body.reference,240),now,now).run();
      await audit(user,"partner.payout.save","partner_payout",id,"Saved partner payout",body); return Response.json({id},{status:201});
    }
    if (action === "saveCompetitor") {
      const id=clean(body.id,80)||crypto.randomUUID(),name=clean(body.name,240);if(!name)throw new Error("Competitor name is required.");
      await env.DB.prepare("INSERT INTO competitors(id,name,website,category,positioning,strengths,weaknesses,differentiation,objection_guidance,battlecard,active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,1,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,website=excluded.website,category=excluded.category,positioning=excluded.positioning,strengths=excluded.strengths,weaknesses=excluded.weaknesses,differentiation=excluded.differentiation,objection_guidance=excluded.objection_guidance,battlecard=excluded.battlecard,updated_at=excluded.updated_at").bind(id,name,clean(body.website,500),clean(body.category,100)||"Direct",clean(body.positioning),clean(body.strengths),clean(body.weaknesses),clean(body.differentiation),clean(body.objectionGuidance),clean(body.battlecard,24000),now,now).run();
      await audit(user,"competitor.save","competitor",id,`Saved competitor ${name}`,body); return Response.json({id},{status:201});
    }
    if (action === "linkCompetitor") {
      const id=clean(body.id,80)||crypto.randomUUID(),dealId=optionalId(body.dealId),competitorId=clean(body.competitorId,80);if(!dealId||!competitorId)throw new Error("Deal and competitor are required.");
      await env.DB.prepare("INSERT INTO deal_competitors(id,deal_id,competitor_id,outcome,reason,mentioned_at,source,created_by) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(deal_id,competitor_id) DO UPDATE SET outcome=excluded.outcome,reason=excluded.reason,mentioned_at=excluded.mentioned_at,source=excluded.source,created_by=excluded.created_by").bind(id,dealId,competitorId,clean(body.outcome,80)||"Open",clean(body.reason,4000),now,clean(body.source,100)||"Manual",user.email).run();
      await audit(user,"competitor.link","deal",dealId,"Linked competitor to deal",body); return Response.json({id},{status:201});
    }
    if (action === "saveCase") {
      const id=clean(body.id,80)||crypto.randomUUID(),subject=clean(body.subject,500);if(!subject)throw new Error("Case subject is required.");const priority=clean(body.priority,40)||"Normal",responseHours=priority==="Urgent"?1:priority==="High"?4:priority==="Low"?24:8,resolutionHours=priority==="Urgent"?8:priority==="High"?24:priority==="Low"?120:72,existing=await env.DB.prepare("SELECT case_number,created_at FROM service_cases WHERE id=?").bind(id).first<Row>(),caseNumber=clean(existing?.case_number,40)||`CR-${Date.now().toString().slice(-8)}`;
      await env.DB.prepare("INSERT INTO service_cases(id,case_number,parent_case_id,source,subject,description,priority,queue,status,owner,skills_json,contact_id,company_id,deal_id,product,inbox_message_id,response_due_at,resolution_due_at,first_responded_at,resolved_at,escalated_at,escalation_reason,portal_visible,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET parent_case_id=excluded.parent_case_id,subject=excluded.subject,description=excluded.description,priority=excluded.priority,queue=excluded.queue,status=excluded.status,owner=excluded.owner,skills_json=excluded.skills_json,contact_id=excluded.contact_id,company_id=excluded.company_id,deal_id=excluded.deal_id,product=excluded.product,response_due_at=excluded.response_due_at,resolution_due_at=excluded.resolution_due_at,first_responded_at=CASE WHEN excluded.status IN ('In progress','Waiting on customer','Resolved','Closed') THEN COALESCE(service_cases.first_responded_at,excluded.updated_at) ELSE service_cases.first_responded_at END,resolved_at=CASE WHEN excluded.status IN ('Resolved','Closed') THEN excluded.updated_at ELSE NULL END,escalated_at=CASE WHEN excluded.status='Escalated' THEN COALESCE(service_cases.escalated_at,excluded.updated_at) ELSE service_cases.escalated_at END,escalation_reason=excluded.escalation_reason,portal_visible=excluded.portal_visible,updated_at=excluded.updated_at").bind(id,caseNumber,clean(body.parentCaseId,80)||null,clean(body.source,80)||"Manual",subject,clean(body.description),priority,clean(body.queue,120)||"General",clean(body.status,80)||"New",clean(body.owner,200),JSON.stringify(csv(body.skills)),optionalId(body.contactId),optionalId(body.companyId),optionalId(body.dealId),clean(body.product,240),clean(body.inboxMessageId,100)||null,clean(body.responseDueAt,40)||hoursFromNow(responseHours),clean(body.resolutionDueAt,40)||hoursFromNow(resolutionHours),null,null,null,clean(body.escalationReason,1000),body.portalVisible===false?0:1,clean(existing?.created_at,40)||now,now).run();
      await audit(user,"case.save","service_case",id,`Saved case ${caseNumber}`,body); return Response.json({id,caseNumber},{status:201});
    }
    if (action === "addCaseNote") {
      const caseId=clean(body.caseId,80),note=clean(body.body,12000);if(!caseId||!note)throw new Error("Case and note are required.");const id=crypto.randomUUID();await env.DB.prepare("INSERT INTO case_notes(id,case_id,body,internal,author,created_at) VALUES (?,?,?,?,?,?)").bind(id,caseId,note,body.internal===false?0:1,user.email,now).run();await env.DB.prepare("UPDATE service_cases SET updated_at=? WHERE id=?").bind(now,caseId).run();await audit(user,"case.note","service_case",caseId,body.internal===false?"Added customer-visible case update":"Added internal case note",{internal:body.internal!==false});return Response.json({id},{status:201});
    }
    if (action === "saveArticle") {
      const id=clean(body.id,80)||crypto.randomUUID(),title=clean(body.title,400),articleSlug=slug(body.slug||title),status=clean(body.status,80)||"Draft";if(!title||!clean(body.body))throw new Error("Article title and content are required.");
      await env.DB.prepare("INSERT INTO knowledge_articles(id,title,slug,summary,body,category,status,audience,owner,published_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,slug=excluded.slug,summary=excluded.summary,body=excluded.body,category=excluded.category,status=excluded.status,audience=excluded.audience,owner=excluded.owner,published_at=CASE WHEN excluded.status='Published' THEN COALESCE(knowledge_articles.published_at,excluded.updated_at) ELSE knowledge_articles.published_at END,updated_at=excluded.updated_at").bind(id,title,articleSlug,clean(body.summary,1000),clean(body.body,24000),clean(body.category,120)||"General",status,clean(body.audience,80)||"Customers",clean(body.owner,200)||user.email,status==="Published"?now:null,now,now).run();await audit(user,"knowledge.save","knowledge_article",id,`Saved knowledge article ${title}`,body);return Response.json({id},{status:201});
    }
    if (action === "createPortalAccess") {
      const companyId=optionalId(body.companyId),contactId=optionalId(body.contactId);if(!companyId||!contactId)throw new Error("Company and contact are required.");const token=`crp_${crypto.randomUUID().replaceAll("-","")}`,id=crypto.randomUUID();await env.DB.prepare("INSERT INTO customer_portal_access(id,company_id,contact_id,token_hash,status,permissions_json,expires_at,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(id,companyId,contactId,await sha256(token),"Active",JSON.stringify(csv(body.permissions).length?csv(body.permissions):["cases","documents","onboarding","knowledge"]),clean(body.expiresAt,40)||null,now).run();await audit(user,"portal.access.create","customer_portal_access",id,"Created customer portal access",{companyId,contactId,expiresAt:body.expiresAt});return Response.json({id,token,url:`/portal?token=${encodeURIComponent(token)}`},{status:201});
    }
    if (action === "saveFieldCapture") {
      const id=clean(body.id,80)||crypto.randomUUID(),type=clean(body.type,80)||"Quick note",note=clean(body.note,12000),audio=clean(body.audioData,4_500_000),image=clean(body.imageData,7_500_000);const existing=(await rows("SELECT captured_by FROM field_captures WHERE id=?",id))[0];if(existing&&String(existing.captured_by).toLowerCase()!==user.email.toLowerCase()&&!canAdmin(user.role))return Response.json({error:"You can only update your own field captures."},{status:403});let audioObjectKey:string|null=null,attachmentObjectKey:string|null=null;const store=async(data:string,key:string,max:number)=>{const match=data.match(/^data:([^;]+);base64,(.+)$/);if(!match)throw new Error("The captured file format is not supported.");const binary=atob(match[2]);if(binary.length>max)throw new Error(`Captured files must be ${Math.round(max/1_000_000)} MB or smaller.`);const bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index++)bytes[index]=binary.charCodeAt(index);await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:match[1]}});return key};if(audio)audioObjectKey=await store(audio,`field-captures/${user.id}/${id}.webm`,3_000_000);if(image)attachmentObjectKey=await store(image,`field-captures/${user.id}/${id}.jpg`,5_000_000);await env.DB.prepare("INSERT INTO field_captures(id,type,status,contact_id,company_id,note,audio_object_key,attachment_object_key,latitude,longitude,accuracy,captured_by,captured_at,synced_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,contact_id=excluded.contact_id,company_id=excluded.company_id,note=excluded.note,audio_object_key=COALESCE(excluded.audio_object_key,field_captures.audio_object_key),attachment_object_key=COALESCE(excluded.attachment_object_key,field_captures.attachment_object_key),latitude=excluded.latitude,longitude=excluded.longitude,accuracy=excluded.accuracy,synced_at=excluded.synced_at").bind(id,type,"Synced",optionalId(body.contactId),optionalId(body.companyId),note,audioObjectKey,attachmentObjectKey,clean(body.latitude,40)||null,clean(body.longitude,40)||null,number(body.accuracy)||null,user.email,clean(body.capturedAt,40)||now,now).run();await audit(user,"field.capture","field_capture",id,`Saved ${type.toLowerCase()}`,{contactId:body.contactId,companyId:body.companyId,hasLocation:Boolean(body.latitude),hasAudio:Boolean(audioObjectKey),hasAttachment:Boolean(attachmentObjectKey)});return Response.json({id},{status:201});
    }
    throw new Error("Unknown platform action.");
  } catch (error) { return Response.json({ error:error instanceof Error?error.message:"The change could not be saved." }, { status:400 }); }
}
