import { env } from "cloudflare:workers";
import { audit, can, crmUser } from "@/lib/crm-auth";
import { decryptToken, encryptToken, graph, refreshMicrosoft } from "@/lib/microsoft";
import { notify, stopSequencesForReply, systemEvent } from "@/lib/operations";

type Row=Record<string,unknown>;type Contact={id:number;email:string};
export async function POST(request:Request){
  const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});if(!can(user,"records.edit"))return Response.json({error:"Edit access is required."},{status:403});
  try{
    const account=await env.DB.prepare("SELECT * FROM integration_accounts WHERE provider='microsoft'").first<Row>();if(!account)return Response.json({error:"Connect Microsoft 365 first."},{status:409});
    let access=await decryptToken(String(account.access_token)),refresh=await decryptToken(String(account.refresh_token));
    if(new Date(String(account.expires_at)).getTime()<Date.now()+120000){const next=await refreshMicrosoft(refresh);access=String(next.access_token);refresh=String(next.refresh_token||refresh);await env.DB.prepare("UPDATE integration_accounts SET access_token=?,refresh_token=?,expires_at=?,updated_at=datetime('now') WHERE provider='microsoft'").bind(await encryptToken(access),await encryptToken(refresh),new Date(Date.now()+Number(next.expires_in||3600)*1000).toISOString()).run();}
    const profile=await graph("/me?$select=mail,userPrincipalName",access),own=String(profile.mail||profile.userPrincipalName||account.account_email||"").toLowerCase(),contacts=(await env.DB.prepare("SELECT id,lower(email) AS email FROM contacts").all<Contact>()).results,byEmail=new Map(contacts.map(c=>[c.email,c.id])),since=new Date(Date.now()-30*86400000).toISOString(),until=new Date(Date.now()+180*86400000).toISOString();let messages=0,meetings=0,replies=0,tasks=0;
    if(account.sync_email){const mail=await graph(`/me/messages?$top=100&$select=id,subject,from,toRecipients,receivedDateTime,sentDateTime,isDraft&$filter=receivedDateTime ge ${since}`,access);for(const item of (mail.value as Row[]||[])){if(item.isDraft)continue;const from=((item.from as {emailAddress?:{address?:string}})?.emailAddress?.address||"").toLowerCase(),recipients=(item.toRecipients as Array<{emailAddress?:{address?:string}}>||[]).map(r=>(r.emailAddress?.address||"").toLowerCase()),match=[from,...recipients].find(email=>byEmail.has(email));if(!match)continue;const contactId=Number(byEmail.get(match)),occurred=String(item.receivedDateTime||item.sentDateTime||new Date().toISOString()),record=await env.DB.prepare("INSERT OR IGNORE INTO sync_records(provider,external_id,item_type,contact_id,occurred_at,created_at) VALUES ('microsoft',?,'email',?,?,datetime('now'))").bind(String(item.id),contactId,occurred).run();if(record.meta.changes){const inbound=from===match&&from!==own;await env.DB.prepare("INSERT INTO activities(contact_id,type,note,happened_at) VALUES (?,?,?,?)").bind(contactId,inbound?"Email received":"Email sent",String(item.subject||"Email"),occurred).run();messages++;if(inbound){const stopped=await stopSequencesForReply(contactId,`Reply: ${String(item.subject||"Email")}`);if(stopped){await notify(user.email,"reply","Prospect replied",String(item.subject||"Email reply"),"contact",contactId,"/?view=today");replies++;}}}}
    }
    if(account.sync_calendar){const calendar=await graph(`/me/calendarView?startDateTime=${encodeURIComponent(since)}&endDateTime=${encodeURIComponent(until)}&$top=100&$select=id,subject,start,end,organizer,attendees,isCancelled`,access);for(const item of (calendar.value as Row[]||[])){if(item.isCancelled)continue;const organizer=(((item.organizer as {emailAddress?:{address?:string}})?.emailAddress?.address)||"").toLowerCase(),attendees=(item.attendees as Array<{emailAddress?:{address?:string}}>||[]).map(a=>(a.emailAddress?.address||"").toLowerCase()),match=[organizer,...attendees].find(email=>byEmail.has(email));if(!match)continue;const contactId=Number(byEmail.get(match)),occurred=String((item.start as {dateTime?:string})?.dateTime||new Date().toISOString()),ended=String((item.end as {dateTime?:string})?.dateTime||occurred),record=await env.DB.prepare("INSERT OR IGNORE INTO sync_records(provider,external_id,item_type,contact_id,occurred_at,created_at) VALUES ('microsoft',?,'meeting',?,?,datetime('now'))").bind(String(item.id),contactId,occurred).run();if(record.meta.changes){await env.DB.prepare("INSERT INTO activities(contact_id,type,note,happened_at) VALUES (?,'Calendar meeting',?,?)").bind(contactId,String(item.subject||"Calendar meeting"),occurred).run();meetings++;if(account.auto_tasks&&new Date(ended).getTime()<Date.now()&&new Date(ended).getTime()>Date.now()-7*86400000){await env.DB.prepare("INSERT INTO tasks(contact_id,title,due_date,owner,status,completed) VALUES (?,?,date('now','+1 day'),?,'Open',0)").bind(contactId,`Follow up: ${String(item.subject||"meeting")}`,user.email).run();tasks++;}}}}
    await env.DB.prepare("UPDATE integration_accounts SET last_synced_at=datetime('now'),updated_at=datetime('now') WHERE provider='microsoft'").run();await audit(user,"integration.sync","integration","microsoft",`Synced ${messages} emails and ${meetings} meetings`,{messages,meetings,replies,tasks});return Response.json({messages,meetings,replies,tasks});
  }catch(error){const message=error instanceof Error?error.message:"Microsoft synchronization failed.";await systemEvent("error","integration","microsoft",message);return Response.json({error:message},{status:500});}
}
