import { env } from "cloudflare:workers";
import { audit, canEdit, crmUser } from "@/lib/crm-auth";
import { decryptToken, encryptToken, graph, refreshMicrosoft } from "@/lib/microsoft";

type Contact = { id: number; email: string };
export async function POST(request: Request) {
  const user = await crmUser(request); if (!user) return Response.json({ error: "Sign in is required." }, { status: 401 }); if (!canEdit(user.role)) return Response.json({ error: "Your viewer role is read-only." }, { status: 403 });
  try {
    const account = await env.DB.prepare("SELECT * FROM integration_accounts WHERE provider='microsoft'").first<Record<string, unknown>>(); if (!account) return Response.json({ error: "Connect Microsoft 365 first." }, { status: 409 });
    let access = await decryptToken(String(account.access_token)); let refresh = await decryptToken(String(account.refresh_token));
    if (new Date(String(account.expires_at)).getTime() < Date.now() + 120000) { const next = await refreshMicrosoft(refresh); access = String(next.access_token); refresh = String(next.refresh_token || refresh); await env.DB.prepare("UPDATE integration_accounts SET access_token=?,refresh_token=?,expires_at=?,updated_at=datetime('now') WHERE provider='microsoft'").bind(await encryptToken(access), await encryptToken(refresh), new Date(Date.now() + Number(next.expires_in || 3600) * 1000).toISOString()).run(); }
    const contacts = (await env.DB.prepare("SELECT id,lower(email) AS email FROM contacts").all<Contact>()).results, byEmail = new Map(contacts.map(c => [c.email, c.id]));
    const since = new Date(Date.now() - 30 * 86400000).toISOString(), until = new Date(Date.now() + 180 * 86400000).toISOString();
    const [mail, calendar] = await Promise.all([graph(`/me/messages?$top=100&$select=id,subject,from,toRecipients,receivedDateTime,sentDateTime&$filter=receivedDateTime ge ${since}`, access), graph(`/me/calendarView?startDateTime=${encodeURIComponent(since)}&endDateTime=${encodeURIComponent(until)}&$top=100&$select=id,subject,start,end,organizer,attendees,isCancelled`, access)]);
    let messages = 0, meetings = 0;
    for (const item of (mail.value as Array<Record<string, unknown>> || [])) { const from = ((item.from as { emailAddress?: { address?: string } })?.emailAddress?.address || "").toLowerCase(); const recipients = (item.toRecipients as Array<{ emailAddress?: { address?: string } }> || []).map(r => (r.emailAddress?.address || "").toLowerCase()); const match = [from, ...recipients].find(e => byEmail.has(e)); if (!match) continue; const record = await env.DB.prepare("INSERT OR IGNORE INTO sync_records (provider,external_id,item_type,contact_id,occurred_at,created_at) VALUES ('microsoft',?,'email',?,?,datetime('now'))").bind(String(item.id), byEmail.get(match), String(item.receivedDateTime || item.sentDateTime || new Date().toISOString())).run(); if (record.meta.changes) { await env.DB.prepare("INSERT INTO activities (contact_id,type,note,happened_at) VALUES (?,'Synced email',?,?)").bind(byEmail.get(match), String(item.subject || "Email"), String(item.receivedDateTime || item.sentDateTime || new Date().toISOString())).run(); messages++; } }
    for (const item of (calendar.value as Array<Record<string, unknown>> || [])) { if (item.isCancelled) continue; const organizer = (((item.organizer as { emailAddress?: { address?: string } })?.emailAddress?.address) || "").toLowerCase(); const attendees = (item.attendees as Array<{ emailAddress?: { address?: string } }> || []).map(a => (a.emailAddress?.address || "").toLowerCase()); const match = [organizer, ...attendees].find(e => byEmail.has(e)); if (!match) continue; const occurred = String((item.start as { dateTime?: string })?.dateTime || new Date().toISOString()); const record = await env.DB.prepare("INSERT OR IGNORE INTO sync_records (provider,external_id,item_type,contact_id,occurred_at,created_at) VALUES ('microsoft',?,'meeting',?,?,datetime('now'))").bind(String(item.id), byEmail.get(match), occurred).run(); if (record.meta.changes) { await env.DB.prepare("INSERT INTO activities (contact_id,type,note,happened_at) VALUES (?,'Synced meeting',?,?)").bind(byEmail.get(match), String(item.subject || "Calendar meeting"), occurred).run(); meetings++; } }
    await env.DB.prepare("UPDATE integration_accounts SET last_synced_at=datetime('now'),updated_at=datetime('now') WHERE provider='microsoft'").run(); await audit(user, "integration.sync", "integration", "microsoft", `Synced ${messages} emails and ${meetings} meetings`); return Response.json({ messages, meetings });
  } catch (error) { console.error(error); return Response.json({ error: error instanceof Error ? error.message : "Microsoft synchronization failed." }, { status: 500 }); }
}
