"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, FileSignature, LoaderCircle } from "lucide-react";

type Data={proposal:{id:number;title:string;amount:number;status:string;validUntil:string|null;bodyMarkdown:string;contractStartDate:string|null;contractEndDate:string|null;renewalTermMonths:number|null;renewalNoticeDays:number|null;autoRenew:boolean;contractTerms:string;contractStatus:string;acceptedAt:string|null;acceptedBy:string|null;signerName:string|null;signerEmail:string|null;signerTitle:string|null};deal:{name:string;company:string};brand:{businessName:string;logoUrl:string;physicalAddress:string}};
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value/100);
const date=(value:string|null)=>value?new Date(`${value}T12:00:00`).toLocaleDateString():"—";

export default function ProposalPage({params}:{params:{token:string}}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState(""),[title,setTitle]=useState(""),[signature,setSignature]=useState(""),[acceptTerms,setAcceptTerms]=useState(false),[busy,setBusy]=useState(false),[accepted,setAccepted]=useState(false);
 useEffect(()=>{void fetch(`/api/proposal-public?token=${encodeURIComponent(params.token)}`,{cache:"no-store"}).then(async response=>{const body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error||"Proposal could not be opened.");setData(body);setAccepted(Boolean(body.proposal.acceptedAt));setEmail(body.proposal.signerEmail||"")}).catch(reason=>setError(reason instanceof Error?reason.message:"Proposal could not be opened."))},[params.token]);
 const sign=async()=>{setBusy(true);setError("");try{const response=await fetch("/api/proposal-public",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token:params.token,signerName:name,signerEmail:email,signerTitle:title,signatureText:signature,acceptTerms})}),body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"Proposal could not be accepted.");setAccepted(true)}catch(reason){setError(reason instanceof Error?reason.message:"Proposal could not be accepted.")}finally{setBusy(false)}};
 if(error&&!data)return <main className="grid min-h-screen place-items-center bg-slate-100 p-5"><section className="max-w-lg rounded-2xl border bg-white p-8 text-center shadow-sm"><h1 className="text-xl font-semibold text-slate-900">Proposal unavailable</h1><p className="mt-3 text-slate-600">{error}</p></section></main>;
 if(!data)return <main className="grid min-h-screen place-items-center bg-slate-100 text-slate-600"><LoaderCircle className="animate-spin"/>Loading proposal…</main>;
 const {proposal,brand,deal}=data;
 return <main className="min-h-screen bg-slate-100 px-4 py-8 text-slate-900 sm:px-8"><section className="mx-auto max-w-4xl overflow-hidden rounded-2xl border bg-white shadow-sm"><header className="border-b px-6 py-7 sm:px-10"><div className="flex flex-wrap items-start justify-between gap-6"><div className="flex items-center gap-4">{brand.logoUrl&&<img src={brand.logoUrl} alt="" className="max-h-12 max-w-44 object-contain"/>}<div><p className="text-sm font-semibold text-[#3156c9]">{brand.businessName}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">{proposal.title}</h1></div></div><div className="text-sm text-slate-500">Prepared for<br/><strong className="text-slate-800">{deal.company||deal.name}</strong></div></div></header>
 <div className="grid gap-8 px-6 py-8 sm:px-10"><div className="grid gap-4 rounded-xl border bg-slate-50 p-5 sm:grid-cols-3"><div><p className="text-xs font-medium uppercase tracking-wide text-slate-500">Investment</p><p className="mt-1 text-xl font-semibold">{money(proposal.amount)}</p></div><div><p className="text-xs font-medium uppercase tracking-wide text-slate-500">Valid through</p><p className="mt-1 font-semibold">{date(proposal.validUntil)}</p></div><div><p className="text-xs font-medium uppercase tracking-wide text-slate-500">Contract status</p><p className="mt-1 font-semibold">{proposal.contractStatus}</p></div></div>
 <article className="whitespace-pre-wrap text-[16px] leading-7 text-slate-700">{proposal.bodyMarkdown}</article>
 <section className="rounded-xl border"><div className="border-b px-5 py-4"><h2 className="font-semibold">Contract and renewal terms</h2></div><div className="grid gap-5 p-5 sm:grid-cols-2"><div className="space-y-2 text-sm"><p><strong>Start date:</strong> {date(proposal.contractStartDate)}</p><p><strong>End date:</strong> {date(proposal.contractEndDate)}</p><p><strong>Renewal term:</strong> {proposal.renewalTermMonths?`${proposal.renewalTermMonths} months`:"Not specified"}</p><p><strong>Notice period:</strong> {proposal.renewalNoticeDays?`${proposal.renewalNoticeDays} days`:"Not specified"}</p><p><strong>Renewal:</strong> {proposal.autoRenew?"Renews automatically unless notice is given.":"Does not renew automatically."}</p></div><p className="whitespace-pre-wrap text-sm leading-6 text-slate-600">{proposal.contractTerms||"No additional terms were added to this proposal."}</p></div></section>
 {accepted?<section className="rounded-xl border border-emerald-200 bg-emerald-50 p-6"><div className="flex items-center gap-3"><CheckCircle2 className="text-emerald-600"/><div><h2 className="font-semibold text-emerald-950">Proposal accepted</h2><p className="mt-1 text-sm text-emerald-800">Signed by {proposal.signerName||"the authorized representative"}{proposal.acceptedAt?` on ${new Date(proposal.acceptedAt).toLocaleString()}`:""}.</p></div></div></section>:<section className="rounded-xl border border-blue-200 bg-blue-50/40 p-5"><div className="flex items-center gap-2"><FileSignature size={19} className="text-[#3156c9]"/><h2 className="font-semibold">Accept and sign</h2></div><p className="mt-2 text-sm leading-6 text-slate-600">By signing, you confirm that you are authorized to accept this proposal on behalf of the customer and agree to the terms shown above.</p>{error&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-2"><input value={name} onChange={event=>setName(event.target.value)} placeholder="Full legal name" className="h-10 rounded-md border bg-white px-3 text-sm"/><input value={email} onChange={event=>setEmail(event.target.value)} type="email" placeholder="Business email" className="h-10 rounded-md border bg-white px-3 text-sm"/><input value={title} onChange={event=>setTitle(event.target.value)} placeholder="Title / role" className="h-10 rounded-md border bg-white px-3 text-sm sm:col-span-2"/><input value={signature} onChange={event=>setSignature(event.target.value)} placeholder="Type your full legal name as your signature" className="h-10 rounded-md border bg-white px-3 text-sm sm:col-span-2"/></div><label className="mt-4 flex items-start gap-2 text-sm text-slate-700"><input checked={acceptTerms} onChange={event=>setAcceptTerms(event.target.checked)} type="checkbox" className="mt-1"/>I am authorized to accept this proposal and agree that my typed name is my electronic signature.</label><button disabled={busy} onClick={()=>void sign()} className="mt-5 inline-flex h-10 items-center justify-center rounded-md bg-[#3156c9] px-5 text-sm font-semibold text-white disabled:opacity-60">{busy?"Submitting signature…":"Accept and sign proposal"}</button></section>}
 </div><footer className="border-t px-6 py-5 text-xs text-slate-500 sm:px-10">{brand.businessName}{brand.physicalAddress?` · ${brand.physicalAddress}`:""}</footer></section></main>;
}
