"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, MailX } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function UnsubscribePage(){
 const[done,setDone]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[link,setLink]=useState<{email:string;token:string}|null>(null),[ready,setReady]=useState(false);
 useEffect(()=>{const timer=window.setTimeout(()=>{const params=new URLSearchParams(window.location.search),email=params.get("email")||"",token=params.get("token")||"";if(email&&token)setLink({email,token});setReady(true)},0);return()=>window.clearTimeout(timer)},[]);
 async function submit(){if(!link)return;setBusy(true);setError("");const response=await fetch("/api/unsubscribe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(link)});const result=await response.json().catch(()=>({})) as {error?:string};setBusy(false);if(!response.ok){setError(result.error||"We could not process that request.");return}setDone(true)}
 return <main className="grid min-h-screen place-items-center bg-[#f3f5f8] p-5"><section className="w-full max-w-md rounded-2xl border bg-white p-8 text-center shadow-sm"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#e8edff] text-[#3968ff]">{done?<CheckCircle2 size={26}/>:<MailX size={26}/>}</div>{done?<><h1 className="mt-5 text-2xl font-semibold text-[#111b31]">You’re unsubscribed</h1><p className="mt-3 leading-7 text-slate-600">This address has been added to our suppression list and will not receive future marketing campaigns.</p></>:<><h1 className="mt-5 text-2xl font-semibold text-[#111b31]">Unsubscribe from marketing emails</h1>{!ready?<p className="mt-3 leading-7 text-slate-600">Loading…</p>:link?<><p className="mt-3 leading-7 text-slate-600">Stop marketing emails to <strong className="break-all text-slate-800">{link.email}</strong>? Transactional messages may still be sent when required.</p>{error&&<p className="mt-4 text-sm text-red-700">{error}</p>}<Button className="mt-6 w-full" disabled={busy} onClick={submit}>{busy?"Processing…":"Unsubscribe"}</Button></>:<p className="mt-3 leading-7 text-slate-600">To unsubscribe, use the unsubscribe link at the bottom of the email you received. That link confirms the request for your address automatically.</p>}</>}<p className="mt-7 text-xs text-slate-400">Email preferences</p></section></main>;
}
