import { env } from "cloudflare:workers";
import { audit, can, crmUser } from "@/lib/crm-auth";

type Row=Record<string,unknown>;
const clean=(value:unknown,max=8000)=>String(value??"").trim().slice(0,max);
const optionalId=(value:unknown)=>{const result=Number(value);return Number.isInteger(result)&&result>0?result:null};
const parse=(value:unknown,fallback:unknown)=>{try{return JSON.parse(String(value??""))}catch{return fallback}};
const splitName=(name:string)=>{const parts=name.trim().split(/\s+/).filter(Boolean);return {firstName:parts[0]||"Unknown",lastName:parts.slice(1).join(" ")||"Contact"}};

export async function GET(request:Request){const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});if(!can(user,"records.view"))return Response.json({error:"View access is required."},{status:403});try{// Contacts, companies and deals are chosen with server-side search pickers (GET /api/crm?resource=search), not shipped here.
const items=(await env.DB.prepare("SELECT * FROM communication_review_items WHERE status='Pending' ORDER BY created_at DESC LIMIT 300").all<Row>()).results;return Response.json({items:items.map(item=>({...item,evidence:parse(item.evidence_json,{}),suggestedContact:parse(item.suggested_contact_json,{}),companyCandidates:parse(item.company_candidates_json,[]),dealCandidates:parse(item.deal_candidates_json,[])}))})}catch{return Response.json({error:"The communication review inbox is not available."},{status:503})}}

export async function POST(request:Request){const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});if(!can(user,"records.edit"))return Response.json({error:"Edit access is required."},{status:403});try{const body=await request.json() as Row,action=clean(body.action,40),itemId=clean(body.id,100),now=new Date().toISOString(),item=await env.DB.prepare("SELECT * FROM communication_review_items WHERE id=? AND status='Pending'").bind(itemId).first<Row>();if(!item)throw new Error("This review item is no longer pending.");if(action==="dismiss"){await env.DB.prepare("UPDATE communication_review_items SET status='Dismissed',reviewed_at=?,reviewed_by=? WHERE id=?").bind(now,user.email,itemId).run();await audit(user,"communication_review.dismiss","communication_review",itemId,"Dismissed communication suggestion",{});return Response.json({ok:true})}if(action!=="resolve")throw new Error("Choose resolve or dismiss.");
 let contactId=optionalId(body.contactId)||optionalId(item.contact_id),companyId=optionalId(body.companyId)||optionalId(item.company_id),dealId=optionalId(body.dealId);const suggested=parse(item.suggested_contact_json,{}) as Row;
 if(!contactId&&body.createContact!==false){const email=clean(body.email||suggested.email||item.sender_email,320).toLowerCase(),fullName=clean(body.name||suggested.name||item.sender_name,240)||email.split("@")[0].replace(/[._-]+/g," "),name=splitName(fullName),existing=await env.DB.prepare("SELECT id FROM contacts WHERE lower(email)=?").bind(email).first<Row>();if(existing)contactId=Number(existing.id);else{if(!email.match(/^[^\s@]+@[^\s@]+\.[^\s@]+$/))throw new Error("A valid contact email is required.");const company=companyId?await env.DB.prepare("SELECT name FROM companies WHERE id=?").bind(companyId).first<Row>():null,result=await env.DB.prepare("INSERT INTO contacts(first_name,last_name,email,company,title,phone,location,notes,lead_source,stage,tags,subscribed,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'','Communication review','Lead','[]',1,?,?)").bind(name.firstName,name.lastName,email,clean(company?.name),clean(body.title||suggested.title,240),clean(body.phone||suggested.phone,80),clean(body.location||suggested.location,240),now,now).run();contactId=Number(result.meta.last_row_id)}}
 if(!companyId&&clean(body.newCompanyName)){const result=await env.DB.prepare("INSERT INTO companies(name,domain,stage,owner,updated_at) VALUES (?,?,'Prospect',?,?) ON CONFLICT(name) DO UPDATE SET updated_at=excluded.updated_at RETURNING id").bind(clean(body.newCompanyName,240),clean(body.companyDomain||suggested.companyDomain,240),user.email,now).first<Row>();companyId=optionalId(result?.id)}
 if(contactId&&companyId){const company=await env.DB.prepare("SELECT name FROM companies WHERE id=?").bind(companyId).first<Row>();if(company)await env.DB.prepare("UPDATE contacts SET company=?,updated_at=? WHERE id=?").bind(company.name,now,contactId).run()}
 await env.DB.batch([env.DB.prepare("UPDATE communication_review_items SET status='Resolved',contact_id=?,company_id=?,deal_id=?,reviewed_at=?,reviewed_by=? WHERE id=?").bind(contactId,companyId,dealId,now,user.email,itemId),env.DB.prepare("UPDATE inbox_messages SET contact_id=?,company_id=?,deal_id=?,status='Assigned',owner=?,updated_at=? WHERE id=? OR external_id=?").bind(contactId,companyId,dealId,user.email,now,item.source_id,item.source_id),env.DB.prepare("UPDATE sync_records SET contact_id=?,deal_id=? WHERE external_id=?").bind(contactId,dealId,item.source_id)]);
 if(contactId&&clean(item.subject)){await env.DB.prepare("INSERT INTO activities(contact_id,type,note,happened_at) VALUES (?,'Communication reviewed',?,?)").bind(contactId,clean(item.subject,500),now).run()}await audit(user,"communication_review.resolve","communication_review",itemId,"Resolved communication associations",{contactId,companyId,dealId,createdContact:!item.contact_id});return Response.json({ok:true,contactId,companyId,dealId})
 }catch(error){return Response.json({error:error instanceof Error?error.message:"The review item could not be saved."},{status:400})}}
