"use client";

import { useCallback, useEffect, useState } from "react";
import { Check, Clipboard, Pencil, RotateCcw, Save, Sparkles, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { Row } from "@/lib/crm-types";

type Draft={title:string;executiveSummary:string;sections:Array<{heading:string;content:string}>;bodyMarkdown:string;suggestedAmount:number;validUntil:string;confidence:"Low"|"Medium"|"High";explanation:string;dataGaps:string[]};
type Artifact={id:string;reviewStatus:string;content:Draft;provider:string;model:string;promptVersion:number;generatedAt:string;generatedBy:string;reviewedAt:string|null;reviewedBy:string|null;sourceCount:number};
type State={drafts:Artifact[];providerConfigured:boolean;settings:{enabled:boolean};permissions:{generate:boolean;review:boolean;edit:boolean}};
const when=(value:unknown)=>value?new Date(String(value)).toLocaleString():"";
const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);
const copy=(draft:Draft)=>JSON.parse(JSON.stringify(draft)) as Draft;

export function AIProposalPanel({dealId,onSaved}:{dealId:number;onSaved:()=>Promise<void>}){
  const[data,setData]=useState<State|null>(null),[activeId,setActiveId]=useState(""),[editing,setEditing]=useState<Draft|null>(null),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const response=await fetch(`/api/ai-proposals?dealId=${dealId}`,{cache:"no-store"}),body=await response.json() as State&{error?:string};if(!response.ok)throw new Error(body.error||"AI proposals could not load.");setData(body);setActiveId(current=>current&&body.drafts.some(item=>item.id===current)?current:String(body.drafts[0]?.id||""))},[dealId]);
  useEffect(()=>{void load().catch(reason=>setError(reason instanceof Error?reason.message:"AI proposals could not load."))},[load]);
  const active=data?.drafts.find(item=>item.id===activeId)||data?.drafts[0]||null;
  const request=async(payload:Row,message:string)=>{setBusy(String(payload.action));setError("");try{const response=await fetch("/api/ai-proposals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({dealId,...payload})}),body=await response.json() as {error?:string;artifact?:Artifact};if(!response.ok)throw new Error(body.error||"The proposal action could not be completed.");await load();if(body.artifact)setActiveId(body.artifact.id);setNotice(message);window.setTimeout(()=>setNotice(""),2600);return body}catch(reason){setError(reason instanceof Error?reason.message:"The proposal action could not be completed.");return null}finally{setBusy("")}};
  const generate=(force=false)=>{setEditing(null);void request({action:"generate",force},force?"A new proposal draft was generated":"Proposal draft prepared")};
  const review=(status:"Accepted"|"Rejected"|"Edited",content?:Draft)=>active&&void request({action:"review",artifactId:active.id,status,content},status==="Accepted"?"Proposal draft accepted":status==="Rejected"?"Proposal draft rejected":"Proposal edits saved").then(result=>{if(result)setEditing(null)});
  const save=()=>active&&void request({action:"saveProposal",artifactId:active.id,content:editing||active.content,title:(editing||active.content).title,amount:(editing||active.content).suggestedAmount/100,validUntil:(editing||active.content).validUntil},"Proposal saved to the deal").then(result=>{if(result){setEditing(null);void onSaved()}});
  const clipboard=async()=>{if(!active)return;await navigator.clipboard.writeText((editing||active.content).bodyMarkdown);setNotice("Proposal copied");window.setTimeout(()=>setNotice(""),2200)};
  return <div className="grid gap-5">
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><Check size={15}/>{notice}</p>}
    <section className="rounded-2xl border bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Sparkles size={18} className="text-blue-600"/><h3 className="font-semibold">AI proposal</h3></div><div className="flex items-center gap-2"><Badge variant={data?.settings.enabled&&data.providerConfigured?"default":"secondary"}>{data?.settings.enabled&&data.providerConfigured?"Model-backed":"Rules-based"}</Badge><Button size="sm" disabled={!data?.permissions.generate||Boolean(busy)} onClick={()=>generate(false)}><Sparkles size={15}/>{busy==="generate"?"Generating…":"Draft proposal"}</Button></div></div><p className="mt-2 text-sm text-slate-600">Create a reviewable proposal from this deal’s scope, stakeholders, customer activity, risks, and commercial record.</p></section>
    {active&&<section className="min-w-0 rounded-2xl border border-blue-200 bg-blue-50/30"><div className="border-b border-blue-100 bg-white/70 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-lg font-semibold">{active.content.title}</h3><Badge variant={active.reviewStatus==="Rejected"?"destructive":"secondary"}>{active.reviewStatus}</Badge><Badge variant="outline">{active.content.confidence} confidence</Badge></div><p className="mt-1 text-xs text-slate-500">Generated {when(active.generatedAt)} · {active.sourceCount} source groups · {active.model}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setEditing(editing?null:copy(active.content))}><Pencil size={14}/>{editing?"Cancel":"Edit"}</Button><Button size="sm" variant="outline" disabled={Boolean(busy)} onClick={()=>generate(true)}><RotateCcw size={14}/>Regenerate</Button><Button size="sm" variant="outline" onClick={()=>void clipboard()}><Clipboard size={14}/>Copy</Button></div></div></div>
      <div className="px-4 pb-4">{editing?<ProposalEditor draft={editing} change={setEditing}/>:<ProposalView draft={active.content}/>}<div className="mt-4 rounded-xl border bg-white p-4 text-sm text-slate-600"><strong className="text-slate-900">Why this was generated</strong><p className="mt-1 leading-6">{active.content.explanation}</p>{active.content.dataGaps.length>0&&<p className="mt-2 text-amber-700">Data gaps: {active.content.dataGaps.join(" ")}</p>}</div></div>
      <div className="border-t border-blue-100 bg-white p-4"><div className="flex flex-wrap gap-2">{editing?<Button size="sm" disabled={!data?.permissions.review||Boolean(busy)} onClick={()=>review("Edited",editing)}><Check size={14}/>Save edits</Button>:<><>{active.reviewStatus==="Draft"&&<Button size="sm" disabled={!data?.permissions.review||Boolean(busy)} onClick={()=>review("Accepted")}><Check size={14}/>Accept</Button>}</>{active.reviewStatus!=="Rejected"&&<Button size="sm" variant="outline" disabled={!data?.permissions.review||Boolean(busy)} onClick={()=>review("Rejected")}><X size={14}/>Reject</Button>}</>}<Button size="sm" disabled={!data?.permissions.edit||!["Accepted","Edited"].includes(active.reviewStatus)||Boolean(busy)} onClick={save}><Save size={14}/>Save to deal</Button></div>{!editing&&!['Accepted','Edited'].includes(active.reviewStatus)&&<p className="mt-2 text-xs text-slate-500">Accept the draft or save edits before adding it to the deal.</p>}</div>
    </section>}
    {data&&data.drafts.length>1&&<section className="rounded-xl border p-4"><h3 className="text-sm font-semibold">Proposal drafts</h3><div className="mt-3 grid gap-2">{data.drafts.map(item=><button key={item.id} onClick={()=>{setActiveId(item.id);setEditing(null)}} className={`rounded-lg border p-3 text-left text-sm ${item.id===active?.id?"border-blue-300 bg-blue-50":"bg-white"}`}><strong>{item.content.title}</strong><span className="mt-1 block text-xs text-slate-500">{item.reviewStatus} · {when(item.generatedAt)}</span></button>)}</div></section>}
  </div>;
}

function ProposalView({draft}:{draft:Draft}){return <div className="mt-4 grid gap-3"><div className="rounded-xl border bg-white p-4"><h4 className="mb-2 text-sm font-semibold">Executive summary</h4><p className="whitespace-pre-wrap text-sm leading-6 text-slate-700">{draft.executiveSummary}</p></div><div className="rounded-xl border bg-white p-4"><h4 className="mb-3 text-sm font-semibold">Proposal content</h4><pre className="whitespace-pre-wrap font-sans text-sm leading-6 text-slate-700">{draft.bodyMarkdown}</pre></div><div className="flex flex-wrap gap-4 rounded-xl border bg-white p-4 text-sm"><span><strong>Suggested investment:</strong> {money(draft.suggestedAmount)}</span><span><strong>Valid until:</strong> {draft.validUntil||"[Confirm date]"}</span></div></div>}
function ProposalEditor({draft,change}:{draft:Draft;change:(value:Draft)=>void}){const set=(patch:Partial<Draft>)=>change({...draft,...patch});return <div className="mt-4 grid gap-3"><label className="grid gap-1 text-sm font-medium">Proposal title<Input value={draft.title} onChange={event=>set({title:event.target.value})}/></label><div className="grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Investment<Input type="number" min="0" step=".01" value={draft.suggestedAmount/100} onChange={event=>set({suggestedAmount:Math.round(Number(event.target.value||0)*100)})}/></label><label className="grid gap-1 text-sm font-medium">Valid until<Input type="date" value={draft.validUntil} onChange={event=>set({validUntil:event.target.value})}/></label></div><label className="grid gap-1 text-sm font-medium">Executive summary<Textarea rows={3} value={draft.executiveSummary} onChange={event=>set({executiveSummary:event.target.value})}/></label><label className="grid gap-1 text-sm font-medium">Proposal content <span className="font-normal text-slate-500">Markdown supported</span><Textarea className="h-[min(38dvh,30rem)] min-h-48 resize-y" value={draft.bodyMarkdown} onChange={event=>set({bodyMarkdown:event.target.value})}/></label></div>}
