"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BrainCircuit, Check, ChevronDown, RefreshCw, ShieldAlert, Sparkles, TrendingUp, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { Row } from "@/lib/crm-types";

type Artifact={id:string;entityId:string;reviewStatus:string;content:Row;explanation:string;confidence:number;provider:string;model:string;promptVersion:number;generatedAt:string;generatedBy:string;sourceCount:number};
type State={deals:Row[];reviews:Artifact[];forecast:Artifact|null;settings:{enabled:boolean};providerConfigured:boolean;permissions:{generate:boolean;review:boolean}};
const money=(value:unknown)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(value||0)/100);
const values=(value:unknown)=>Array.isArray(value)?value.map(item=>String(item)).filter(Boolean):[];
const confidence=(number:unknown)=>Number(number)>=80?"High":Number(number)>=60?"Medium":"Low";

function DetailList({title,items,tone="slate"}:{title:string;items:unknown;tone?:"slate"|"amber"|"blue"}){const rows=values(items);if(!rows.length)return null;const styles={slate:"border-slate-200 bg-slate-50 text-slate-700",amber:"border-amber-200 bg-amber-50 text-amber-900",blue:"border-blue-200 bg-blue-50 text-blue-900"}[tone];return <div className={`rounded-xl border p-3 ${styles}`}><strong className="text-xs uppercase tracking-wide">{title}</strong><ul className="mt-2 grid gap-1.5 text-sm leading-5">{rows.map((item,index)=><li key={index}>• {item}</li>)}</ul></div>}

function Audit({artifact}:{artifact:Artifact}){return <p className="mt-3 text-xs text-slate-500">Generated {new Date(artifact.generatedAt).toLocaleString()} · {confidence(artifact.confidence)} confidence · {artifact.sourceCount} source group{artifact.sourceCount===1?"":"s"} · {artifact.provider==="openai"?artifact.model:"ClientRecord rules"} v{artifact.promptVersion}</p>}

export function AIRevenueIntelligence(){
 const[data,setData]=useState<State|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(""),[dealId,setDealId]=useState(""),[expanded,setExpanded]=useState<string|null>(null);
 const load=useCallback(async()=>{try{const response=await fetch("/api/ai-revenue-intelligence",{cache:"no-store"}),body=await response.json() as State&{error?:string};if(!response.ok)throw new Error(body.error||"AI revenue intelligence could not load.");setData(body);setError("");setDealId(current=>current||String(body.deals[0]?.id||""));}catch(reason){setError(reason instanceof Error?reason.message:"AI revenue intelligence could not load.")}},[]);
 useEffect(()=>{void load()},[load]);
 const post=async(action:string,payload:Row={},success?:string)=>{setBusy(action);setError("");try{const response=await fetch("/api/ai-revenue-intelligence",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload})}),body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"AI analysis could not be completed.");if(success)setError(success);await load()}catch(reason){setError(reason instanceof Error?reason.message:"AI analysis could not be completed.")}finally{setBusy("")}};
 const selected=useMemo(()=>data?.deals.find(item=>String(item.id)===dealId)||null,[data,dealId]),latest=useMemo(()=>data?.reviews.find(item=>item.entityId===dealId)||null,[data,dealId]);
 if(!data)return <section className="mt-6 rounded-2xl border bg-white p-6 text-sm text-slate-500">{error||"Loading AI revenue intelligence…"}</section>;
 const modelReady=data.settings.enabled&&data.providerConfigured;
 return <section className="mt-6 rounded-2xl border bg-white shadow-[0_1px_2px_rgba(15,23,42,.03)]"><div className="flex flex-wrap items-start justify-between gap-4 border-b p-5"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e8edff] text-[#3156c9]"><BrainCircuit size={20}/></span><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">AI deal review & forecast explanation</h2><Badge variant={modelReady?"default":"secondary"}>{modelReady?"Model-backed":"Rules-based"}</Badge></div><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-600">Review deal changes and forecast coverage from recorded CRM evidence. Nothing is changed automatically.</p></div></div><Button size="sm" variant="outline" onClick={()=>void load()}><RefreshCw size={15}/>Refresh</Button></div>{error&&<div className={`mx-5 mt-4 rounded-xl p-3 text-sm ${error.startsWith("Generated")?"bg-emerald-50 text-emerald-800":"bg-red-50 text-red-700"}`}>{error}</div>}
 <div className="grid gap-6 p-5 xl:grid-cols-2"><div className="grid content-start gap-4"><div className="rounded-xl border bg-slate-50 p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-semibold">Weekly deal review</h3><p className="mt-1 text-sm text-slate-600">Risks, evidence, qualification gaps, and one practical action set.</p></div><div className="flex gap-2"><select value={dealId} onChange={event=>setDealId(event.target.value)} className="h-9 max-w-[250px] rounded-md border bg-white px-2 text-sm"><option value="">Choose deal</option>{data.deals.map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.name)} · {String(item.stage)}</option>)}</select><Button size="sm" disabled={!dealId||!data.permissions.generate||Boolean(busy)} onClick={()=>void post("generateDealReview",{dealId:Number(dealId),force:true},"Generated a fresh deal review.")}><Sparkles size={15}/>{busy==="generateDealReview"?"Reviewing…":"Review deal"}</Button></div></div></div>
 {selected&&<div className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{String(selected.name)}</strong><p className="mt-1 text-sm text-slate-500">{String(selected.company||"No company")} · {String(selected.stage)} · {money(selected.value)}</p></div><Badge variant="outline">{String(selected.forecastCategory||"Pipeline")}</Badge></div>{latest&&<Review artifact={latest} onReview={(status)=>void post("review",{artifactId:latest.id,status},`Analysis ${status.toLowerCase()}.`)} allowed={data.permissions.review} expanded={expanded===latest.id} toggle={()=>setExpanded(current=>current===latest.id?null:latest.id)}/>} {!latest&&<p className="mt-4 text-sm text-slate-500">Generate a review to see the evidence, risks, close-date credibility, and recommended actions.</p>}</div>}</div>
 <div className="grid content-start gap-4"><div className="rounded-xl border bg-slate-50 p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-semibold">Forecast explanation</h3><p className="mt-1 text-sm text-slate-600">What carries the forecast, what changed, and where coverage is thin.</p></div><Button size="sm" disabled={!data.permissions.generate||Boolean(busy)} onClick={()=>void post("generateForecast",{force:true},"Generated a fresh forecast explanation.")}><TrendingUp size={15}/>{busy==="generateForecast"?"Explaining…":"Explain forecast"}</Button></div></div>{data.forecast?<Forecast artifact={data.forecast} onReview={(status)=>void post("review",{artifactId:data.forecast?.id,status},`Analysis ${status.toLowerCase()}.`)} allowed={data.permissions.review} expanded={expanded===data.forecast.id} toggle={()=>setExpanded(current=>current===data.forecast?.id?null:data.forecast?.id??null)}/>:<div className="rounded-xl border border-dashed p-5 text-sm text-slate-500">Generate the first explanation to see current weighted forecast, committed coverage, movement, and close-date risks.</div>}</div></div></section>;
}
function Review({artifact,onReview,allowed,expanded,toggle}:{artifact:Artifact;onReview:(status:"Accepted"|"Rejected")=>void;allowed:boolean;expanded:boolean;toggle:()=>void}){const content=artifact.content,close=(content.closeDateCredibility&&typeof content.closeDateCredibility==="object"?content.closeDateCredibility:{}) as Row;return <div className="mt-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="text-sm">{String(content.headline||"Deal review")}</strong><p className="mt-1 text-sm text-slate-600">Close-date credibility: <b>{String(close.rating||"—")}</b>{close.reason?` — ${String(close.reason)}`:""}</p></div><div className="flex items-center gap-2"><Badge variant={artifact.reviewStatus==="Accepted"?"default":artifact.reviewStatus==="Rejected"?"destructive":"secondary"}>{artifact.reviewStatus}</Badge><Button size="sm" variant="ghost" onClick={toggle}>{expanded?"Less":"Details"}<ChevronDown size={15} className={expanded?"rotate-180":""}/></Button></div></div><div className="mt-3 grid gap-3"><DetailList title="Recommended actions" items={content.actions} tone="blue"/>{expanded&&<><DetailList title="What changed" items={content.whatChanged}/><DetailList title="Evidence" items={content.evidence}/><DetailList title="Risks" items={content.risks} tone="amber"/><DetailList title="Missing qualification" items={content.missingQualification} tone="amber"/><DetailList title="Data gaps" items={content.dataGaps}/></>} </div><Audit artifact={artifact}/>{allowed&&artifact.reviewStatus==="Draft"&&<div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>onReview("Accepted")}><Check size={15}/>Accept</Button><Button size="sm" variant="ghost" onClick={()=>onReview("Rejected")}><X size={15}/>Reject</Button></div>}</div>}
function Forecast({artifact,onReview,allowed,expanded,toggle}:{artifact:Artifact;onReview:(status:"Accepted"|"Rejected")=>void;allowed:boolean;expanded:boolean;toggle:()=>void}){const content=artifact.content;return <div className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{String(content.headline||"Forecast explanation")}</strong><div className="mt-3 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4"><span className="rounded-lg bg-slate-50 p-2"><b className="block text-xs text-slate-500">Weighted</b>{money(content.forecastTotal)}</span><span className="rounded-lg bg-slate-50 p-2"><b className="block text-xs text-slate-500">Commit</b>{money(content.commitTotal)}</span><span className="rounded-lg bg-slate-50 p-2"><b className="block text-xs text-slate-500">Best case</b>{money(content.bestCaseTotal)}</span><span className="rounded-lg bg-slate-50 p-2"><b className="block text-xs text-slate-500">Pipeline</b>{money(content.pipelineTotal)}</span></div></div><div className="flex items-center gap-2"><Badge variant={artifact.reviewStatus==="Accepted"?"default":artifact.reviewStatus==="Rejected"?"destructive":"secondary"}>{artifact.reviewStatus}</Badge><Button size="sm" variant="ghost" onClick={toggle}>{expanded?"Less":"Details"}<ChevronDown size={15} className={expanded?"rotate-180":""}/></Button></div></div><div className="mt-4 grid gap-3"><DetailList title="Commit drivers" items={content.commitDrivers} tone="blue"/>{expanded&&<><DetailList title="Recent movement" items={content.movements}/><DetailList title="Close-date risk" items={content.closeDateRisks} tone="amber"/><DetailList title="Coverage gaps" items={content.coverageGaps} tone="amber"/><DetailList title="Recommended actions" items={content.actions} tone="blue"/><DetailList title="Data gaps" items={content.dataGaps}/></>}</div><Audit artifact={artifact}/>{allowed&&artifact.reviewStatus==="Draft"&&<div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>onReview("Accepted")}><Check size={15}/>Accept</Button><Button size="sm" variant="ghost" onClick={()=>onReview("Rejected")}><X size={15}/>Reject</Button></div>}</div>}
