"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, ChevronDown, LoaderCircle, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { RecordPicker } from "@/components/record-picker";
import type { Row } from "@/lib/crm-types";
import { text } from "@/lib/format";

const notifyUndo=(token?:unknown,label="Change saved")=>window.dispatchEvent(new CustomEvent("crm:undoable",{detail:{token:text(token),label}}));

export function ContactCapture({onSaved}:{onSaved:()=>Promise<void>|void}){
 const[step,setStep]=useState(1),[name,setName]=useState(""),[email,setEmail]=useState(""),[matches,setMatches]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const timer=window.setTimeout(async()=>{if(!email&&!name){setMatches([]);return}const response=await fetch(`/api/quick-capture?email=${encodeURIComponent(email)}&name=${encodeURIComponent(name)}`),body=await response.json() as{matches?:Row[]};setMatches(body.matches||[])},280);return()=>window.clearTimeout(timer)},[email,name]);
 async function save(form:HTMLFormElement){setBusy(true);setError("");try{const values=Object.fromEntries(new FormData(form).entries()),response=await fetch("/api/quick-capture",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"commitDraft",draft:{kind:"contact",name,email,...values}})}),body=await response.json() as{error?:string;undoToken?:string};if(!response.ok)throw new Error(body.error||"Contact could not be created.");notifyUndo(body.undoToken,"Contact created");await onSaved()}catch(reason){setError(reason instanceof Error?reason.message:"Contact could not be created.")}finally{setBusy(false)}}
 return <form className="grid gap-4" onSubmit={event=>{event.preventDefault();void save(event.currentTarget)}}><div className="flex items-center gap-2 text-sm"><Badge>{step} of 2</Badge><span className="text-slate-500">{step===1?"Essential contact":"Optional relationship details"}</span></div><label className="grid gap-1 text-sm font-medium">Name<Input value={name} onChange={event=>setName(event.target.value)} required autoFocus placeholder="Jordan Lee"/></label><label className="grid gap-1 text-sm font-medium">Email<Input value={email} onChange={event=>setEmail(event.target.value)} required type="email" placeholder="jordan@company.com"/></label>{matches.length>0&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><strong>Possible duplicate{matches.length>1?"s":""}</strong>{matches.map(match=><p key={text(match.id)} className="mt-1">{text(match.firstName)} {text(match.lastName)} · {text(match.email)}{match.company?` · ${text(match.company)}`:""}</p>)}</div>}{step===2&&<div className="grid gap-3 border-t pt-4 sm:grid-cols-2"><Input name="company" placeholder="Company"/><Input name="title" placeholder="Job title"/><Input name="phone" placeholder="Phone"/><Input name="location" placeholder="Location"/><select name="stage" defaultValue="Lead" className="h-10 rounded-md border bg-white px-3 text-sm"><option>Lead</option><option>Prospect</option><option>Opportunity</option><option>Customer</option></select><Input name="leadSource" defaultValue="Direct" placeholder="Lead source"/><Textarea name="notes" rows={3} className="sm:col-span-2" placeholder="Relationship context"/></div>}{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex flex-wrap justify-end gap-2">{step===1&&<Button type="button" variant="outline" disabled={busy||Boolean(matches.some(item=>text(item.email).toLowerCase()===email.toLowerCase()))} onClick={event=>void save(event.currentTarget.closest("form")!)}>Save minimum</Button>}{step===1?<Button type="button" onClick={()=>setStep(2)}>Continue <ChevronDown size={16}/></Button>:<><Button type="button" variant="ghost" onClick={()=>setStep(1)}>Back</Button><Button disabled={busy||Boolean(matches.some(item=>text(item.email).toLowerCase()===email.toLowerCase()))}>{busy?<LoaderCircle className="animate-spin" size={16}/>:<Check size={16}/>}Create contact</Button></>}</div></form>;
}

export function ActivityComposer({defaultContactId="",defaultType="Call",onSaved}:{defaultContactId?:string;defaultType?:string;onSaved:()=>Promise<void>|void}){
 const[contactId,setContactId]=useState(defaultContactId),[dealId,setDealId]=useState(""),[note,setNote]=useState(""),[preset,setPreset]=useState(defaultType==="Call"?"":""),[proposals,setProposals]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const presets=["No response","Left voicemail","Meeting held, no change","Email sent, awaiting reply"];
 const selected=useMemo(()=>proposals.filter(item=>item.selected!==false),[proposals]);
 async function propose(nextPreset=preset){setBusy(true);setError("");try{const response=await fetch("/api/quick-capture",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"composeActivity",text:note,preset:nextPreset,contactId,dealId})}),body=await response.json() as{error?:string;proposals?:Row[]};if(!response.ok)throw new Error(body.error||"Suggestions could not be prepared.");setProposals(body.proposals||[])}catch(reason){setError(reason instanceof Error?reason.message:"Suggestions could not be prepared.")}finally{setBusy(false)}}
 async function commit(){setBusy(true);setError("");try{const response=await fetch("/api/quick-capture",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"commitProposals",proposals:selected})}),body=await response.json() as{error?:string;undoToken?:string};if(!response.ok)throw new Error(body.error||"Selected changes could not be saved.");notifyUndo(body.undoToken,`${selected.length} reviewed update${selected.length===1?"":"s"} saved`);await onSaved()}catch(reason){setError(reason instanceof Error?reason.message:"Selected changes could not be saved.")}finally{setBusy(false)}}
 return <div className="grid gap-4"><div className="flex flex-wrap gap-2">{presets.map(item=><Button key={item} type="button" size="sm" variant={preset===item?"default":"outline"} onClick={()=>{setPreset(item);setNote(item);void propose(item)}}>{item}</Button>)}</div><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Contact<RecordPicker kind="contact" value={contactId} onChange={setContactId} placeholder="No contact · search…"/></label><label className="grid gap-1 text-sm font-medium">Deal<RecordPicker kind="deal" value={dealId} onChange={setDealId} placeholder="No deal · search…"/></label></div><label className="grid gap-1 text-sm font-medium">What happened?<Textarea rows={5} value={note} onChange={event=>setNote(event.target.value)} placeholder="Met Jordan. Budget approved. Follow up with revised scope Friday. Risk: security review may delay close."/></label>{!proposals.length?<Button type="button" disabled={busy||(!note&&!preset)||(!contactId&&!dealId)} onClick={()=>void propose()}><Sparkles size={16}/>{busy?"Preparing…":"Review proposed updates"}</Button>:<div className="rounded-lg border"><div className="border-b bg-slate-50 px-4 py-3"><strong className="text-sm">Proposed CRM updates</strong><p className="mt-1 text-xs text-slate-500">Nothing is saved until you confirm the selected items.</p></div>{proposals.map((proposal,index)=><label key={text(proposal.id)||index} className="flex items-start gap-3 border-b p-4 last:border-0"><input className="mt-1" type="checkbox" checked={proposal.selected!==false} onChange={event=>setProposals(items=>items.map((item,itemIndex)=>itemIndex===index?{...item,selected:event.target.checked}:item))}/><span className="min-w-0"><strong className="text-sm">{text(proposal.label)}</strong><span className="mt-1 block truncate text-xs text-slate-500">Evidence: {text(proposal.evidence)}</span></span></label>)}</div>}{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{proposals.length>0&&<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setProposals([])}>Revise note</Button><Button type="button" disabled={busy||!selected.length} onClick={()=>void commit()}><Check size={16}/>Apply {selected.length} selected</Button></div>}</div>;
}
