"use client";

import { useEffect, useMemo, useState } from "react";
import { Building2, CalendarPlus, CheckSquare, ChevronDown, ChevronLeft, ChevronRight, CircleUserRound, Combine, Mail, MapPin, Pencil, Phone, ShieldBan, Trash2, Users, X } from "lucide-react";
import { AIRecordFieldsPanel } from "@/components/ai-record-fields";
import { CustomFieldInput, customFieldValue, type CustomFieldDefinition, type CustomFieldValue } from "@/components/custom-fields";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { RecordPicker } from "@/components/record-picker";
import type { Activity, CampaignEvent, Contact, ContactRef } from "@/lib/crm-types";

/** GET /api/crm?resource=contact&id= — the open record with only its own timeline, custom values and likely duplicates. */
type ContactDetail={contact:Contact;activities:Activity[];campaignEvents:CampaignEvent[];customFieldValues:CustomFieldValue[];duplicates:ContactRef[]};


const date=(value:string|null)=>value?new Date(value.length===10?`${value}T12:00:00`:value).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):"—";
const initials=(contact:Contact)=>`${contact.firstName[0]||""}${contact.lastName[0]||""}`;

function Stage({value}:{value:string}){return <span className={`crm-stage crm-stage-${value.toLowerCase()}`}>{value}</span>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="crm-record-section"><h3><ChevronDown size={16}/>{title}</h3><div className="crm-record-section-body">{children}</div></section>}
function FieldRow({label,value,icon}:{label:string;value:React.ReactNode;icon?:React.ReactNode}){return <div className="crm-field-row"><div className="crm-field-label">{icon}{label}</div><div className="crm-field-value">{value||"—"}</div></div>}

export function ContactWorkspace({contacts,total,offset,pageSize,loading,page,refreshKey,bulk,owner,selectedId,select,customFields,merge,update,remove,task,suppress}:{contacts:Contact[];total:number;offset:number;pageSize:number;loading:boolean;page:(offset:number)=>void;refreshKey:number;bulk:(contacts:Contact[])=>void;owner:string;selectedId:number|null;select:(id:number|null)=>void;customFields:CustomFieldDefinition[];merge:(keepId:number,mergeId:number)=>Promise<void>;update:(form:FormData)=>Promise<void>;remove:(id:number)=>Promise<void>;task:(form:FormData)=>Promise<void>;suppress:(email:string,reason:string)=>void}){
 const [checked,setChecked]=useState<Contact[]>([]),[mergeId,setMergeId]=useState(0),[detail,setDetail]=useState<ContactDetail|null>(null),[edit,setEdit]=useState(false),[view,setView]=useState("All contacts"),[density,setDensity]=useState<"comfortable"|"compact">("comfortable");
 useEffect(()=>{if(!selectedId)return;let alive=true;fetch(`/api/crm?resource=contact&id=${selectedId}`,{cache:"no-store"}).then(response=>response.ok?response.json() as Promise<ContactDetail>:null).then(body=>{if(alive)setDetail(body)}).catch(()=>{if(alive)setDetail(null)});return()=>{alive=false}},[selectedId,refreshKey]);
 const selected=selectedId&&detail?.contact.id===selectedId?detail.contact:null,isChecked=(id:number)=>checked.some(item=>item.id===id);
 const allChecked=contacts.length>0&&contacts.every(contact=>isChecked(contact.id));
 const timeline=useMemo(()=>detail?[...detail.activities.map(item=>({date:item.happenedAt,label:item.type,detail:item.note})),...detail.campaignEvents.map(item=>({date:item.occurredAt,label:item.type.replace("email.","Email "),detail:item.campaignName}))].sort((a,b)=>b.date.localeCompare(a.date)):[],[detail]);
 const suggested=selected&&detail?detail.duplicates:[];
 const toggle=(contact:Contact)=>setChecked(current=>current.some(item=>item.id===contact.id)?current.filter(item=>item.id!==contact.id):[...current,contact]);
 return <>
  <section className="crm-table-shell">
   <div className="crm-object-bar"><div className="flex min-w-0 items-center gap-3"><span className="crm-object-icon"><CircleUserRound size={20}/></span><div><div className="text-xs text-slate-500">Contacts</div><h1>{view}</h1></div><ChevronDown size={16} className="text-slate-400"/></div><div className="flex items-center gap-2 text-xs text-slate-500">{loading?"Loading…":`${total.toLocaleString()} records`}{checked.length?` · ${checked.length} selected`:""}{checked.length>0&&<><Button size="sm" variant="outline" onClick={()=>bulk(checked)}><Users size={14}/>Bulk update</Button><Button size="sm" variant="ghost" onClick={()=>setChecked([])}>Clear</Button></>}</div></div>
   <div className="crm-list-toolbar"><div className="flex min-w-0 flex-1 gap-1 overflow-x-auto">{["All contacts","Needs follow-up","Quiet 30+ days","Customers"].map(item=><button key={item} className={`view-chip ${view===item?"view-chip-active":""}`} onClick={()=>{setView(item);window.dispatchEvent(new CustomEvent("crm:contact-view",{detail:item}))}}>{item}</button>)}</div><div className="flex shrink-0 items-center gap-1 border-l pl-2"><button className={`view-chip ${density==="comfortable"?"view-chip-active":""}`} onClick={()=>{setDensity("comfortable");window.dispatchEvent(new CustomEvent("crm:contact-density",{detail:"comfortable"}))}}>Roomy</button><button className={`view-chip ${density==="compact"?"view-chip-active":""}`} onClick={()=>{setDensity("compact");window.dispatchEvent(new CustomEvent("crm:contact-density",{detail:"compact"}))}}>Compact</button></div></div>
   <div className="overflow-auto"><table className="crm-record-table"><thead><tr><th className="w-10"><input aria-label="Select all contacts" type="checkbox" checked={allChecked} onChange={()=>setChecked(current=>allChecked?current.filter(item=>!contacts.some(contact=>contact.id===item.id)):[...current,...contacts.filter(contact=>!current.some(item=>item.id===contact.id))])}/></th><th className="w-10">#</th><th>Name</th><th>Company</th><th>Title</th><th>Phone</th><th>Email</th><th>Stage</th><th>Last contact</th><th className="w-10"/></tr></thead><tbody>{contacts.map((contact,index)=><tr key={contact.id}><td><input aria-label={`Select ${contact.firstName} ${contact.lastName}`} type="checkbox" checked={isChecked(contact.id)} onChange={()=>toggle(contact)}/></td><td className="text-slate-400">{offset+index+1}</td><td><button className="crm-record-link" onClick={()=>select(contact.id)}>{contact.firstName} {contact.lastName}</button></td><td>{contact.company||"—"}</td><td>{contact.title||"—"}</td><td>{contact.phone||"—"}</td><td><a className="crm-record-link" href={`mailto:${contact.email}`}>{contact.email}</a></td><td><Stage value={contact.stage}/></td><td>{date(contact.lastContact)}</td><td><button className="icon-control" title="Open record" onClick={()=>select(contact.id)}><ChevronRight size={16}/></button></td></tr>)}</tbody></table>{!contacts.length&&!loading&&<div className="grid min-h-56 place-items-center text-sm text-slate-500">No contacts match this view.</div>}</div>
   {total>0&&<nav aria-label="Contact pages" className="flex items-center justify-between gap-3 border-t px-4 py-2 text-xs text-slate-500"><span>{offset+1}–{Math.min(offset+contacts.length,total)} of {total.toLocaleString()}</span><div className="flex gap-1"><Button size="sm" variant="outline" disabled={loading||offset===0} onClick={()=>page(offset-pageSize)}><ChevronLeft size={15}/>Previous</Button><Button size="sm" variant="outline" disabled={loading||offset+pageSize>=total} onClick={()=>page(offset+pageSize)}>Next<ChevronRight size={15}/></Button></div></nav>}
  </section>
  {selectedId&&!selected&&<div role="status" className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-lg bg-slate-950 px-4 py-2 text-sm text-white shadow-xl">Opening contact…</div>}
  {selected&&<div className="fixed inset-0 z-50 bg-slate-950/25" onMouseDown={event=>{if(event.currentTarget===event.target)select(null)}}><aside className="crm-record-drawer">
   <header className="crm-record-header"><div className="crm-record-avatar">{initials(selected)}</div><div className="min-w-0 flex-1"><div className="text-xs font-medium text-slate-500">Contact</div><h2>{selected.firstName} {selected.lastName}</h2><p>{selected.title||"Contact"}{selected.company?` at ${selected.company}`:""}</p></div><div className="crm-record-actions"><Button size="sm" variant="outline" asChild><a href={`mailto:${selected.email}`}><Mail size={15}/>Email</a></Button><Button size="sm" variant="outline" onClick={()=>setEdit(value=>!value)}><Pencil size={15}/>Edit</Button><Button size="icon" variant="ghost" title="Close record" onClick={()=>select(null)}><X size={19}/></Button></div></header>
   <div className="crm-record-summary"><FieldRow label="Company" value={selected.company}/><FieldRow label="Title" value={selected.title}/><FieldRow label="Phone" value={selected.phone}/><FieldRow label="Email" value={selected.email}/><FieldRow label="Status" value={<Stage value={selected.stage}/>}/></div>
   <div className="crm-record-grid"><main className="crm-record-main">
    {edit&&<Section title="Edit contact"><form action={async form=>{await update(form);setEdit(false)}} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="id" value={selected.id}/><label>First name<Input name="firstName" defaultValue={selected.firstName} required/></label><label>Last name<Input name="lastName" defaultValue={selected.lastName} required/></label><label>Email<Input name="email" type="email" defaultValue={selected.email} required/></label><label>Phone<Input name="phone" defaultValue={selected.phone}/></label><label>Company<Input name="company" defaultValue={selected.company}/></label><label>Role<Input name="title" defaultValue={selected.title}/></label><label>Location<Input name="location" defaultValue={selected.location}/></label><label>Tags<Input name="tags" defaultValue={selected.tags.join(", ")}/></label><label>Stage<select name="stage" defaultValue={selected.stage}><option>Lead</option><option>Prospect</option><option>Opportunity</option><option>Customer</option></select></label>{customFields.map(field=><CustomFieldInput key={field.id} field={field} value={customFieldValue(detail?.customFieldValues||[],"contact",selected.id,field.id)}/>)}<label className="sm:col-span-2">Notes<Textarea name="notes" rows={3} defaultValue={selected.notes}/></label><div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="ghost" onClick={()=>setEdit(false)}>Cancel</Button><Button>Save contact</Button></div></form></Section>}
    <Section title="About"><FieldRow label="Name" value={`${selected.firstName} ${selected.lastName}`}/><FieldRow label="Company" icon={<Building2 size={14}/>} value={selected.company}/><FieldRow label="Title" value={selected.title}/><FieldRow label="Lifecycle stage" value={<Stage value={selected.stage}/>}/><FieldRow label="Email permission" value={selected.subscribed?"Subscribed":selected.suppressionReason||"Unsubscribed"}/><FieldRow label="Tags" value={selected.tags.length?<div className="flex flex-wrap gap-1">{selected.tags.map(tag=><Badge key={tag} variant="outline">{tag}</Badge>)}</div>:"—"}/></Section>
    <Section title="Get in touch"><FieldRow label="Phone" icon={<Phone size={14}/>} value={selected.phone}/><FieldRow label="Email" icon={<Mail size={14}/>} value={<a className="crm-record-link" href={`mailto:${selected.email}`}>{selected.email}</a>}/><FieldRow label="Location" icon={<MapPin size={14}/>} value={selected.location}/><FieldRow label="Next follow-up" icon={<CalendarPlus size={14}/>} value={date(selected.nextFollowUp)}/></Section>
    <Section title="Notes"><p className="whitespace-pre-wrap text-sm leading-6 text-slate-600">{selected.notes||"No contact notes yet."}</p></Section>
   </main><section className="crm-activity-column"><div className="crm-activity-toolbar"><form action={task} className="grid gap-2"><input type="hidden" name="contactId" value={selected.id}/><div className="flex items-center gap-2 font-semibold"><CheckSquare size={17} className="text-emerald-600"/>New task</div><div className="grid grid-cols-[1fr_145px_auto] gap-2"><Input name="title" aria-label="Task title" placeholder="Create a follow-up…" required/><Input name="dueDate" aria-label="Due date" type="date" required/><input type="hidden" name="owner" value={owner}/><Button size="sm">Add</Button></div></form></div><div className="crm-activity-heading"><strong>Activity</strong><span>All time · All types</span></div><div className="crm-timeline"><div className="crm-timeline-group">Upcoming &amp; recent</div>{timeline.length?timeline.slice(0,30).map((item,index)=><article key={`${item.date}-${index}`}><span className="crm-timeline-dot"/><div><div className="flex justify-between gap-3"><strong>{item.label}</strong><time>{date(item.date)}</time></div><p>{item.detail}</p></div></article>):<div className="p-8 text-center text-sm text-slate-500">No activity yet. Add a task or record an interaction.</div>}</div></section><aside className="crm-related-column">
    <Section title="Relationship"><FieldRow label="Owner" value={owner}/><FieldRow label="Last contact" value={date(selected.lastContact)}/><FieldRow label="Next action" value={date(selected.nextFollowUp)}/></Section>
    <Section title="AI evidence"><AIRecordFieldsPanel entityType="contact" entityId={selected.id} compact/></Section>
    <Section title="Data quality">{suggested.length?<div className="mb-3 border-l-2 border-amber-400 bg-amber-50 p-3 text-xs text-amber-900">Possible duplicate: {suggested.map(contact=>`${contact.firstName} ${contact.lastName}${contact.email?` (${contact.email})`:""}`).join(", ")}</div>:<p className="mb-3 text-sm text-slate-500">No potential duplicates found.</p>}<div className="flex gap-2">{suggested.length>0&&!mergeId&&<Button size="sm" variant="outline" onClick={()=>setMergeId(suggested[0].id)}>Use suggestion</Button>}<RecordPicker kind="contact" ariaLabel="Merge contact" placeholder="Merge contact…" value={mergeId?String(mergeId):""} onChange={id=>setMergeId(Number(id)===selected.id?0:Number(id)||0)}/><Button size="icon" variant="outline" title="Merge contact" disabled={!mergeId} onClick={()=>{if(mergeId&&window.confirm("Merge this contact into the open record?"))void merge(selected.id,mergeId)}}><Combine size={15}/></Button></div></Section>
    <Section title="Record controls">{selected.subscribed&&<Button size="sm" variant="outline" className="w-full" onClick={()=>{if(window.confirm(`Suppress ${selected.email} from future campaigns?`))suppress(selected.email,"Manual unsubscribe")}}><ShieldBan size={15}/>Suppress email</Button>}<Button size="sm" variant="ghost" className="mt-2 w-full text-red-700" onClick={()=>{if(window.confirm(`Delete ${selected.firstName} ${selected.lastName}? This cannot be undone.`))void remove(selected.id)}}><Trash2 size={15}/>Delete contact</Button></Section>
   </aside></div>
  </aside></div>}
 </>;
}
