"use client";

// Customer portal links: issue a one-time crp_ link for a company contact, list issued links, and revoke active ones.
// Backed by /api/platform-expansion (GET portalAccess never includes token material; POST createPortalAccess returns the token once).
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Check, Copy, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Panel } from "@/components/workspace-primitives";
import { RecordPicker } from "@/components/record-picker";
import type { Row } from "@/lib/crm-types";
import { text } from "@/lib/format";

const PERMISSIONS=["cases","documents","onboarding","knowledge"];
// UTC dates so the chosen day's midnight stays inside the server's 365-day limit in every time zone.
const isoDay=(days:number)=>new Date(Date.now()+days*86400000).toISOString().slice(0,10);
const dateTime=(value:unknown,empty="Not set")=>{if(!value)return empty;const date=new Date(text(value));return Number.isNaN(date.valueOf())?text(value):date.toLocaleString()};
const permissionsOf=(value:unknown)=>{try{const result=JSON.parse(text(value)||"[]");return Array.isArray(result)?result.map(text).join(", "):""}catch{return ""}};
const statusOf=(item:Row)=>text(item.status)==="Active"&&item.expires_at&&new Date(text(item.expires_at))<new Date()?"Expired":text(item.status);

export function CustomerPortalLinks({canEdit}:{canEdit:boolean}){
 const[links,setLinks]=useState<Row[]|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[companyId,setCompanyId]=useState(""),[contactId,setContactId]=useState(""),[portalLink,setPortalLink]=useState(""),[copied,setCopied]=useState(false),[formKey,setFormKey]=useState(0);
 const load=useCallback(async()=>{const response=await fetch("/api/platform-expansion",{cache:"no-store"}),body=await response.json().catch(()=>({})) as {portalAccess?:Row[];error?:string};if(!response.ok)throw new Error(body.error||"Portal links could not load.");setLinks(body.portalAccess||[])},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load().catch(reason=>setError(reason instanceof Error?reason.message:"Portal links could not load."))},0);return()=>window.clearTimeout(timer)},[load]);
 async function run(action:string,payload:Row,message:string){setBusy(true);setError("");try{const response=await fetch("/api/platform-expansion",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload})}),body=await response.json().catch(()=>({})) as Row&{error?:string};if(!response.ok)throw new Error(body.error||"The change could not be saved.");if(action==="createPortalAccess"){setPortalLink(`${window.location.origin}${text(body.url)}`);setCopied(false)}await load();setNotice(message);window.setTimeout(()=>setNotice(""),3200);return true}catch(reason){setError(reason instanceof Error?reason.message:"The change could not be saved.");return false}finally{setBusy(false)}}
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),permissions=form.getAll("permissions").map(String);if(!permissions.length){setError("Choose at least one portal permission.");return}if(await run("createPortalAccess",{companyId,contactId,expiresAt:text(form.get("expiresAt")),permissions:permissions.join(",")},"Portal link created")){setCompanyId("");setContactId("");setFormKey(key=>key+1)}}
 async function copy(){try{await navigator.clipboard.writeText(portalLink);setCopied(true)}catch{setError("Copy failed. Select the link and copy it manually.")}}
 return <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
  <div className="grid content-start gap-4 xl:col-span-2">{error&&<div role="alert" className="rounded-lg bg-red-50 p-4 text-sm text-red-700">{error}</div>}{notice&&<div className="flex items-center gap-2 rounded-lg bg-emerald-50 p-4 text-sm text-emerald-800"><Check size={16}/>{notice}</div>}{portalLink&&<div className="rounded-lg border border-blue-200 bg-blue-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm text-blue-900">New portal link</strong><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>void copy()}>{copied?<Check size={14}/>:<Copy size={14}/>}{copied?"Copied":"Copy link"}</Button><Button size="sm" variant="ghost" onClick={()=>setPortalLink("")}>Done</Button></div></div><p className="mt-2 break-all rounded border border-blue-100 bg-white p-2 font-mono text-xs text-blue-900">{portalLink}</p><p className="mt-2 text-xs text-blue-700">This link is shown once and cannot be retrieved later. Copy it now and share it through a trusted channel.</p></div>}</div>
  <Panel className="overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Customer portal links</h2><p className="mt-1 text-sm text-slate-500">Secure, expiring links that let a customer contact see their cases, documents, onboarding, and knowledge.</p></div>{links===null?<p className="p-5 text-sm text-slate-500">{error?"Portal links are unavailable.":"Loading portal links…"}</p>:links.map(item=>{const status=statusOf(item);return <div key={text(item.id)} className="grid gap-3 border-b p-5 last:border-0 md:grid-cols-[1fr_auto]"><div><strong>{text(item.contact_name)}</strong><p className="mt-1 text-sm text-slate-500">{text(item.company_name)} · {text(item.email)}</p><p className="mt-1 text-xs text-slate-400">Permissions: {permissionsOf(item.permissions_json)||"None"} · Created {dateTime(item.created_at)} · Expires {item.expires_at?dateTime(item.expires_at):"No expiry"} · Last used {dateTime(item.last_used_at,"Never")}</p></div><div className="flex items-center gap-2"><Badge variant={status==="Active"?"default":"secondary"}>{status}</Badge>{canEdit&&text(item.status)==="Active"&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>{if(window.confirm(`Revoke portal access for ${text(item.contact_name)}? The link stops working immediately.`))void run("revokePortalAccess",{id:text(item.id)},"Portal link revoked")}}>Revoke</Button>}</div></div>})}{links?.length===0&&<p className="p-10 text-center text-sm text-slate-500">No portal links issued yet.</p>}</Panel>
  {canEdit&&<Panel className="p-5"><h2 className="font-semibold">Issue portal link</h2><form key={formKey} onSubmit={create} className="mt-4 grid gap-3"><label className="grid gap-1.5 text-sm font-medium">Company<RecordPicker kind="company" value={companyId} onChange={id=>{setCompanyId(id);setContactId("")}} required placeholder="Choose · search…"/></label><label className="grid gap-1.5 text-sm font-medium">Contact<RecordPicker key={companyId} kind="contact" value={contactId} onChange={id=>setContactId(id)} companyId={companyId} disabled={!companyId} required placeholder={companyId?"Contacts at this company · search…":"Choose a company first"}/></label><fieldset className="grid gap-1.5 text-sm"><legend className="mb-1.5 font-medium">Permissions</legend><div className="grid grid-cols-2 gap-2">{PERMISSIONS.map(item=><label key={item} className="flex items-center gap-2 capitalize"><input type="checkbox" name="permissions" value={item} defaultChecked/>{item}</label>)}</div></fieldset><label className="grid gap-1.5 text-sm font-medium">Expires<Input name="expiresAt" type="date" defaultValue={isoDay(90)} min={isoDay(1)} max={isoDay(365)} required/><span className="text-xs font-normal text-slate-500">Default 90 days, at most 365.</span></label><Button disabled={busy||!companyId||!contactId}><ShieldCheck size={16}/>Create secure link</Button></form></Panel>}
 </div>;
}
