"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, Clipboard, ListChecks, Pencil, RotateCcw, Sparkles, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { Row } from "@/lib/crm-types";

type Draft={emailSubject:string;personalizedMessage:string;discussionSummary:string;decisions:string[];commitments:Array<{text:string;owner:string;dueDate:string;party:string}>;nextSteps:Array<{text:string;owner:string;dueDate:string}>;confidence:string;explanation:string;dataGaps:string[]};
type Artifact={id:string;sourceType:"meeting"|"note"|"transcript";sourceId:string;reviewStatus:string;content:Draft;provider:string;model:string;promptVersion:number;rulesVersion:string;generatedAt:string;generatedBy:string;reviewedAt:string|null;reviewedBy:string|null;sourceCount:number};
type State={drafts:Artifact[];providerConfigured:boolean;settings:{enabled:boolean};permissions:{generate:boolean;review:boolean;createTasks:boolean}};
type Props={dealId:number;meetings:Row[];notes:Row[];documents:Row[];onTasksCreated:()=>Promise<void>};
const selectClass="h-10 w-full rounded-md border bg-white px-3 text-sm";
const when=(value:unknown)=>value?new Date(String(value)).toLocaleString():"";
const clone=(draft:Draft)=>JSON.parse(JSON.stringify(draft)) as Draft;
const sourceKey=(type:string,id:unknown)=>`${type}:${String(id)}`;
const listText=(items:string[])=>items.join("\n");
const fromLines=(value:string)=>value.split(/\r?\n/).map(item=>item.replace(/^[-*]\s*/,"").trim()).filter(Boolean);

export function FollowUpDraftPanel({dealId,meetings,notes,documents,onTasksCreated}:Props){
  const [data,setData]=useState<State|null>(null),[selected,setSelected]=useState(""),[activeId,setActiveId]=useState(""),[editing,setEditing]=useState<Draft|null>(null),[selectedSteps,setSelectedSteps]=useState<number[]>([]),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const transcriptDocuments=useMemo(()=>documents.filter(document=>String(document.content_type||"").startsWith("text/")||meetings.some(meeting=>String(meeting.transcript_document_id||"")===String(document.id))),[documents,meetings]);
  const sources=useMemo(()=>[
    ...meetings.map(item=>({key:sourceKey("meeting",item.id),type:"meeting" as const,id:String(item.id),label:`Meeting · ${String(item.subject)} · ${when(item.starts_at)}`})),
    ...notes.map(item=>({key:sourceKey("note",item.id),type:"note" as const,id:String(item.id),label:`${String(item.kind)} · ${when(item.created_at)} · ${String(item.body).slice(0,70)}`})),
    ...transcriptDocuments.map(item=>({key:sourceKey("transcript",item.id),type:"transcript" as const,id:String(item.id),label:`Transcript · ${String(item.title)} · ${String(item.filename||"")}`})),
  ],[meetings,notes,transcriptDocuments]);
  const load=useCallback(async()=>{const response=await fetch(`/api/follow-up-drafts?dealId=${dealId}`,{cache:"no-store"}),body=await response.json() as State&{error?:string};if(!response.ok)throw new Error(body.error);setData(body);setActiveId(current=>current&&body.drafts.some(item=>item.id===current)?current:String(body.drafts[0]?.id||""));setSelected(current=>current||sources[0]?.key||"")},[dealId,sources]);
  useEffect(()=>{let cancelled=false;const hydrate=async()=>{try{const response=await fetch(`/api/follow-up-drafts?dealId=${dealId}`,{cache:"no-store"}),body=await response.json() as State&{error?:string};if(!response.ok)throw new Error(body.error);if(cancelled)return;setData(body);setActiveId(String(body.drafts[0]?.id||""));setSelected(current=>current||sources[0]?.key||"")}catch(reason){if(!cancelled)setError(reason instanceof Error?reason.message:"Follow-up drafts could not load.")}};void hydrate();return()=>{cancelled=true}},[dealId,sources]);
  const active=data?.drafts.find(item=>item.id===activeId)||data?.drafts[0]||null;
  const request=async(payload:Row,message:string)=>{setBusy(String(payload.action));setError("");try{const response=await fetch("/api/follow-up-drafts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({dealId,...payload})}),body=await response.json() as {error?:string;artifact?:Artifact;created?:string[];skipped?:string[]};if(!response.ok)throw new Error(body.error);await load();if(body.artifact)setActiveId(body.artifact.id);setNotice(message);window.setTimeout(()=>setNotice(""),2600);return body}catch(reason){setError(reason instanceof Error?reason.message:"The follow-up action failed.");return null}finally{setBusy("")}};
  const generate=async(force=false)=>{const [type,...parts]=selected.split(":");if(!type||!parts.length){setError("Choose a meeting, note, or transcript.");return}setEditing(null);setSelectedSteps([]);await request({action:"generate",sourceType:type,sourceId:parts.join(":"),force},force?"A new draft was generated":"Follow-up draft prepared")};
  const review=async(status:"Accepted"|"Rejected"|"Edited",content?:Draft)=>{if(!active)return;const result=await request({action:"review",artifactId:active.id,status,content},status==="Edited"?"Edits saved":status==="Accepted"?"Draft accepted":"Draft rejected");if(result)setEditing(null)};
  const copy=async()=>{if(!active)return;const draft=editing||active.content,text=`${draft.emailSubject}\n\n${draft.personalizedMessage}`;await navigator.clipboard.writeText(text);setNotice("Subject and message copied");window.setTimeout(()=>setNotice(""),2400)};
  const createTasks=async()=>{if(!active||!selectedSteps.length)return;if(!window.confirm(`Create ${selectedSteps.length} selected deal task${selectedSteps.length===1?"":"s"}?`))return;const result=await request({action:"createTasks",artifactId:active.id,selected:selectedSteps},"Selected deal tasks created");if(result){setSelectedSteps([]);await onTasksCreated()}};
  return <div className="grid gap-5">
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800"><Check size={15}/>{notice}</p>}
    <section className="rounded-2xl border bg-slate-50 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Sparkles size={19} className="text-blue-600"/><h3 className="text-lg font-semibold">AI follow-up draft</h3></div><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Choose a meeting, note, or transcript. ClientRecord creates a governed draft for review; nothing is sent automatically.</p></div><Badge variant={data?.settings.enabled&&data.providerConfigured?"default":"secondary"}>{data?.settings.enabled&&data.providerConfigured?"Model-backed":"Rules-based mode"}</Badge></div>
      <div className="mt-5 grid gap-3 md:grid-cols-[1fr_auto]"><select aria-label="Follow-up source" className={selectClass} value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Choose a source</option>{sources.map(source=><option key={source.key} value={source.key}>{source.label}</option>)}</select><Button disabled={!selected||!data?.permissions.generate||Boolean(busy)} onClick={()=>void generate(false)}><Sparkles size={15}/>{busy==="generate"?"Generating…":"Generate draft"}</Button></div>
      {!sources.length&&<p className="mt-3 text-sm text-amber-700">Add a meeting, note, or text transcript to this deal before generating a follow-up.</p>}
    </section>

    {active&&<section className="rounded-2xl border border-blue-200 bg-blue-50/30 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold">Follow-up draft</h3><Badge variant={active.reviewStatus==="Rejected"?"destructive":"secondary"}>{active.reviewStatus}</Badge><Badge variant="outline">{active.content.confidence} confidence</Badge></div><p className="mt-2 text-xs text-slate-500">Generated {when(active.generatedAt)} · {active.sourceCount} source groups · {active.model} · prompt v{active.promptVersion}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setEditing(editing?null:clone(active.content))}><Pencil size={14}/>{editing?"Cancel edit":"Edit"}</Button><Button size="sm" variant="outline" onClick={()=>void generate(true)} disabled={Boolean(busy)}><RotateCcw size={14}/>Regenerate</Button><Button size="sm" variant="outline" onClick={()=>void copy()}><Clipboard size={14}/>Copy</Button></div></div>
      {editing?<DraftEditor draft={editing} change={setEditing}/>:<DraftView draft={active.content} selected={selectedSteps} select={setSelectedSteps}/>} 
      <div className="mt-5 rounded-xl border bg-white p-4 text-sm text-slate-600"><strong className="text-slate-900">Why this was generated</strong><p className="mt-1 leading-6">{active.content.explanation}</p>{active.content.dataGaps.length>0&&<p className="mt-2 text-amber-700">Data gaps: {active.content.dataGaps.join(" ")}</p>}</div>
      <div className="mt-4 flex flex-wrap gap-2">{editing?<Button size="sm" onClick={()=>void review("Edited",editing)} disabled={!data?.permissions.review||Boolean(busy)}><Check size={14}/>Save edits</Button>:<>{active.reviewStatus==="Draft"&&<Button size="sm" onClick={()=>void review("Accepted")} disabled={!data?.permissions.review||Boolean(busy)}><Check size={14}/>Accept</Button>}{active.reviewStatus!=="Rejected"&&<Button size="sm" variant="outline" onClick={()=>void review("Rejected")} disabled={!data?.permissions.review||Boolean(busy)}><X size={14}/>Reject</Button>}<Button size="sm" variant="outline" onClick={()=>void createTasks()} disabled={!data?.permissions.createTasks||!selectedSteps.length||!["Accepted","Edited"].includes(active.reviewStatus)||Boolean(busy)}><ListChecks size={14}/>Create selected tasks</Button></>}</div>
      {!editing&&active.content.nextSteps.length>0&&!['Accepted','Edited'].includes(active.reviewStatus)&&<p className="mt-3 text-xs text-slate-500">Accept the draft or save edits before creating tasks.</p>}
    </section>}
    {data&&data.drafts.length>1&&<section className="rounded-xl border p-4"><h3 className="text-sm font-semibold">Current drafts by source</h3><div className="mt-3 grid gap-2">{data.drafts.map(item=><button key={item.id} onClick={()=>{setActiveId(item.id);setEditing(null);setSelectedSteps([])}} className={`rounded-lg border p-3 text-left text-sm ${item.id===active?.id?"border-blue-300 bg-blue-50":"bg-white"}`}><strong>{sources.find(source=>source.type===item.sourceType&&source.id===item.sourceId)?.label||`${item.sourceType} ${item.sourceId}`}</strong><span className="mt-1 block text-xs text-slate-500">{item.reviewStatus} · {when(item.generatedAt)}</span></button>)}</div></section>}
  </div>;
}

function DraftView({draft,selected,select}:{draft:Draft;selected:number[];select:(value:number[])=>void}){return <div className="mt-5 grid gap-4 lg:grid-cols-2"><Block title="Email subject"><p className="text-sm font-medium">{draft.emailSubject}</p></Block><Block title="Discussion summary"><p className="whitespace-pre-wrap text-sm leading-6 text-slate-700">{draft.discussionSummary}</p></Block><Block title="Personalized message" className="lg:col-span-2"><pre className="whitespace-pre-wrap font-sans text-sm leading-6 text-slate-700">{draft.personalizedMessage}</pre></Block><ListBlock title="Decisions" items={draft.decisions}/><Block title="Commitments">{draft.commitments.map((item,index)=><div key={index} className="border-b py-2 text-sm last:border-0"><strong>{item.text}</strong><p className="mt-1 text-xs text-slate-500">{item.party} · {item.owner||"Owner not recorded"}{item.dueDate?` · due ${item.dueDate}`:""}</p></div>)}{!draft.commitments.length&&<p className="text-sm text-slate-500">No commitments recorded.</p>}</Block><Block title="Next steps" className="lg:col-span-2">{draft.nextSteps.map((item,index)=><label key={index} className="flex items-start gap-3 border-b py-3 last:border-0"><input type="checkbox" checked={selected.includes(index)} onChange={event=>select(event.target.checked?[...selected,index]:selected.filter(value=>value!==index))}/><span className="text-sm"><strong className="block">{item.text}</strong><span className="mt-1 block text-xs text-slate-500">{item.owner||"Deal owner"}{item.dueDate?` · due ${item.dueDate}`:" · due date will default to two days from now"}</span></span></label>)}{!draft.nextSteps.length&&<p className="text-sm text-slate-500">No next steps recorded.</p>}</Block></div>}

function DraftEditor({draft,change}:{draft:Draft;change:(value:Draft)=>void}){const set=(patch:Partial<Draft>)=>change({...draft,...patch});return <div className="mt-5 grid gap-4 lg:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Email subject<Input value={draft.emailSubject} onChange={event=>set({emailSubject:event.target.value})}/></label><label className="grid gap-1 text-sm font-medium">Discussion summary<Textarea rows={4} value={draft.discussionSummary} onChange={event=>set({discussionSummary:event.target.value})}/></label><label className="grid gap-1 text-sm font-medium lg:col-span-2">Personalized message<Textarea rows={10} value={draft.personalizedMessage} onChange={event=>set({personalizedMessage:event.target.value})}/></label><label className="grid gap-1 text-sm font-medium">Decisions <span className="font-normal text-slate-500">one per line</span><Textarea rows={5} value={listText(draft.decisions)} onChange={event=>set({decisions:fromLines(event.target.value)})}/></label><label className="grid gap-1 text-sm font-medium">Commitments <span className="font-normal text-slate-500">one per line</span><Textarea rows={5} value={draft.commitments.map(item=>item.text).join("\n")} onChange={event=>set({commitments:fromLines(event.target.value).map((text,index)=>({...draft.commitments[index],text,owner:draft.commitments[index]?.owner||"",dueDate:draft.commitments[index]?.dueDate||"",party:draft.commitments[index]?.party||"Shared"}))})}/></label><Block title="Next steps" className="lg:col-span-2">{draft.nextSteps.map((item,index)=><div key={index} className="mb-3 grid gap-2 rounded-lg bg-slate-50 p-3 md:grid-cols-[1fr_220px_150px_auto]"><Input aria-label={`Next step ${index+1}`} value={item.text} onChange={event=>change({...draft,nextSteps:draft.nextSteps.map((step,i)=>i===index?{...step,text:event.target.value}:step)})}/><Input aria-label={`Owner ${index+1}`} value={item.owner} onChange={event=>change({...draft,nextSteps:draft.nextSteps.map((step,i)=>i===index?{...step,owner:event.target.value}:step)})}/><Input aria-label={`Due date ${index+1}`} type="date" value={item.dueDate} onChange={event=>change({...draft,nextSteps:draft.nextSteps.map((step,i)=>i===index?{...step,dueDate:event.target.value}:step)})}/><Button type="button" size="sm" variant="outline" onClick={()=>change({...draft,nextSteps:draft.nextSteps.filter((_,i)=>i!==index)})}>Remove</Button></div>)}<Button type="button" size="sm" variant="outline" onClick={()=>change({...draft,nextSteps:[...draft.nextSteps,{text:"",owner:"",dueDate:""}]})}>Add next step</Button></Block></div>}

function Block({title,children,className=""}:{title:string;children:React.ReactNode;className?:string}){return <div className={`rounded-xl border bg-white p-4 ${className}`}><h4 className="mb-3 text-sm font-semibold">{title}</h4>{children}</div>}
function ListBlock({title,items}:{title:string;items:string[]}){return <Block title={title}>{items.length?<ul className="list-disc space-y-1.5 pl-5 text-sm leading-6 text-slate-700">{items.map((item,index)=><li key={`${index}-${item}`}>{item}</li>)}</ul>:<p className="text-sm text-slate-500">None recorded.</p>}</Block>}
