"use client";

import { useMemo, useState, type FormEvent } from "react";
import { CalendarDays, Check, FileText, Sparkles, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type Row=Record<string,unknown>;
type Contact={id:number;name:string;email:string;company:string;title:string};
type BriefContent={companyAndAttendeeSummary:string;currentDealPosition:string;lastMeaningfulInteraction:string;unresolvedCommitments:string[];risksAndObjections:string[];stakeholderConcerns:string[];suggestedAgenda:string[];recommendedQuestions:string[];confidence:string;dataGaps:string[];sourcesUsed:string[];freshnessTime:string};
type Artifact={id:string;meetingKey:string;reviewStatus:string;content:BriefContent;explanation:string;confidence:number;model:string;rulesVersion:string;generatedAt:string;generatedBy:string;reviewedAt:string|null;reviewedBy:string|null;sourceCount:number};
type Props={meetings:Row[];briefs:Record<string,Artifact|null>;contacts:Contact[];documents:Row[];dealOwner:string;canEdit:boolean;canReview:boolean;busy:boolean;run:(action:string,payload?:Row,message?:string)=>Promise<boolean>};

const selectClass="h-10 w-full rounded-md border bg-white px-3 text-sm";
const when=(value:unknown)=>value?new Date(String(value)).toLocaleString():"";
const inputDate=(value:unknown)=>{const parsed=new Date(String(value||""));return Number.isFinite(parsed.getTime())?new Date(parsed.getTime()-parsed.getTimezoneOffset()*60000).toISOString().slice(0,16):""};
const lines=(value:unknown)=>{try{const parsed=JSON.parse(String(value||"[]"));return Array.isArray(parsed)?parsed.map(item=>typeof item==="string"?item:String((item as Row).text||"")).filter(Boolean).join("\n"):""}catch{return ""}};
function Field({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className="grid gap-1 text-sm font-medium">{label}<Input {...props}/></label>}
function Select({label,children,...props}:{label:string;children:React.ReactNode}&React.SelectHTMLAttributes<HTMLSelectElement>){return <label className="grid gap-1 text-sm font-medium">{label}<select className={selectClass} {...props}>{children}</select></label>}
function List({items,empty}:{items:string[];empty:string}){return items.length?<ul className="list-disc space-y-1.5 pl-5 text-sm leading-6 text-slate-700">{items.map((item,index)=><li key={`${index}-${item}`}>{item}</li>)}</ul>:<p className="text-sm text-slate-500">{empty}</p>}

export function MeetingIntelligencePanel({meetings,briefs,contacts,documents,dealOwner,canEdit,canReview,busy,run}:Props){
  const [editing,setEditing]=useState<Row|null>(null),[selectedKey,setSelectedKey]=useState("deal");
  const selectedBrief=briefs[selectedKey]||null,upcoming=useMemo(()=>meetings.filter(item=>String(item.status)==="Scheduled").sort((a,b)=>String(a.starts_at).localeCompare(String(b.starts_at))),[meetings]);
  const prepare=async(key:string)=>{setSelectedKey(key);await run("prepareMeeting",{meetingId:key},briefs[key]?"Meeting brief is current":"Meeting brief prepared")};
  const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),payload=Object.fromEntries(data.entries()) as Row;payload.attendeeIds=data.getAll("attendeeIds");if(editing)payload.id=editing.id;if(await run("saveMeeting",payload,editing?"Meeting record updated":"Meeting record created")){setEditing(null);form.reset()}};
  const editAttendees=new Set(((editing?.attendees as Row[]|undefined)||[]).map(item=>String(item.contact_id)));
  return <div className="grid gap-5">
    <section className="rounded-2xl border bg-slate-50 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Sparkles size={19} className="text-blue-600"/><h3 className="text-lg font-semibold">Meeting preparation</h3></div><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Prepare from the deal or select an upcoming meeting. Briefs use current CRM evidence and stay cached until a source record changes.</p></div><Button onClick={()=>void prepare("deal")} disabled={busy} variant="outline"><Sparkles size={15}/>{briefs.deal?"Refresh deal brief":"Prepare from deal"}</Button></div>
      <div className="mt-4 grid gap-3 lg:grid-cols-2">{upcoming.slice(0,6).map(meeting=><div key={String(meeting.id)} className="rounded-xl border bg-white p-4"><div className="flex items-start gap-3"><CalendarDays size={18} className="mt-0.5 text-blue-600"/><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{String(meeting.subject)}</strong><p className="mt-1 text-xs text-slate-500">{when(meeting.starts_at)} · {String(meeting.source_provider)}</p></div>{briefs[String(meeting.id)]&&<Badge variant="secondary">Brief ready</Badge>}</div><div className="mt-3 flex gap-2"><Button size="sm" onClick={()=>void prepare(String(meeting.id))} disabled={busy}><Sparkles size={14}/>Prepare</Button>{canEdit&&<Button size="sm" variant="outline" onClick={()=>setEditing(meeting)}>Edit record</Button>}</div></div>)}{!upcoming.length&&<p className="rounded-xl border border-dashed bg-white p-5 text-sm text-slate-500">No upcoming meeting is recorded. Add one below or prepare directly from the deal.</p>}</div>
    </section>

    {selectedBrief&&<Brief artifact={selectedBrief} canReview={canReview} busy={busy} review={status=>run("reviewMeetingBrief",{id:selectedBrief.id,status},`Brief ${status.toLowerCase()}`)}/>} 

    {canEdit&&<section className="rounded-xl border p-5"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">{editing?"Edit meeting record":"Add a structured meeting"}</h3><p className="mt-1 text-xs text-slate-500">Manual, Google, Microsoft, and future Granola meetings use the same record structure.</p></div>{editing&&<Button size="sm" variant="outline" onClick={()=>setEditing(null)}>Cancel edit</Button>}</div><form key={String(editing?.id||"new")} className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={save}>
      <Field label="Meeting subject" name="subject" required defaultValue={String(editing?.subject||"")}/><Select label="Status" name="status" defaultValue={String(editing?.status||"Scheduled")}><option>Scheduled</option><option>Completed</option><option>Cancelled</option></Select>
      <Field label="Starts" name="startsAt" type="datetime-local" required defaultValue={inputDate(editing?.starts_at||new Date())}/><Field label="Ends" name="endsAt" type="datetime-local" defaultValue={inputDate(editing?.ends_at)}/>
      <Field label="Owner" name="owner" required defaultValue={String(editing?.owner||dealOwner)}/><Select label="Source provider" name="sourceProvider" defaultValue={String(editing?.source_provider||"Manual")}><option>Manual</option><option>Google</option><option>Microsoft</option><option>Granola</option><option>Other</option></Select>
      <div className="rounded-xl border p-4 sm:col-span-2"><div className="mb-3 flex items-center gap-2"><Users size={16} className="text-blue-600"/><strong className="text-sm">Attendees</strong></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{contacts.map(contact=><label key={contact.id} className="flex items-start gap-2 rounded-lg bg-slate-50 p-3 text-sm"><input type="checkbox" name="attendeeIds" value={contact.id} defaultChecked={editAttendees.has(String(contact.id))}/><span><strong className="block">{contact.name}</strong><span className="text-xs text-slate-500">{contact.title||contact.email}</span></span></label>)}</div></div>
      <label className="grid gap-1 text-sm font-medium sm:col-span-2">Summary<Textarea name="summary" rows={4} defaultValue={String(editing?.summary||"")}/></label>
      <label className="grid gap-1 text-sm font-medium">Decisions <span className="font-normal text-slate-500">one per line</span><Textarea name="decisions" rows={4} defaultValue={lines(editing?.decisions_json)}/></label><label className="grid gap-1 text-sm font-medium">Risks and objections <span className="font-normal text-slate-500">one per line</span><Textarea name="risksObjections" rows={4} defaultValue={lines(editing?.risks_objections_json)}/></label>
      <label className="grid gap-1 text-sm font-medium">Customer commitments <span className="font-normal text-slate-500">one per line</span><Textarea name="customerCommitments" rows={4} defaultValue={lines(editing?.customer_commitments_json)}/></label><label className="grid gap-1 text-sm font-medium">Internal commitments <span className="font-normal text-slate-500">one per line</span><Textarea name="internalCommitments" rows={4} defaultValue={lines(editing?.internal_commitments_json)}/></label>
      <label className="grid gap-1 text-sm font-medium sm:col-span-2">Next steps <span className="font-normal text-slate-500">one per line</span><Textarea name="nextSteps" rows={4} defaultValue={lines(editing?.next_steps_json)}/></label><Field label="Next-step owner" name="nextStepOwner" defaultValue={dealOwner}/><Field label="Next-step due date" name="nextStepDueDate" type="date"/>
      <Select label="Transcript document" name="transcriptDocumentId" defaultValue={String(editing?.transcript_document_id||"")}><option value="">No transcript attached</option>{documents.map(document=><option key={String(document.id)} value={String(document.id)}>{String(document.title)} · {String(document.category)}</option>)}</Select><Field label="External meeting ID" name="externalId" defaultValue={String(editing?.external_id||"")} placeholder="Optional provider reference"/>
      <Button className="sm:col-span-2" disabled={busy}>{editing?"Update meeting":"Save meeting"}</Button>
    </form></section>}

    <section className="rounded-xl border p-5"><h3 className="font-semibold">Meeting records</h3><div className="mt-4 grid gap-3">{meetings.map(meeting=><div key={String(meeting.id)} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{String(meeting.subject)}</strong><p className="mt-1 text-xs text-slate-500">{when(meeting.starts_at)} · {String(meeting.owner)} · {String(meeting.source_provider)}</p></div><div className="flex items-center gap-2"><Badge variant={meeting.status==="Completed"?"default":"secondary"}>{String(meeting.status)}</Badge>{canEdit&&<Button size="sm" variant="outline" onClick={()=>setEditing(meeting)}>Edit</Button>}<Button size="sm" variant="outline" onClick={()=>void prepare(String(meeting.id))}><Sparkles size={14}/>Prepare</Button></div></div>{Boolean(meeting.summary)&&<p className="mt-3 whitespace-pre-wrap text-sm text-slate-700">{String(meeting.summary)}</p>}<div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500">{((meeting.attendees as Row[]|undefined)||[]).map(attendee=><span key={String(attendee.id)} className="rounded-full bg-slate-100 px-2.5 py-1">{String(attendee.contact_name||attendee.name||attendee.email)}</span>)}{Boolean(meeting.transcript_title)&&<span className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2.5 py-1 text-blue-700"><FileText size={12}/>{String(meeting.transcript_title)}</span>}</div></div>)}{!meetings.length&&<p className="rounded-xl border border-dashed p-5 text-center text-sm text-slate-500">No structured meetings yet.</p>}</div></section>
  </div>;
}

function Brief({artifact,canReview,busy,review}:{artifact:Artifact;canReview:boolean;busy:boolean;review:(status:"Accepted"|"Rejected")=>Promise<boolean>}){
 const brief=artifact.content;
 return <section className="rounded-2xl border border-blue-200 bg-blue-50/40 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Sparkles size={18} className="text-blue-600"/><h3 className="text-lg font-semibold">Meeting-preparation brief</h3><Badge variant="secondary">{artifact.reviewStatus}</Badge></div><p className="mt-2 text-sm text-slate-600">{brief.companyAndAttendeeSummary}</p></div><div className="text-right text-xs leading-5 text-slate-500">Generated {when(artifact.generatedAt)}<br/>{artifact.sourceCount} source groups · {brief.confidence} confidence</div></div>
  <div className="mt-5 grid gap-4 lg:grid-cols-2"><Block title="Current deal position"><p className="text-sm leading-6 text-slate-700">{brief.currentDealPosition}</p></Block><Block title="Last meaningful interaction"><p className="text-sm leading-6 text-slate-700">{brief.lastMeaningfulInteraction}</p></Block><Block title="Unresolved commitments"><List items={brief.unresolvedCommitments} empty="No unresolved commitments were found."/></Block><Block title="Risks and objections"><List items={brief.risksAndObjections} empty="No open risks or objections were found."/></Block><Block title="Stakeholder concerns"><List items={brief.stakeholderConcerns} empty="No current stakeholder gaps were found."/></Block><Block title="Suggested agenda"><List items={brief.suggestedAgenda} empty="No agenda items were generated."/></Block><Block title="Recommended questions" className="lg:col-span-2"><List items={brief.recommendedQuestions} empty="No questions were generated."/></Block></div>
  <div className="mt-4 rounded-xl border bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Evidence and freshness</p><p className="mt-2 text-sm text-slate-700">Sources: {brief.sourcesUsed.join(", ")}.</p><p className="mt-1 text-xs text-slate-500">Fresh through {when(brief.freshnessTime)} · {artifact.model} · {artifact.rulesVersion}</p>{brief.dataGaps.length>0&&<p className="mt-2 text-xs text-amber-700">Data gaps: {brief.dataGaps.join(" ")}</p>}</div>
  {canReview&&artifact.reviewStatus==="Draft"&&<div className="mt-4 flex gap-2"><Button size="sm" onClick={()=>void review("Accepted")} disabled={busy}><Check size={14}/>Accept brief</Button><Button size="sm" variant="outline" onClick={()=>void review("Rejected")} disabled={busy}>Reject</Button></div>}{artifact.reviewStatus==="Accepted"&&<p className="mt-4 flex items-center gap-2 text-sm text-emerald-700"><Check size={15}/>Approved by {artifact.reviewedBy||"a reviewer"}.</p>}
 </section>;
}
function Block({title,children,className=""}:{title:string;children:React.ReactNode;className?:string}){return <div className={`rounded-xl border bg-white p-4 ${className}`}><h4 className="mb-3 text-sm font-semibold">{title}</h4>{children}</div>}
