"use client";

import { useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import { CalendarDays, Check, FileText, Import, Sparkles, Upload, Users, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { parseMeetilyImport } from "@/lib/meetily-import";
import { Field } from "@/components/workspace-primitives";
import type { ContactSummary as Contact, Row } from "@/lib/crm-types";

type BriefContent={companyAndAttendeeSummary:string;currentDealPosition:string;lastMeaningfulInteraction:string;unresolvedCommitments:string[];risksAndObjections:string[];stakeholderConcerns:string[];suggestedAgenda:string[];recommendedQuestions:string[];confidence:string;dataGaps:string[];sourcesUsed:string[];freshnessTime:string};
type Artifact={id:string;meetingKey:string;reviewStatus:string;content:BriefContent;explanation:string;confidence:number;model:string;rulesVersion:string;generatedAt:string;generatedBy:string;reviewedAt:string|null;reviewedBy:string|null;sourceCount:number};
type Props={dealId:number;meetings:Row[];briefs:Record<string,Artifact|null>;contacts:Contact[];documents:Row[];dealOwner:string;canEdit:boolean;canUpload:boolean;canManageSensitive:boolean;canReview:boolean;busy:boolean;run:(action:string,payload?:Row,message?:string)=>Promise<boolean>};

const selectClass="h-10 w-full rounded-md border bg-white px-3 text-sm";
const when=(value:unknown)=>value?new Date(String(value)).toLocaleString():"";
const inputDate=(value:unknown)=>{const parsed=new Date(String(value||""));return Number.isFinite(parsed.getTime())?new Date(parsed.getTime()-parsed.getTimezoneOffset()*60000).toISOString().slice(0,16):""};
const lines=(value:unknown)=>{try{const parsed=JSON.parse(String(value||"[]"));return Array.isArray(parsed)?parsed.map(item=>typeof item==="string"?item:String((item as Row).text||"")).filter(Boolean).join("\n"):""}catch{return ""}};
function Select({label,children,...props}:{label:string;children:React.ReactNode}&React.SelectHTMLAttributes<HTMLSelectElement>){return <label className="grid gap-1 text-sm font-medium">{label}<select className={selectClass} {...props}>{children}</select></label>}
function List({items,empty}:{items:string[];empty:string}){return items.length?<ul className="list-disc space-y-1.5 pl-5 text-sm leading-6 text-slate-700">{items.map((item,index)=><li key={`${index}-${item}`}>{item}</li>)}</ul>:<p className="text-sm text-slate-500">{empty}</p>}

export function MeetingIntelligencePanel({dealId,meetings,briefs,contacts,documents,dealOwner,canEdit,canUpload,canManageSensitive,canReview,busy,run}:Props){
  const [editing,setEditing]=useState<Row|null>(null),[importDraft,setImportDraft]=useState<Row|null>(null),[selectedKey,setSelectedKey]=useState("deal"),[showMeetily,setShowMeetily]=useState(false),[meetilyNotes,setMeetilyNotes]=useState(""),[meetilyTranscript,setMeetilyTranscript]=useState(""),[importTranscript,setImportTranscript]=useState(""),[importGaps,setImportGaps]=useState<string[]>([]),[localError,setLocalError]=useState(""),[uploading,setUploading]=useState(false);
  const selectedBrief=briefs[selectedKey]||null,upcoming=useMemo(()=>meetings.filter(item=>String(item.status)==="Scheduled").sort((a,b)=>String(a.starts_at).localeCompare(String(b.starts_at))),[meetings]);
  const prepare=async(key:string)=>{setSelectedKey(key);await run("prepareMeeting",{meetingId:key},briefs[key]?"Meeting brief is current":"Meeting brief prepared")};
  const clearImport=()=>{setImportDraft(null);setImportTranscript("");setImportGaps([]);setMeetilyNotes("");setMeetilyTranscript("");setShowMeetily(false);setLocalError("")};
  const loadFile=async(event:ChangeEvent<HTMLInputElement>,target:"notes"|"transcript")=>{const file=event.target.files?.[0];if(!file)return;try{const value=await file.text();if(target==="notes")setMeetilyNotes(value);else setMeetilyTranscript(value);setLocalError("")}catch{setLocalError("The selected Meetily file could not be read.")}};
  const parseMeetily=()=>{setLocalError("");if(!meetilyNotes.trim()&&!meetilyTranscript.trim()){setLocalError("Paste or upload a Meetily summary or transcript first.");return}const parsed=parseMeetilyImport(meetilyNotes,meetilyTranscript),hints=parsed.attendeeHints.map(value=>value.toLowerCase()),matched=contacts.filter(contact=>hints.some(hint=>hint===contact.email.toLowerCase()||hint===contact.name.toLowerCase()||hint.includes(contact.email.toLowerCase())||hint.includes(contact.name.toLowerCase())));setEditing(null);setImportDraft({import_key:crypto.randomUUID(),subject:parsed.title,status:"Completed",starts_at:parsed.startsAt,owner:dealOwner,source_provider:"Meetily",summary:parsed.summary,decisions_json:JSON.stringify(parsed.decisions),customer_commitments_json:JSON.stringify(parsed.customerCommitments),internal_commitments_json:JSON.stringify(parsed.internalCommitments),risks_objections_json:JSON.stringify(parsed.risksAndObjections),next_steps_json:JSON.stringify(parsed.nextSteps),next_step_owner:parsed.nextStepOwner||dealOwner,next_step_due_date:parsed.nextStepDueDate,external_id:parsed.externalId,attendees:matched.map(contact=>({contact_id:contact.id}))});setImportTranscript(parsed.transcript);setImportGaps(parsed.dataGaps);setShowMeetily(false)};
  const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),payload=Object.fromEntries(data.entries()) as Row;payload.attendeeIds=data.getAll("attendeeIds");if(editing?.id)payload.id=editing.id;setLocalError("");let uploadedDocumentId="";try{if(importDraft&&importTranscript&&!payload.transcriptDocumentId){if(!canUpload)throw new Error("Document-upload permission is required to save the Meetily transcript.");setUploading(true);const title=String(payload.subject||"Meetily meeting").replace(/[^a-zA-Z0-9 _.-]/g,"_").slice(0,120),upload=new FormData();upload.set("entityType","deal");upload.set("entityId",String(dealId));upload.set("title",`${title} — Meetily transcript`);upload.set("category","Correspondence");if(canManageSensitive)upload.set("sensitive","true");upload.set("file",new File([importTranscript],`${title}-meetily-transcript.txt`,{type:"text/plain"}));const response=await fetch("/api/documents",{method:"POST",body:upload}),body=await response.json() as {id?:string;error?:string};if(!response.ok||!body.id)throw new Error(body.error||"The Meetily transcript could not be stored.");uploadedDocumentId=body.id;payload.transcriptDocumentId=body.id}const saved=await run("saveMeeting",payload,editing?"Meeting record updated":importDraft?"Meetily meeting imported":"Meeting record created");if(saved){setEditing(null);clearImport();form.reset()}else if(uploadedDocumentId)setLocalError("The transcript was stored in deal documents, but the meeting was not saved. Select that transcript and retry.")}catch(error){setLocalError(error instanceof Error?error.message:"The Meetily meeting could not be imported.")}finally{setUploading(false)}};
  const formRecord=editing||importDraft,editAttendees=new Set(((formRecord?.attendees as Row[]|undefined)||[]).map(item=>String(item.contact_id)));
  return <div className="grid gap-5">
    <section className="rounded-2xl border bg-slate-50 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Sparkles size={19} className="text-blue-600"/><h3 className="text-lg font-semibold">Meeting preparation</h3></div><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Prepare from the deal or select an upcoming meeting. Briefs use current CRM evidence and stay cached until a source record changes.</p></div><Button onClick={()=>void prepare("deal")} disabled={busy} variant="outline"><Sparkles size={15}/>{briefs.deal?"Refresh deal brief":"Prepare from deal"}</Button></div>
      <div className="mt-4 grid gap-3 lg:grid-cols-2">{upcoming.slice(0,6).map(meeting=><div key={String(meeting.id)} className="rounded-xl border bg-white p-4"><div className="flex items-start gap-3"><CalendarDays size={18} className="mt-0.5 text-blue-600"/><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{String(meeting.subject)}</strong><p className="mt-1 text-xs text-slate-500">{when(meeting.starts_at)} · {String(meeting.source_provider)}</p></div>{briefs[String(meeting.id)]&&<Badge variant="secondary">Brief ready</Badge>}</div><div className="mt-3 flex gap-2"><Button size="sm" onClick={()=>void prepare(String(meeting.id))} disabled={busy}><Sparkles size={14}/>Prepare</Button>{canEdit&&<Button size="sm" variant="outline" onClick={()=>setEditing(meeting)}>Edit record</Button>}</div></div>)}{!upcoming.length&&<p className="rounded-xl border border-dashed bg-white p-5 text-sm text-slate-500">No upcoming meeting is recorded. Add one below or prepare directly from the deal.</p>}</div>
    </section>

    {selectedBrief&&<Brief artifact={selectedBrief} canReview={canReview} busy={busy} review={status=>run("reviewMeetingBrief",{id:selectedBrief.id,status},`Brief ${status.toLowerCase()}`)}/>} 

    {canEdit&&<section className="rounded-xl border p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{editing?"Edit meeting record":importDraft?"Review Meetily import":"Add a structured meeting"}</h3><p className="mt-1 text-xs text-slate-500">Meetily, manual, Google, and Microsoft meetings use the same reviewed record structure.</p></div><div className="flex gap-2">{!editing&&<Button type="button" size="sm" variant="outline" onClick={()=>setShowMeetily(value=>!value)}><Import size={14}/>Import Meetily notes</Button>}{(editing||importDraft)&&<Button type="button" size="sm" variant="outline" onClick={()=>{setEditing(null);clearImport()}}><X size={14}/>Cancel</Button>}</div></div>
      {showMeetily&&<div className="mt-5 rounded-xl border border-blue-200 bg-blue-50/50 p-4"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-blue-600 text-white"><Import size={17}/></span><div><strong className="text-sm text-blue-950">Import from Meetily</strong><p className="mt-1 text-xs leading-5 text-blue-800">In Meetily, copy the meeting summary and transcript, then paste them here. You can also upload copied Markdown or text files. Nothing is saved until you review and submit the meeting form.</p></div></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Meeting summary<Textarea rows={8} value={meetilyNotes} onChange={event=>setMeetilyNotes(event.target.value)} placeholder="# Meeting Summary: …&#10;&#10;## Summary&#10;…&#10;&#10;## Key Decisions&#10;…"/><span className="flex items-center gap-2 text-xs font-normal text-slate-500"><Upload size={13}/><input type="file" accept=".md,.txt,text/plain" onChange={event=>void loadFile(event,"notes")}/></span></label><label className="grid gap-1 text-sm font-medium">Transcript <span className="font-normal text-slate-500">optional</span><Textarea rows={8} value={meetilyTranscript} onChange={event=>setMeetilyTranscript(event.target.value)} placeholder="# Transcript of the Meeting: …"/><span className="flex items-center gap-2 text-xs font-normal text-slate-500"><Upload size={13}/><input type="file" accept=".md,.txt,text/plain" onChange={event=>void loadFile(event,"transcript")}/></span></label></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500">Audio and video are never uploaded. Transcript text is stored as a private deal document.</p><Button type="button" onClick={parseMeetily}><Sparkles size={15}/>Parse for review</Button></div></div>}
      {localError&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{localError}</p>}{importDraft&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary">Review required</Badge><strong className="text-sm text-amber-950">Meetily content has not been saved yet</strong></div><p className="mt-2 text-sm leading-6 text-amber-900">Check the fields and attendee matches below. Saving creates a completed meeting activity; the transcript is stored as a private client document when supplied.</p>{importGaps.length>0&&<ul className="mt-2 list-disc pl-5 text-xs leading-5 text-amber-800">{importGaps.map(gap=><li key={gap}>{gap}</li>)}</ul>}</div>}
      <form key={String(formRecord?.id||formRecord?.import_key||"new")} className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={save}>
      <Field label="Meeting subject" name="subject" required defaultValue={String(formRecord?.subject||"")}/><Select label="Status" name="status" defaultValue={String(formRecord?.status||"Scheduled")}><option>Scheduled</option><option>Completed</option><option>Cancelled</option></Select>
      <Field label="Starts" name="startsAt" type="datetime-local" required defaultValue={inputDate(formRecord?.starts_at||new Date())}/><Field label="Ends" name="endsAt" type="datetime-local" defaultValue={inputDate(formRecord?.ends_at)}/>
      <Field label="Owner" name="owner" required defaultValue={String(formRecord?.owner||dealOwner)}/><Select label="Source provider" name="sourceProvider" defaultValue={String(formRecord?.source_provider||"Manual")}><option>Manual</option><option>Google</option><option>Microsoft</option><option>Meetily</option><option>Granola</option><option>Other</option></Select>
      <div className="rounded-xl border p-4 sm:col-span-2"><div className="mb-3 flex items-center gap-2"><Users size={16} className="text-blue-600"/><strong className="text-sm">Attendees</strong></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{contacts.map(contact=><label key={contact.id} className="flex items-start gap-2 rounded-lg bg-slate-50 p-3 text-sm"><input type="checkbox" name="attendeeIds" value={contact.id} defaultChecked={editAttendees.has(String(contact.id))}/><span><strong className="block">{contact.name}</strong><span className="text-xs text-slate-500">{contact.title||contact.email}</span></span></label>)}</div></div>
      <label className="grid gap-1 text-sm font-medium sm:col-span-2">Summary<Textarea name="summary" rows={4} defaultValue={String(formRecord?.summary||"")}/></label>
      <label className="grid gap-1 text-sm font-medium">Decisions <span className="font-normal text-slate-500">one per line</span><Textarea name="decisions" rows={4} defaultValue={lines(formRecord?.decisions_json)}/></label><label className="grid gap-1 text-sm font-medium">Risks and objections <span className="font-normal text-slate-500">one per line</span><Textarea name="risksObjections" rows={4} defaultValue={lines(formRecord?.risks_objections_json)}/></label>
      <label className="grid gap-1 text-sm font-medium">Customer commitments <span className="font-normal text-slate-500">one per line</span><Textarea name="customerCommitments" rows={4} defaultValue={lines(formRecord?.customer_commitments_json)}/></label><label className="grid gap-1 text-sm font-medium">Internal commitments <span className="font-normal text-slate-500">one per line</span><Textarea name="internalCommitments" rows={4} defaultValue={lines(formRecord?.internal_commitments_json)}/></label>
      <label className="grid gap-1 text-sm font-medium sm:col-span-2">Next steps <span className="font-normal text-slate-500">one per line</span><Textarea name="nextSteps" rows={4} defaultValue={lines(formRecord?.next_steps_json)}/></label><Field label="Next-step owner" name="nextStepOwner" defaultValue={String(formRecord?.next_step_owner||dealOwner)}/><Field label="Next-step due date" name="nextStepDueDate" type="date" defaultValue={String(formRecord?.next_step_due_date||"")}/>
      <Select label="Transcript document" name="transcriptDocumentId" defaultValue={String(formRecord?.transcript_document_id||"")}><option value="">{importTranscript?"Create from imported transcript":"No transcript attached"}</option>{documents.map(document=><option key={String(document.id)} value={String(document.id)}>{String(document.title)} · {String(document.category)}</option>)}</Select><Field label="External meeting ID" name="externalId" defaultValue={String(formRecord?.external_id||"")} placeholder="Optional provider reference"/>
      <Button className="sm:col-span-2" disabled={busy||uploading}>{uploading?"Storing transcript…":editing?"Update meeting":importDraft?"Save Meetily meeting":"Save meeting"}</Button>
    </form></section>}

    <section className="rounded-xl border p-5"><h3 className="font-semibold">Meeting records</h3><div className="mt-4 grid gap-3">{meetings.map(meeting=><div key={String(meeting.id)} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{String(meeting.subject)}</strong><p className="mt-1 text-xs text-slate-500">{when(meeting.starts_at)} · {String(meeting.owner)} · {String(meeting.source_provider)}</p></div><div className="flex items-center gap-2"><Badge variant={meeting.status==="Completed"?"default":"secondary"}>{String(meeting.status)}</Badge>{canEdit&&<Button size="sm" variant="outline" onClick={()=>setEditing(meeting)}>Edit</Button>}<Button size="sm" variant="outline" onClick={()=>void prepare(String(meeting.id))}><Sparkles size={14}/>Prepare</Button></div></div>{Boolean(meeting.summary)&&<p className="mt-3 whitespace-pre-wrap text-sm text-slate-700">{String(meeting.summary)}</p>}<div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500">{((meeting.attendees as Row[]|undefined)||[]).map(attendee=><span key={String(attendee.id)} className="rounded-full bg-slate-100 px-2.5 py-1">{String(attendee.contact_name||attendee.name||attendee.email)}</span>)}{Boolean(meeting.transcript_title)&&<span className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2.5 py-1 text-blue-700"><FileText size={12}/>{String(meeting.transcript_title)}</span>}</div></div>)}{!meetings.length&&<p className="rounded-xl border border-dashed p-5 text-center text-sm text-slate-500">No structured meetings yet.</p>}</div></section>
  </div>;
}

function Brief({artifact,canReview,busy,review}:{artifact:Artifact;canReview:boolean;busy:boolean;review:(status:"Accepted"|"Rejected")=>Promise<boolean>}){
 const brief=artifact.content;
 return <section className="rounded-2xl border border-blue-200 bg-blue-50/40 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Sparkles size={18} className="text-blue-600"/><h3 className="text-lg font-semibold">Meeting-preparation brief</h3><Badge variant="secondary">{artifact.reviewStatus}</Badge></div><p className="mt-2 text-sm text-slate-600">{brief.companyAndAttendeeSummary}</p></div><div className="text-right text-xs leading-5 text-slate-500">Generated {when(artifact.generatedAt)}<br/>{artifact.sourceCount} source groups · {brief.confidence} confidence</div></div>
  <div className="mt-5 grid gap-4 lg:grid-cols-2"><Block title="Current deal position"><p className="text-sm leading-6 text-slate-700">{brief.currentDealPosition}</p></Block><Block title="Last meaningful interaction"><p className="text-sm leading-6 text-slate-700">{brief.lastMeaningfulInteraction}</p></Block><Block title="Unresolved commitments"><List items={brief.unresolvedCommitments} empty="No unresolved commitments were found."/></Block><Block title="Risks and objections"><List items={brief.risksAndObjections} empty="No open risks or objections were found."/></Block><Block title="Stakeholder concerns"><List items={brief.stakeholderConcerns} empty="No current stakeholder gaps were found."/></Block><Block title="Suggested agenda"><List items={brief.suggestedAgenda} empty="No agenda items were generated."/></Block><Block title="Recommended questions" className="lg:col-span-2"><List items={brief.recommendedQuestions} empty="No questions were generated."/></Block></div>
  <div className="mt-4 rounded-xl border bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Evidence and freshness</p><p className="mt-2 text-sm text-slate-700">Sources: {brief.sourcesUsed.join(", ")}.</p><p className="mt-1 text-xs text-slate-500">Fresh through {when(brief.freshnessTime)} · {artifact.model} · {artifact.rulesVersion}</p>{brief.dataGaps.length>0&&<p className="mt-2 text-xs text-amber-700">Data gaps: {brief.dataGaps.join(" ")}</p>}</div>
  {canReview&&artifact.reviewStatus==="Draft"&&<div className="mt-4 flex gap-2"><Button size="sm" onClick={()=>void review("Accepted")} disabled={busy}><Check size={14}/>Accept brief</Button><Button size="sm" variant="outline" onClick={()=>void review("Rejected")} disabled={busy}>Reject</Button></div>}{artifact.reviewStatus==="Accepted"&&<p className="mt-4 flex items-center gap-2 text-sm text-emerald-700"><Check size={15}/>Approved by {artifact.reviewedBy||"a reviewer"}.</p>}
 </section>;
}
function Block({title,children,className=""}:{title:string;children:React.ReactNode;className?:string}){return <div className={`rounded-xl border bg-white p-4 ${className}`}><h4 className="mb-3 text-sm font-semibold">{title}</h4>{children}</div>}
