"use client";

import { useState, type FormEvent, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/workspace-primitives";
import { dealRequiredFieldOptions, defaultPipeline, type Pipeline, type Stage } from "@/lib/sales-rules";

export type Run=(action:string,payload:Record<string,unknown>)=>Promise<boolean>;
const selectClass="h-10 min-w-0 w-full rounded-md border bg-white px-3 text-sm";
function Select({label,children,...props}:{label:string;children:ReactNode}&React.SelectHTMLAttributes<HTMLSelectElement>){return <label className="grid gap-1 text-sm font-medium">{label}<select className={selectClass} {...props}>{children}</select></label>}
function payload(e:FormEvent<HTMLFormElement>){e.preventDefault();return Object.fromEntries(new FormData(e.currentTarget).entries());}

export function PipelineEditor({pipeline,disabled,run,close}:{pipeline?:Pipeline;disabled:boolean;run:Run;close:()=>void}){
 const [stages,setStages]=useState<Stage[]>(pipeline?.stages||defaultPipeline.stages.map(s=>({...s,key:crypto.randomUUID()})));
 const edit=(i:number,patch:Partial<Stage>)=>setStages(v=>v.map((s,n)=>n===i?{...s,...patch}:s));
 return <form onSubmit={async e=>{if(await run("savePipeline",{...payload(e),id:pipeline?.id,stages}))close()}}><Field label="Pipeline name" name="name" required defaultValue={pipeline?.name||""}/><p className="my-4 text-xs leading-5 text-slate-500">Stage names, probabilities, and required deal fields are configurable. Won is always 100%; lost is 0%. Reordering changes board order.</p><div className="grid gap-3">{stages.map((s,i)=><div key={s.key} className="rounded-xl border bg-slate-50 p-3"><div className="grid gap-2 sm:grid-cols-[1fr_100px_110px_auto]"><Field label={"Stage "+(i+1)} value={s.name} required onChange={e=>edit(i,{name:e.target.value})}/><Field label="Probability %" type="number" min="0" max="100" value={s.kind==="Won"?100:s.kind==="Lost"?0:s.probability} disabled={s.kind!=="Open"} onChange={e=>edit(i,{probability:Number(e.target.value)})}/><Select label="Outcome" value={s.kind} disabled={!!pipeline?.stages.some(p=>p.key===s.key)} onChange={e=>edit(i,{kind:e.target.value as Stage["kind"]})}>{["Open","Won","Lost"].map(k=><option key={k}>{k}</option>)}</Select><div className="flex items-end gap-1"><Button type="button" size="sm" variant="outline" aria-label={"Move "+s.name+" up"} disabled={!i} onClick={()=>setStages(v=>{const a=[...v];[a[i-1],a[i]]=[a[i],a[i-1]];return a})}>↑</Button><Button type="button" size="sm" variant="outline" aria-label={"Remove "+s.name} onClick={()=>setStages(v=>v.filter(x=>x.key!==s.key))}>×</Button></div></div><div className="mt-3 border-t pt-3"><p className="mb-2 text-xs font-medium text-slate-600">Required before entering this stage</p><div className="flex flex-wrap gap-x-4 gap-y-2">{dealRequiredFieldOptions.map(field=><label key={field} className="flex items-center gap-2 text-xs capitalize"><input type="checkbox" checked={s.requiredFields?.includes(field)||false} onChange={e=>edit(i,{requiredFields:e.target.checked?[...(s.requiredFields||[]),field]:(s.requiredFields||[]).filter(v=>v!==field)})}/>{field.replace(/([A-Z])/g," $1")}</label>)}</div></div></div>)}</div><div className="mt-5 flex flex-wrap justify-between gap-3"><Button type="button" variant="outline" disabled={stages.length>=16} onClick={()=>setStages(v=>[...v,{key:crypto.randomUUID(),name:"New stage",probability:50,kind:"Open",requiredFields:[]}])}>Add stage</Button><Button disabled={disabled}>Save pipeline</Button></div></form>;
}
