"use client";
import { useCallback, useEffect, useState } from "react";
import { Check, ClipboardCheck, FileCheck2, Inbox, Merge, Plus, Send, Sparkles, Webhook } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Heading, Panel } from "@/components/workspace-primitives";
import type { Row } from "@/lib/crm-types";
import { money } from "@/lib/format";

type Data={account:{email:string};leads:Row[];messages:Row[];deals:Row[];incomplete:Row[];duplicates:Row[];proposals:Row[];brand:{businessName:string;logoUrl:string;physicalAddress:string};endpoints:{leadCapture:string;inboxCapture:string}};
const when=(value:unknown)=>value?new Date(String(value)).toLocaleString():"—";

export function RevenueOpsWorkspace({section}:{section:"leads"|"inbox"|"cleanup"|"proposals"}){
 const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/revenue-ops",{cache:"no-store"}),body=await r.json() as Data&{error?:string};if(!r.ok)throw new Error(body.error||"Revenue operations could not load.");setData(body);setError("")},[]);
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Revenue operations could not load."))},[load]);
 const run=async(action:string,payload:Row={},message="Saved")=>{setBusy(action);setError("");try{const r=await fetch("/api/revenue-ops",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload})}),body=await r.json() as {error?:string};if(!r.ok)throw new Error(body.error||"The change could not be saved.");await load();window.dispatchEvent(new Event("crm-changed"));setNotice(message);window.setTimeout(()=>setNotice(""),2400);return true}catch(e){setError(e instanceof Error?e.message:"The change could not be saved.");return false}finally{setBusy("")}};
 const uploadAttachments=async(files:FileList,entityType:"contact"|"company"|"deal",entityId:number)=>{for(const file of Array.from(files)){const form=new FormData();form.set("entityType",entityType);form.set("entityId",String(entityId));form.set("title",file.name);form.set("category","Correspondence");form.set("file",file);const response=await fetch("/api/documents",{method:"POST",body:form}),body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||`Could not save ${file.name}.`)}};
 const printable=(proposal:Row)=>{if(!data)return;const escape=(value:unknown)=>String(value||"").replace(/[&<>\"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[char]||char));const popup=window.open("","_blank","width=900,height=760");if(!popup)return;popup.document.write(`<!doctype html><html><head><title>${escape(proposal.title)}</title><style>body{max-width:760px;margin:48px auto;font:16px/1.6 Arial;color:#172033}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #3156c9;padding-bottom:20px}.logo{max-height:48px;max-width:180px}pre{white-space:pre-wrap;font:inherit}.meta{margin:28px 0;padding:16px;background:#f5f7fb}.foot{margin-top:48px;font-size:12px;color:#64748b}</style></head><body><div class="head"><div><h1>${escape(data.brand.businessName||"ClientRecord")}</h1><strong>${escape(proposal.title)}</strong></div>${data.brand.logoUrl?`<img class="logo" src="${escape(data.brand.logoUrl)}"/>`:""}</div><div class="meta"><strong>Prepared for:</strong> ${escape(proposal.company||"")}<br/><strong>Investment:</strong> ${money(proposal.amount)}<br/><strong>Valid until:</strong> ${escape(proposal.validUntil||"To be confirmed")}</div><pre>${escape(proposal.bodyMarkdown||"Proposal content has not been added yet.")}</pre><div class="foot">${escape(data.brand.physicalAddress||"")}</div><script>window.onload=()=>window.print()<\/script></body></html>`);popup.document.close()};
 if(!data)return <Panel rounded="2xl" className="p-6 text-sm text-slate-500">{error||"Loading revenue operations…"}</Panel>;
 return <>{error&&<div className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{notice&&<div className="mb-4 flex items-center gap-2 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><Check size={16}/>{notice}</div>}
 {section==="leads"&&<><Heading eyebrow="Lead capture" title="Capture and route every inbound lead"/><div className="grid gap-6 xl:grid-cols-[1fr_1.2fr]"><Panel rounded="2xl" className="p-5"><div className="flex items-center gap-2"><Plus size={18}/><h2 className="font-semibold">Add a lead</h2></div><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void run("captureLead",Object.fromEntries(new FormData(e.currentTarget).entries()),"Lead captured and follow-up task created").then(ok=>{if(ok)e.currentTarget.reset()})}}><Input name="firstName" placeholder="First name"/><Input name="lastName" placeholder="Last name"/><Input required name="email" type="email" placeholder="Email"/><Input name="company" placeholder="Company"/><Input name="website" placeholder="Website"/><Input name="source" defaultValue="Website" placeholder="Source"/><Textarea className="sm:col-span-2" name="message" placeholder="Inquiry or context"/><Button disabled={Boolean(busy)} className="sm:col-span-2">Capture and route</Button></form><div className="mt-5 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-600"><strong className="text-slate-900">Website endpoint</strong><code className="mt-2 block break-all rounded bg-white p-2">{data.endpoints.leadCapture}</code><p className="mt-2">POST the form data with a <code>leads.capture</code> API key. Exact email matches are held as duplicates; new leads receive an immediate owner task.</p></div></Panel><Panel rounded="2xl" className="overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Routing queue</h2><p className="mt-1 text-sm text-slate-500">Source, duplicate state, owner, and follow-up are visible together.</p></div>{data.leads.map(lead=><div key={String(lead.id)} className="grid gap-3 border-b p-4 last:border-0 md:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-2"><strong>{String(lead.first_name||"")} {String(lead.last_name||lead.email)}</strong><Badge variant={lead.status==="Duplicate"?"destructive":"secondary"}>{String(lead.status)}</Badge></div><p className="mt-1 text-sm text-slate-600">{String(lead.email)} · {String(lead.company_name||"No company")}</p><p className="mt-1 text-xs text-slate-500">{String(lead.source)} · {when(lead.received_at)} · owner {String(lead.owner||"Unassigned")}</p></div><div className="flex items-center gap-2"><select defaultValue={String(lead.status)} onChange={e=>void run("routeLead",{id:lead.id,status:e.target.value,owner:lead.owner||data.account.email},"Lead routing updated")} className="h-9 rounded-md border bg-white px-2 text-sm"><option>New</option><option>Duplicate</option><option>Routed</option><option>Resolved</option><option>Rejected</option></select></div></div>)}{!data.leads.length&&<div className="p-8 text-center text-sm text-slate-500">No leads have been captured.</div>}</Panel></div></>}
 {section==="inbox"&&<><Heading eyebrow="Manual capture" title="Add an email to the shared inbox"/><div className="max-w-2xl"><Panel rounded="2xl" className="p-5"><div className="flex items-center gap-2"><Inbox size={18}/><h2 className="font-semibold">Capture email</h2></div><form className="mt-4 grid gap-3" onSubmit={e=>{e.preventDefault();void run("captureInbox",Object.fromEntries(new FormData(e.currentTarget).entries()),"Email added to the inbox").then(ok=>{if(ok)e.currentTarget.reset()})}}><Input required type="email" name="fromEmail" placeholder="Sender email"/><Input name="fromName" placeholder="Sender name"/><Input name="subject" placeholder="Subject"/><Textarea name="body" rows={7} placeholder="Message content"/><Input name="attachmentNames" placeholder="Attachment names, comma separated"/><Button disabled={Boolean(busy)}>Add to inbox</Button></form><div className="mt-5 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-600"><strong className="text-slate-900">Inbound-email endpoint</strong><code className="mt-2 block break-all rounded bg-white p-2">{data.endpoints.inboxCapture}</code><p className="mt-2">Use an <code>inbox.capture</code> API key from a mailbox parser or automation. Assigning an email creates CRM timeline activity and can create a follow-up task.</p></div></Panel></div></>}
 {section==="proposals"&&<><Heading eyebrow="Commercial workflow" title="Quotes, proposals, and approvals"/><Panel rounded="2xl" className="overflow-hidden"><div className="border-b p-5"><h2 className="font-semibold">Proposal delivery tracker</h2><p className="mt-1 text-sm text-slate-500">AI drafts remain in the deal workspace. Open a branded, print-ready document here, record sent/opened/accepted milestones, and request discount or legal review from the deal’s Reviews & approvals view.</p></div>{data.proposals.map(proposal=><div key={String(proposal.id)} className="grid gap-3 border-b p-4 last:border-0 md:grid-cols-[1fr_auto_auto]"><div><strong>{String(proposal.title)}</strong><p className="mt-1 text-sm text-slate-600">{String(proposal.dealName)} · {String(proposal.company||"No company")} · {money(proposal.amount)}</p><p className="mt-1 text-xs text-slate-500">Sent {when(proposal.sentAt)} · opened {when(proposal.openedAt)} · accepted {when(proposal.acceptedAt)}</p></div><div className="flex items-center gap-2"><Badge variant={proposal.status==="Accepted"?"default":proposal.status==="Declined"?"destructive":"secondary"}>{String(proposal.status)}</Badge><Button size="sm" variant="outline" onClick={()=>printable(proposal)}>Print / PDF</Button></div><select defaultValue={String(proposal.status)} onChange={e=>void run("updateProposalStatus",{id:proposal.id,status:e.target.value},`Proposal marked ${e.target.value.toLowerCase()}`)} className="h-9 rounded-md border bg-white px-2 text-sm"><option>Draft</option><option>Sent</option><option>Opened</option><option>Accepted</option><option>Declined</option><option>Expired</option></select></div>)}{!data.proposals.length&&<div className="p-8 text-center text-sm text-slate-500">Save an accepted AI draft from a deal to begin tracking it here.</div>}</Panel></>}
 {section==="cleanup"&&<><Heading eyebrow="Data quality" title="Cleanup center"/><div className="grid gap-6 xl:grid-cols-2"><Panel rounded="2xl" className="overflow-hidden"><div className="border-b p-5"><div className="flex items-center gap-2"><Merge size={18}/><h2 className="font-semibold">Possible company duplicates</h2></div><p className="mt-1 text-sm text-slate-500">Same normalized company name or website domain.</p></div>{data.duplicates.map(item=><div key={`${item.aId}-${item.bId}`} className="flex flex-wrap items-center gap-3 border-b p-4"><div className="min-w-0 flex-1"><strong>{String(item.aName)}</strong><span className="mx-2 text-slate-400">and</span><strong>{String(item.bName)}</strong><p className="mt-1 text-xs text-slate-500">{String(item.domain||"Matching name")}</p></div><Button size="sm" variant="outline" disabled={Boolean(busy)} onClick={()=>{if(window.confirm(`Merge ${item.aName} into ${item.bName}?`))void run("mergeCompanies",{sourceId:item.aId,targetId:item.bId},"Companies merged")}}>Merge</Button></div>)}{!data.duplicates.length&&<div className="p-8 text-center text-sm text-slate-500">No company duplicates detected.</div>}</Panel><Panel rounded="2xl" className="overflow-hidden"><div className="border-b p-5"><div className="flex items-center gap-2"><ClipboardCheck size={18}/><h2 className="font-semibold">Incomplete company records</h2></div><p className="mt-1 text-sm text-slate-500">Missing owner, website/domain, or industry.</p></div>{data.incomplete.map(item=><div key={String(item.id)} className="flex flex-wrap items-center gap-3 border-b p-4"><div className="min-w-0 flex-1"><strong>{String(item.name)}</strong><p className="mt-1 text-xs text-slate-500">{[!item.website&&"website",!item.domain&&"domain",!item.owner&&"owner",!item.industry&&"industry"].filter(Boolean).join(" · ")}</p></div>{Boolean(item.domain)&&<Button size="sm" variant="outline" disabled={Boolean(busy)} onClick={()=>void run("matchCompanyDomain",{companyId:item.id},"Domain matching completed")}>Match contacts</Button>}</div>)}{!data.incomplete.length&&<div className="p-8 text-center text-sm text-slate-500">No incomplete company records.</div>}</Panel></div></>}
 </>;
}
