"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Clock3, Plus, TicketCheck, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { ContextBlock, Pagination, RecordDrawer, ViewBar, WorkspaceEmpty, WorkspaceError, type WorkspaceDensity, type WorkspaceMode } from "@/components/workspace-primitives";

type Row=Record<string,unknown>;
type Data={account:{email:string};cases:Row[];caseNotes:Row[];companies:Row[];contacts:Row[];deals:Row[];serviceSummary:{open:number;breached:number;unassigned:number}};
const text=(value:unknown)=>String(value??"");
const dateTime=(value:unknown)=>value?new Date(text(value)).toLocaleString():"Not set";
const fieldClass="h-10 w-full rounded-md border bg-white px-3 text-sm";

export function ServiceWorkspace(){
 const[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const[mode,setMode]=useState<WorkspaceMode>("table"),[density,setDensity]=useState<WorkspaceDensity>("comfortable"),[view,setView]=useState("All open"),[page,setPage]=useState(1),[selected,setSelected]=useState<Row|null>(null),[creating,setCreating]=useState(false),[checked,setChecked]=useState<string[]>([]);
 const load=useCallback(async()=>{try{const response=await fetch("/api/platform-expansion",{cache:"no-store"}),body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error||"Cases could not load.");setData(body);setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Cases could not load.")}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 async function run(action:string,payload:Row,message="Saved") {setBusy(true);setError("");try{const response=await fetch("/api/platform-expansion",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload})}),body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"The change could not be saved.");await load();setNotice(message);window.setTimeout(()=>setNotice(""),2800);return true}catch(reason){setError(reason instanceof Error?reason.message:"The change could not be saved.");return false}finally{setBusy(false)}}
 const cases=useMemo(()=>{if(!data)return[];return data.cases.filter(item=>{const status=text(item.status);if(view==="Mine")return text(item.owner)===data.account.email;if(view==="SLA risk")return status==="Escalated"||(!["Resolved","Closed"].includes(status)&&new Date(text(item.response_due_at))<new Date());if(view==="Unassigned")return !text(item.owner);return !["Resolved","Closed"].includes(status)})},[data,view]);
 const pages=Math.max(1,Math.ceil(cases.length/20)),visible=cases.slice((page-1)*20,page*20);
 if(!data)return <div className="skeleton-workspace" aria-label="Loading cases"/>;
 const notes=selected?data.caseNotes.filter(note=>text(note.case_id)===text(selected.id)):[];
 const selectedContact=data.contacts.find(item=>text(item.id)===text(selected?.contact_id));
 const selectedCompany=data.companies.find(item=>text(item.id)===text(selected?.company_id));
 const selectedDeal=data.deals.find(item=>text(item.id)===text(selected?.deal_id));
 const slaRisk=selected&&!(["Resolved","Closed"].includes(text(selected.status)))&&new Date(text(selected.response_due_at))<new Date();
 async function saveCase(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget).entries());const ok=await run("saveCase",{...form,id:selected?.id||undefined},selected?"Case updated":"Case created");if(ok){setCreating(false);setSelected(null)}}
 async function addNote(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=Object.fromEntries(new FormData(event.currentTarget).entries());if(await run("addCaseNote",{...form,caseId:selected.id},"Internal note added"))event.currentTarget.reset()}
 const rail=<>{selected&&<><ContextBlock title="Next action"><strong>{slaRisk?"Respond now":"Continue resolution"}</strong><p className="mt-1 text-xs text-slate-500">Response due {dateTime(selected.response_due_at)}</p></ContextBlock><ContextBlock title="Owner and status"><dl className="grid gap-2"><div><span className="text-slate-500">Owner</span><strong className="block">{text(selected.owner)||"Unassigned"}</strong></div><div><span className="text-slate-500">Queue</span><strong className="block">{text(selected.queue)||"General"}</strong></div><div><span className="text-slate-500">Status</span><strong className="block">{text(selected.status)}</strong></div></dl></ContextBlock><ContextBlock title="SLA and risk"><div className={slaRisk?"text-red-700":"text-emerald-700"}><strong>{slaRisk?"Response SLA breached":"SLA on track"}</strong></div><p className="mt-2 text-xs text-slate-500">Resolution due {dateTime(selected.resolution_due_at)}</p></ContextBlock><ContextBlock title="Recent changes"><p className="text-xs text-slate-500">Updated {dateTime(selected.updated_at)}</p><p className="mt-1 text-xs text-slate-500">Created {dateTime(selected.created_at)}</p></ContextBlock></>}</>;
 return <div>
  <div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-blue-600">Service operations</p><h1 className="mt-1 text-2xl font-semibold">Cases</h1><p className="mt-1 text-sm text-slate-500">Route, resolve, and audit customer requests without losing the surrounding account context.</p></div><Button onClick={()=>{setSelected(null);setCreating(true)}}><Plus size={16}/>New case</Button></div>
  {error&&<div className="mb-4"><WorkspaceError message={error} retry={()=>void load()}/></div>}{notice&&<div className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</div>}
  <div className="mb-5 grid gap-3 sm:grid-cols-3"><Metric icon={<TicketCheck size={17}/>} label="Open cases" value={data.serviceSummary.open}/><Metric icon={<Clock3 size={17}/>} label="SLA escalations" value={data.serviceSummary.breached}/><Metric icon={<UsersRound size={17}/>} label="Unassigned" value={data.serviceSummary.unassigned}/></div>
  <ViewBar views={["All open","Mine","SLA risk","Unassigned"]} activeView={view} onView={value=>{setView(value);setPage(1)}} mode={mode} onMode={setMode} density={density} onDensity={setDensity}>{checked.length>0&&<div className="flex items-center gap-2 text-xs"><strong>{checked.length} selected</strong><Button size="sm" variant="outline" onClick={()=>setChecked([])}>Clear</Button></div>}</ViewBar>
  {mode==="table"?<section className="overflow-hidden rounded-lg border bg-white"><div className={`universal-table overflow-auto ${density==="compact"?"universal-table-compact":""}`}><table><thead><tr><th className="w-10"><input aria-label="Select visible cases" type="checkbox" checked={visible.length>0&&visible.every(item=>checked.includes(text(item.id)))} onChange={event=>setChecked(event.target.checked?Array.from(new Set([...checked,...visible.map(item=>text(item.id))])):checked.filter(id=>!visible.some(item=>text(item.id)===id)))}/></th><th>Case</th><th>Priority</th><th>Queue</th><th>Status</th><th>Owner</th><th>Response due</th></tr></thead><tbody>{visible.map(item=><tr key={text(item.id)} onClick={()=>setSelected(item)}><td onClick={event=>event.stopPropagation()}><input aria-label={`Select ${text(item.subject)}`} type="checkbox" checked={checked.includes(text(item.id))} onChange={event=>setChecked(event.target.checked?[...checked,text(item.id)]:checked.filter(id=>id!==text(item.id)))}/></td><td><strong>{text(item.subject)}</strong><span className="mt-1 block text-xs text-slate-500">{text(item.case_number)} · {text(item.company_name)||"Unlinked company"}</span></td><td><Priority value={text(item.priority)}/></td><td>{text(item.queue)||"General"}</td><td><Badge variant="secondary">{text(item.status)}</Badge></td><td>{text(item.owner)||"Unassigned"}</td><td className={new Date(text(item.response_due_at))<new Date()?"text-red-700":""}>{dateTime(item.response_due_at)}</td></tr>)}</tbody></table></div>{visible.length===0?<WorkspaceEmpty title="No cases in this view" detail="Create a case or choose a different saved view." action={<Button onClick={()=>setCreating(true)}><Plus size={16}/>Create case</Button>}/>:<Pagination page={page} pages={pages} onPage={setPage}/>}</section>:<div className="grid gap-4 lg:grid-cols-4">{["New","In progress","Waiting on customer","Escalated"].map(status=><section key={status} className="min-w-0 rounded-lg border bg-slate-50/70"><header className="flex items-center justify-between border-b px-3 py-3 text-sm font-semibold"><span>{status}</span><Badge variant="outline">{cases.filter(item=>text(item.status)===status).length}</Badge></header><div className="grid gap-2 p-2">{cases.filter(item=>text(item.status)===status).map(item=><button key={text(item.id)} className="rounded-md border bg-white p-3 text-left shadow-sm hover:border-blue-300" onClick={()=>setSelected(item)}><strong className="line-clamp-2 text-sm">{text(item.subject)}</strong><p className="mt-2 text-xs text-slate-500">{text(item.company_name)||"Unlinked"}</p><div className="mt-3 flex items-center justify-between gap-2"><Priority value={text(item.priority)}/>{new Date(text(item.response_due_at))<new Date()&&<AlertTriangle size={15} className="text-red-600"/>}</div></button>)}</div></section>)}</div>}
  <RecordDrawer open={Boolean(selected)||creating} title={creating?"New case":text(selected?.subject)} subtitle={creating?"Create a minimum record, then add detail":`${text(selected?.case_number)} · ${text(selected?.source)||"Manual"}`} status={creating?"Draft":text(selected?.status)} onClose={()=>{setCreating(false);setSelected(null)}} rail={creating?<ContextBlock title="Minimum record"><p className="text-slate-600">A subject is enough to start. Routing, relationships, and SLA detail can be added now or later.</p></ContextBlock>:rail}>
   <form onSubmit={saveCase} className="grid gap-6"><section><h3 className="font-semibold">Overview</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm font-medium md:col-span-2">Subject<Input name="subject" defaultValue={text(selected?.subject)} required/></label><label className="grid gap-1 text-sm font-medium">Priority<select name="priority" defaultValue={text(selected?.priority)||"Normal"} className={fieldClass}><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select></label><label className="grid gap-1 text-sm font-medium">Status<select name="status" defaultValue={text(selected?.status)||"New"} className={fieldClass}><option>New</option><option>In progress</option><option>Waiting on customer</option><option>Escalated</option><option>Resolved</option><option>Closed</option></select></label><label className="grid gap-1 text-sm font-medium">Queue<Input name="queue" defaultValue={text(selected?.queue)||"General"}/></label><label className="grid gap-1 text-sm font-medium">Owner<Input name="owner" defaultValue={text(selected?.owner)||data.account.email}/></label><label className="grid gap-1 text-sm font-medium md:col-span-2">Description<Textarea name="description" defaultValue={text(selected?.description)} rows={5}/></label></div></section><section><h3 className="font-semibold">Relationships</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Contact<select name="contactId" defaultValue={text(selected?.contact_id)} className={fieldClass}><option value="">Unlinked</option>{data.contacts.map(item=><option key={text(item.id)} value={text(item.id)}>{text(item.name)}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Company<select name="companyId" defaultValue={text(selected?.company_id)} className={fieldClass}><option value="">Unlinked</option>{data.companies.map(item=><option key={text(item.id)} value={text(item.id)}>{text(item.name)}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Deal<select name="dealId" defaultValue={text(selected?.deal_id)} className={fieldClass}><option value="">Unlinked</option>{data.deals.map(item=><option key={text(item.id)} value={text(item.id)}>{text(item.name)}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Product<Input name="product" defaultValue={text(selected?.product)}/></label></div>{selected&&<p className="mt-3 text-sm text-slate-500">Linked to {text(selectedContact?.name)||"no contact"}, {text(selectedCompany?.name)||"no company"}, and {text(selectedDeal?.name)||"no deal"}.</p>}</section><div className="sticky bottom-0 flex justify-end gap-2 border-t bg-white py-4"><Button type="button" variant="outline" onClick={()=>{setCreating(false);setSelected(null)}}>Cancel</Button><Button disabled={busy}>{busy?"Saving...":"Save case"}</Button></div></form>
   {selected&&<section className="mt-7 border-t pt-6"><h3 className="font-semibold">Timeline and internal notes</h3><div className="mt-3 grid gap-2">{notes.map(note=><div key={text(note.id)} className="rounded-md border p-3 text-sm"><div className="flex justify-between gap-3"><strong>{note.internal?"Internal note":"Customer update"}</strong><span className="text-xs text-slate-400">{text(note.author)}</span></div><p className="mt-1 text-slate-600">{text(note.body)}</p></div>)}{notes.length===0&&<p className="text-sm text-slate-500">No notes yet.</p>}</div><form onSubmit={addNote} className="mt-3 flex gap-2"><Textarea name="body" rows={2} placeholder="Add an internal note" required/><Button disabled={busy}>Add note</Button></form></section>}
  </RecordDrawer>
 </div>
}

function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <section className="rounded-lg border bg-white p-4"><div className="flex items-center gap-2 text-sm text-slate-500">{icon}{label}</div><strong className="mt-2 block text-2xl">{value}</strong></section>}
function Priority({value}:{value:string}){return <Badge variant={value==="Urgent"?"destructive":"outline"}>{value||"Normal"}</Badge>}
