"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, Inbox, MailPlus, Paperclip, Reply, Send, TicketPlus, UserRoundCheck, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type Row=Record<string,unknown>;
type Data={account:{email:string};messages:Row[];contacts:Row[];companies:Row[];deals:Row[];documents:Row[];overdue:number;identity:{fromName:string;fromEmail:string;replyToEmail:string}};
const text=(value:unknown)=>String(value??"");
const when=(value:unknown)=>value?new Date(text(value)).toLocaleString():"—";
const Panel=({children,className=""}:{children:React.ReactNode;className?:string})=><section className={`rounded-2xl border bg-white shadow-[0_1px_2px_rgba(15,23,42,.03)] ${className}`}>{children}</section>;
const statusStyle=(value:string)=>value==="Overdue"?"destructive":value==="Resolved"?"secondary":"default";

export function SharedInboxWorkspace(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(""),[selectedKey,setSelectedKey]=useState(""),[compose,setCompose]=useState<{reply?:Row}|null>(null);
 const load=useCallback(async()=>{const response=await fetch("/api/shared-inbox",{cache:"no-store"}),body=await response.json() as Data&{error?:string};if(!response.ok)throw new Error(body.error||"Shared inbox could not load.");setData(body);setError("")},[]);
 useEffect(()=>{void load().catch(reason=>setError(reason instanceof Error?reason.message:"Shared inbox could not load."))},[load]);
 const run=async(action:string,payload:Row={},message="Saved")=>{setBusy(action);setError("");try{const response=await fetch("/api/shared-inbox",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,...payload})}),body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||"The inbox change could not be saved.");await load();setNotice(message);window.setTimeout(()=>setNotice(""),2800);return true}catch(reason){setError(reason instanceof Error?reason.message:"The inbox change could not be saved.");return false}finally{setBusy("")}};
 const createCase=async(message:Row)=>{setBusy("case");setError("");try{const response=await fetch("/api/platform-expansion",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"saveCase",source:"Email",subject:text(message.subject)||"Customer email",description:text(message.body),priority:text(message.status)==="Overdue"?"High":"Normal",queue:"Customer support",owner:text(message.owner||data?.account.email),contactId:message.contact_id||null,companyId:message.company_id||null,dealId:message.deal_id||null,inboxMessageId:message.id})}),body=await response.json() as{error?:string;caseNumber?:string};if(!response.ok)throw new Error(body.error||"The service case could not be created.");setNotice(`Case ${body.caseNumber} created from this email.`);window.setTimeout(()=>setNotice(""),3200)}catch(reason){setError(reason instanceof Error?reason.message:"The service case could not be created.")}finally{setBusy("")}};
 const threads=useMemo(()=>{if(!data)return [] as {key:string;messages:Row[];latest:Row}[];const grouped=new Map<string,Row[]>();for(const message of data.messages){const key=text(message.thread_key||message.id);grouped.set(key,[...(grouped.get(key)||[]),message])}return Array.from(grouped.entries()).map(([key,messages])=>({key,messages:messages.sort((a,b)=>new Date(text(a.occurred_at)).getTime()-new Date(text(b.occurred_at)).getTime()),latest:messages.slice().sort((a,b)=>new Date(text(b.occurred_at)).getTime()-new Date(text(a.occurred_at)).getTime())[0]})).sort((a,b)=>new Date(text(b.latest.occurred_at)).getTime()-new Date(text(a.latest.occurred_at)).getTime())},[data]);
 const selected=threads.find(thread=>thread.key===selectedKey)||null;
 const uploadFiles=async(files:FileList,contactId:number,companyId:number,dealId:number)=>{const entityType=dealId?"deal":companyId?"company":"contact",entityId=dealId||companyId||contactId;if(!entityId)throw new Error("Choose a CRM record before attaching files.");const ids:string[]=[];for(const file of Array.from(files)){const form=new FormData();form.set("entityType",entityType);form.set("entityId",String(entityId));form.set("title",file.name);form.set("category","Correspondence");form.set("file",file);const response=await fetch("/api/documents",{method:"POST",body:form}),body=await response.json() as {id?:string;error?:string};if(!response.ok||!body.id)throw new Error(body.error||`Could not save ${file.name}.`);ids.push(body.id)}return ids};
 if(!data)return <Panel className="p-6 text-sm text-slate-500">{error||"Loading shared inbox…"}</Panel>;
 return <>{error&&<div className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{notice&&<div className="mb-4 flex items-center gap-2 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><Check size={16}/>{notice}</div>}
  <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-1 text-sm font-semibold text-[#3968ff]">Customer conversations</div><h1 className="text-2xl font-semibold tracking-[-.025em] md:text-[30px]">Shared inbox</h1><p className="mt-1 text-sm text-slate-500">Send, reply, associate threads, and keep client files with the right record.</p></div><Button onClick={()=>setCompose({})}><MailPlus size={16}/>New email</Button></div>
  {data.overdue>0&&<div className="mb-5 flex items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle size={17}/><strong>{data.overdue}</strong> inbound {data.overdue===1?"email is":"emails are"} beyond the response target.</div>}
  <div className="grid gap-6 xl:grid-cols-[.86fr_1.14fr]"><Panel className="max-h-[72vh] overflow-y-auto"><div className="border-b p-5"><div className="flex items-center gap-2"><Inbox size={18}/><h2 className="font-semibold">Conversations</h2></div><p className="mt-1 text-sm text-slate-500">Threads are grouped automatically by reply chain and subject.</p></div>{threads.map(thread=>{const message=thread.latest;return <button key={thread.key} onClick={()=>setSelectedKey(thread.key)} className={`w-full border-b p-4 text-left last:border-0 ${selectedKey===thread.key?"bg-[#f2f5ff]":"hover:bg-slate-50"}`}><div className="flex items-center justify-between gap-3"><strong className="truncate">{text(message.subject)||"Untitled email"}</strong><Badge variant={statusStyle(text(message.status)) as "default"}>{text(message.status)}</Badge></div><p className="mt-1 truncate text-sm text-slate-600">{text(message.direction)==="Outbound"?`To ${text(message.to_emails).replace(/[\[\]"]/g,"")}`:text(message.from_name||message.from_email)}</p><div className="mt-1 flex justify-between gap-2 text-xs text-slate-500"><span>{thread.messages.length} {thread.messages.length===1?"message":"messages"}</span><span>{when(message.occurred_at)}</span></div></button>})}{!threads.length&&<div className="p-8 text-center text-sm text-slate-500">No customer emails yet. Send one from ClientRecord or post inbound mail to the capture endpoint.</div>}</Panel>
   <Panel className="min-h-[520px] overflow-hidden">{selected?<><div className="flex flex-wrap items-start justify-between gap-3 border-b p-5"><div><h2 className="font-semibold">{text(selected.latest.subject)||"Untitled email"}</h2><p className="mt-1 text-sm text-slate-500">{text(selected.latest.deal_name||selected.latest.company_name||"Unassigned conversation")}</p></div><Button size="sm" onClick={()=>setCompose({reply:selected.latest})}><Reply size={15}/>Reply</Button></div><div className="max-h-[510px] space-y-4 overflow-y-auto p-5">{selected.messages.map(message=><article key={text(message.id)} className={`max-w-[92%] rounded-2xl p-4 text-sm ${text(message.direction)==="Outbound"?"ml-auto bg-[#3156c9] text-white":"bg-slate-100 text-slate-900"}`}><div className="mb-2 flex flex-wrap justify-between gap-3 text-xs opacity-75"><span>{text(message.direction)==="Outbound"?`You → ${text(message.to_emails).replace(/[\[\]"]/g,"")}`:text(message.from_name||message.from_email)}</span><span>{when(message.occurred_at)}</span></div><div className="whitespace-pre-wrap leading-6">{text(message.body)||"No message body supplied."}</div>{text(message.attachments_json)!=="[]"&&<div className="mt-3 text-xs opacity-80">Attachments: {text(message.attachments_json)}</div>}</article>)}</div><div className="border-t p-4"><div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>setCompose({reply:selected.latest})}><Reply size={15}/>Reply</Button><Button size="sm" variant="outline" disabled={busy==="resolve"} onClick={()=>void run("resolve",{id:selected.latest.id},"Conversation resolved")}>Resolve</Button>{!selected.latest.contact_id&&<Button size="sm" variant="outline" onClick={()=>setSelectedKey(selected.key)}>Assign record below</Button>}</div>{!selected.latest.contact_id&&<AssignForm data={data} message={selected.latest} busy={Boolean(busy)} onSave={payload=>void run("assign",payload,"Email assigned to CRM records")}/>}</div></>:<div className="grid h-full place-items-center p-10 text-center text-sm text-slate-500">Select a conversation to read, reply, and associate it with a client or deal.</div>}</Panel></div>
  {selected&&text(selected.latest.direction)==="Inbound"&&<div className="mt-4 flex justify-end"><Button variant="outline" disabled={busy==="case"} onClick={()=>void createCase(selected.latest)}><TicketPlus size={16}/>Create service case from selected email</Button></div>}
  {compose&&<ComposeDialog data={data} reply={compose.reply} busy={Boolean(busy)} close={()=>setCompose(null)} send={async form=>{const files=form.get("files");const contactId=Number(form.get("contactId"))||0,companyId=Number(form.get("companyId"))||0,dealId=Number(form.get("dealId"))||0;const documentIds=files instanceof FileList&&files.length?await uploadFiles(files,contactId,companyId,dealId):[];const done=await run(compose.reply?"reply":"send",{to:form.get("to"),subject:form.get("subject"),body:form.get("body"),contactId:contactId||null,companyId:companyId||null,dealId:dealId||null,owner:form.get("owner"),responseDueHours:form.get("responseDueHours"),replyToMessageId:compose.reply?.id,attachmentDocumentIds:documentIds},compose.reply?"Reply sent and conversation updated":"Email sent from ClientRecord");if(done)setCompose(null)}}/>}
 </>;
}

function AssignForm({data,message,busy,onSave}:{data:Data;message:Row;busy:boolean;onSave:(payload:Row)=>void}){return <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);onSave({id:message.id,contactId:Number(form.get("contactId")),companyId:Number(form.get("companyId"))||null,dealId:Number(form.get("dealId"))||null,owner:form.get("owner")})}}><select required name="contactId" className="h-10 rounded-md border bg-white px-3"><option value="">Choose contact</option>{data.contacts.map(contact=><option key={text(contact.id)} value={text(contact.id)}>{text(contact.name)} · {text(contact.email)}</option>)}</select><select name="companyId" className="h-10 rounded-md border bg-white px-3"><option value="">Company (optional)</option>{data.companies.map(company=><option key={text(company.id)} value={text(company.id)}>{text(company.name)}</option>)}</select><select name="dealId" className="h-10 rounded-md border bg-white px-3 sm:col-span-2"><option value="">Deal (optional)</option>{data.deals.map(deal=><option key={text(deal.id)} value={text(deal.id)}>{text(deal.name)} · {text(deal.company)}</option>)}</select><Input name="owner" defaultValue={text(message.owner||data.account.email)} placeholder="Owner"/><Button disabled={busy}><UserRoundCheck size={16}/>Assign email</Button></form>}

function ComposeDialog({data,reply,busy,close,send}:{data:Data;reply?:Row;busy:boolean;close:()=>void;send:(form:FormData)=>Promise<void>}){const replyContact=text(reply?.contact_id||""),replyCompany=text(reply?.company_id||""),replyDeal=text(reply?.deal_id||""),recipient=reply?text(reply.from_email):"",subject=reply?text(reply.subject).replace(/^re:\s*/i,""):"";return <div className="fixed inset-0 z-50 grid place-items-center bg-black/35 p-4" onClick={close}><Panel className="max-h-[94vh] w-full max-w-2xl overflow-y-auto p-6" ><form onClick={event=>event.stopPropagation()} className="grid gap-4" onSubmit={event=>{event.preventDefault();void send(new FormData(event.currentTarget)).catch(reason=>window.alert(reason instanceof Error?reason.message:"Could not save attachment."))}}><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">{reply?"Reply from ClientRecord":"New email"}</h2><p className="mt-1 text-sm text-slate-500">From {data.identity.fromName?`${data.identity.fromName} <${data.identity.fromEmail}>`:data.identity.fromEmail||"your verified sending identity"}</p></div><Button type="button" variant="ghost" onClick={close}><X size={18}/></Button></div><Input required name="to" type="email" defaultValue={recipient} placeholder="Recipient email"/><Input required name="subject" defaultValue={subject} placeholder="Subject"/><Textarea required name="body" rows={9} placeholder="Write a helpful, personal message…"/><div className="grid gap-3 sm:grid-cols-2"><select required name="contactId" defaultValue={replyContact} className="h-10 rounded-md border bg-white px-3"><option value="">Contact</option>{data.contacts.map(contact=><option key={text(contact.id)} value={text(contact.id)}>{text(contact.name)} · {text(contact.email)}</option>)}</select><select name="companyId" defaultValue={replyCompany} className="h-10 rounded-md border bg-white px-3"><option value="">Company (optional)</option>{data.companies.map(company=><option key={text(company.id)} value={text(company.id)}>{text(company.name)}</option>)}</select><select name="dealId" defaultValue={replyDeal} className="h-10 rounded-md border bg-white px-3 sm:col-span-2"><option value="">Deal (automatic match if blank)</option>{data.deals.map(deal=><option key={text(deal.id)} value={text(deal.id)}>{text(deal.name)} · {text(deal.company)}</option>)}</select><Input name="owner" defaultValue={data.account.email} placeholder="Owner"/><Input name="responseDueHours" type="number" min="1" max="240" defaultValue="48" placeholder="Reply target hours"/></div><label className="flex cursor-pointer items-center gap-2 rounded-lg border border-dashed p-3 text-sm text-slate-600"><Paperclip size={16}/><span>Attach files — saved securely to this client record and included with the email</span><input name="files" type="file" multiple className="sr-only"/></label><Button disabled={busy}><Send size={16}/>{reply?"Send reply":"Send email"}</Button></form></Panel></div>}
