"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, Bell, CalendarDays, Check, ChevronRight, RefreshCw, Sparkles, TrendingUp } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

type Row=Record<string,unknown>;
type TodayData={account:{email:string;role:string};today:{tasks:Row[];dealTasks:Row[];notifications:Row[];hotAccounts:Row[];stalledDeals:Row[];upcomingMeetings:Row[]};reviewItems:Row[];cases:Row[]};

function Panel({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`console-panel ${className}`}>{children}</section>}
function Empty({children}:{children:string}){return <div className="p-6 text-center text-sm text-slate-500">{children}</div>}

export function TodayConsole(){
 const[data,setData]=useState<TodayData|null>(null),[error,setError]=useState(""),[selected,setSelected]=useState<string[]>([]),[snoozed,setSnoozed]=useState<string[]>([]);
 const load=useCallback(async()=>{try{const[operations,review,service]=await Promise.all([fetch("/api/operations",{cache:"no-store"}),fetch("/api/communication-review",{cache:"no-store"}),fetch("/api/platform-expansion",{cache:"no-store"})]),body=await operations.json() as TodayData&{error?:string},reviewBody=await review.json() as{items?:Row[]},serviceBody=await service.json() as{cases?:Row[]};if(!operations.ok)throw new Error(body.error);setData({...body,reviewItems:review.ok?reviewBody.items||[]:[],cases:service.ok?(serviceBody.cases||[]).filter(item=>!["Resolved","Closed"].includes(String(item.status))):[]});setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Today is temporarily unavailable.")}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const complete=async(row:Row)=>{if(row.taskType==="review"){window.dispatchEvent(new CustomEvent("crm:navigate",{detail:"communication-review"}));return}if(row.taskType==="case"){window.dispatchEvent(new CustomEvent("crm:navigate",{detail:"service"}));return}const deal=row.taskType==="deal";await fetch(deal?"/api/sales":"/api/crm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(deal?{action:"toggleDealTask",id:row.id,completed:true}:{action:"completeTask",id:row.id})});await load()};
 const markAlert=async(id:unknown)=>{await fetch("/api/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"markNotification",id})});await load()};
 const today=new Date().toISOString().slice(0,10);
 const queue=useMemo(()=>data?[...data.today.tasks.map(item=>({...item,taskType:"contact",queueLabel:"Task"})),...data.today.dealTasks.map(item=>({...item,taskType:"deal",queueLabel:"Deal"})),...data.reviewItems.map(item=>({...item,id:`review-${item.id}`,title:item.subject||"Review communication associations",contactName:item.sender_name||item.sender_email,dueDate:item.created_at,taskType:"review",queueLabel:"Review"})),...data.cases.map(item=>({...item,id:`case-${item.id}`,title:item.subject,contactName:item.company_name||item.contact_name,dueDate:item.resolution_due_at||item.created_at,taskType:"case",queueLabel:String(item.priority||"Case")}))].filter(item=>!snoozed.includes(String(item.id))).sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate))):[],[data,snoozed]);
 if(!data)return <Panel className="p-6">{error||"Loading today’s work…"}</Panel>;
 const t=data.today,overdue=queue.filter(item=>String(item.dueDate)<today),recommendation=overdue[0]||t.stalledDeals[0]||t.hotAccounts[0];
 return <>
  <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#3156c9]">Daily execution</p><h1 className="mt-1 text-3xl font-semibold">Today</h1><p className="mt-2 text-sm text-slate-500">A focused queue of commitments, risk, and buying signals.</p></div><Button variant="outline" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</Button></div>
  {error&&<div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <div className="console-kpis mb-5"><button className="console-kpi text-left"><span>Due and overdue</span><strong>{queue.filter(item=>String(item.dueDate)<=today).length}</strong><small>{overdue.length} past due</small></button><button className="console-kpi text-left"><span>Revenue risk</span><strong>{t.stalledDeals.length}</strong><small>stalled deals</small></button><button className="console-kpi text-left"><span>Account signals</span><strong>{t.hotAccounts.length}</strong><small>high-intent accounts</small></button><button className="console-kpi text-left"><span>Unread alerts</span><strong>{t.notifications.length}</strong><small>owner notifications</small></button></div>
  <div className="mb-3 flex min-h-10 flex-wrap items-center justify-between gap-3 rounded-lg border bg-white px-3 py-2 text-xs"><label className="flex items-center gap-2"><input type="checkbox" checked={queue.length>0&&selected.length===queue.length} onChange={event=>setSelected(event.target.checked?queue.map(item=>String(item.id)):[])}/>Select visible work</label><div className="flex items-center gap-2"><span className="text-slate-500">{selected.length} selected</span><Button size="sm" variant="outline" disabled={!selected.length} onClick={()=>{setSnoozed(current=>[...current,...selected]);setSelected([])}}>Snooze</Button><Button size="sm" variant="ghost" disabled={!selected.length} onClick={()=>setSelected([])}>Clear</Button></div></div>
  <div className="grid gap-5 2xl:grid-cols-[minmax(0,1.45fr)_minmax(280px,.8fr)_280px]">
   <Panel className="min-w-0 overflow-hidden"><div className="panel-heading"><div><h2>Next actions</h2><p>Contact and deal commitments, ordered by due date.</p></div><Badge variant="secondary">{queue.length} open</Badge></div>{queue.map((item,index)=><div key={`${item.taskType}-${item.id}-${index}`} className="action-row"><button onClick={()=>void complete(item)} className="check-action" aria-label={`Complete ${String(item.title)}`}><Check size={14}/></button><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{String(item.title)}</strong><span className="block truncate text-xs text-slate-500">{String(item.contactName||item.dealName||item.company||"")}</span></div><span className={`status-text ${String(item.dueDate)<today?"status-danger":""}`}>{String(item.dueDate)<today?"Overdue":String(item.dueDate)===today?"Today":String(item.dueDate)}</span><ChevronRight size={15} className="text-slate-300"/></div>)}{!queue.length&&<Empty>Nothing is due. Your queue is clear.</Empty>}</Panel>
   <div className="grid content-start gap-5"><Panel className="overflow-hidden"><div className="panel-heading"><div><h2>Revenue risk</h2><p>Deals beyond their stage limit.</p></div></div>{t.stalledDeals.slice(0,5).map(item=><div key={String(item.id)} className="signal-row"><AlertTriangle size={16} className="text-amber-600"/><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{String(item.name)}</strong><span className="block truncate text-xs text-slate-500">{String(item.company)} · {String(item.stage)}</span></div><span className="tabular text-xs font-semibold">{String(item.days)}d</span></div>)}{!t.stalledDeals.length&&<Empty>No deals exceed the stage limit.</Empty>}</Panel><Panel className="overflow-hidden"><div className="panel-heading"><div><h2>Account signals</h2><p>Highest combined fit and intent.</p></div></div>{t.hotAccounts.slice(0,5).map(item=><div key={String(item.id)} className="signal-row"><TrendingUp size={16} className="text-emerald-600"/><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{String(item.name)}</strong><span className="block truncate text-xs text-slate-500">{String(item.owner||"Unassigned")}</span></div><Badge variant="secondary">{Number(item.fitScore)+Number(item.intentScore)}</Badge></div>)}{!t.hotAccounts.length&&<Empty>No hot accounts yet.</Empty>}</Panel></div>
   <aside className="grid content-start gap-5 2xl:sticky 2xl:top-24 2xl:self-start"><Panel className="overflow-hidden"><div className="panel-heading"><div><h2>Recommended</h2><p>Best next move from current CRM evidence.</p></div><Sparkles size={16} className="text-[#3968ff]"/></div><div className="p-4"><strong className="text-sm">{recommendation?String(recommendation.title||recommendation.name):"Review the pipeline"}</strong><p className="mt-2 text-xs leading-5 text-slate-500">{recommendation?overdue.length?"This commitment is overdue. Resolve it before lower-priority work.":t.stalledDeals.length?"This deal has exceeded its stage limit. Confirm the next action or update the forecast.":"This account has the strongest current fit and intent signal.":"There are no urgent exceptions. Use the pipeline review to prepare the next move."}</p></div></Panel><Panel className="overflow-hidden"><div className="panel-heading"><div><h2>Owner alerts</h2><p>Click to acknowledge.</p></div><Bell size={16}/></div>{t.notifications.slice(0,4).map(item=><button key={String(item.id)} onClick={()=>void markAlert(item.id)} className="signal-row w-full text-left"><Bell size={15} className="text-[#3968ff]"/><span className="min-w-0 flex-1"><strong className="block truncate text-xs">{String(item.title)}</strong><span className="mt-1 block text-xs leading-4 text-slate-500">{String(item.body)}</span></span><Check size={14} className="text-slate-300"/></button>)}{!t.notifications.length&&<Empty>No unread alerts.</Empty>}</Panel><Panel className="overflow-hidden"><div className="panel-heading"><div><h2>Meetings</h2><p>Next seven days.</p></div><CalendarDays size={16}/></div>{t.upcomingMeetings.slice(0,3).map(item=><div key={String(item.id)} className="signal-row"><div className="min-w-0"><strong className="block text-xs">{String(item.note)}</strong><span className="mt-1 block text-xs text-slate-500">{String(item.contactName)} · {new Date(String(item.happenedAt)).toLocaleDateString()}</span></div></div>)}{!t.upcomingMeetings.length&&<Empty>No upcoming meetings.</Empty>}</Panel></aside>
  </div>
 </>;
}
