"use client";

import { AlertCircle, Check, ChevronLeft, ChevronRight, Columns3, List, PanelRightClose, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";

export type WorkspaceMode="table"|"board";
export type WorkspaceDensity="comfortable"|"compact";

export function ViewBar({views,activeView,onView,mode,onMode,density,onDensity,children}:{views:string[];activeView:string;onView:(value:string)=>void;mode:WorkspaceMode;onMode:(value:WorkspaceMode)=>void;density:WorkspaceDensity;onDensity:(value:WorkspaceDensity)=>void;children?:React.ReactNode}){
 return <div className="workspace-toolbar mb-4"><div className="flex min-w-0 flex-1 gap-1 overflow-x-auto">{views.map(view=><button key={view} className={`view-chip ${activeView===view?"view-chip-active":""}`} onClick={()=>onView(view)}>{view}</button>)}</div>{children}<div className="flex shrink-0 items-center gap-1 border-l pl-2"><button className={`icon-control ${mode==="table"?"icon-control-active":""}`} title="Table view" onClick={()=>onMode("table")}><List size={16}/></button><button className={`icon-control ${mode==="board"?"icon-control-active":""}`} title="Board view" onClick={()=>onMode("board")}><Columns3 size={16}/></button><button className={`view-chip ${density==="compact"?"view-chip-active":""}`} title="Toggle density" onClick={()=>onDensity(density==="compact"?"comfortable":"compact")}>{density==="compact"?"Compact":"Roomy"}</button></div></div>;
}

export function RecordDrawer({open,title,subtitle,status,onClose,children,rail}:{open:boolean;title:string;subtitle?:string;status?:string;onClose:()=>void;children:React.ReactNode;rail:React.ReactNode}){
 if(!open)return null;
 return <div className="fixed inset-0 z-50 bg-slate-950/25" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><aside className="absolute inset-y-0 right-0 flex w-full max-w-6xl flex-col bg-[#f2f3f5] shadow-2xl"><header className="sticky top-0 z-10 flex min-h-[84px] items-center gap-4 border-b bg-white px-5 py-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-md bg-[#2f62d6] text-sm font-bold text-white">{title.slice(0,2).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="text-xs font-medium text-slate-500">Record</div><div className="flex items-center gap-2"><h2 className="truncate text-xl font-semibold">{title}</h2>{status&&<Badge variant="secondary">{status}</Badge>}</div>{subtitle&&<p className="mt-0.5 truncate text-sm text-slate-500">{subtitle}</p>}</div><Button size="icon" variant="ghost" title="Close record" onClick={onClose}><PanelRightClose size={19}/></Button></header><div className="grid min-h-0 flex-1 gap-3 overflow-y-auto p-3 xl:grid-cols-[minmax(0,1fr)_300px]"><main className="min-w-0 rounded-lg border bg-white p-5">{children}</main><aside className="grid content-start gap-3">{rail}</aside></div></aside></div>;
}

export function ContextBlock({title,children,icon}:{title:string;children:React.ReactNode;icon?:React.ReactNode}){return <section className="overflow-hidden rounded-lg border bg-white"><div className="flex min-h-9 items-center gap-2 border-b bg-slate-50 px-3 text-xs font-semibold text-slate-600">{icon}{title}</div><div className="p-4 text-sm">{children}</div></section>}

export function AIEvidence({confidence,evidence,changes,onAccept,onReject,onNoUpdate}:{confidence:number;evidence:string[];changes:string[];onAccept?:()=>void;onReject?:()=>void;onNoUpdate?:()=>void}){return <ContextBlock title="AI evidence" icon={<Sparkles size={14}/>}><div className="flex items-center justify-between"><strong>Suggested update</strong><Badge variant="outline">{confidence}% confidence</Badge></div><p className="mt-2 text-xs text-slate-500">Proposal only. CRM data is unchanged until accepted.</p>{changes.length>0&&<ul className="mt-3 grid gap-1 text-xs">{changes.map(item=><li key={item}>• {item}</li>)}</ul>}{evidence.length>0&&<details className="mt-3"><summary className="cursor-pointer text-xs font-semibold">View source evidence</summary><ul className="mt-2 grid gap-1 text-xs text-slate-500">{evidence.map(item=><li key={item}>{item}</li>)}</ul></details>}<div className="mt-4 flex flex-wrap gap-2">{onAccept&&<Button size="sm" onClick={onAccept}><Check size={14}/>Accept selected</Button>}{onReject&&<Button size="sm" variant="outline" onClick={onReject}>Reject</Button>}{onNoUpdate&&<Button size="sm" variant="ghost" onClick={onNoUpdate}>No update</Button>}</div></ContextBlock>}

export function WorkspaceEmpty({title,detail,action}:{title:string;detail:string;action?:React.ReactNode}){return <div className="grid min-h-56 place-items-center p-8 text-center"><div><div className="mx-auto grid h-10 w-10 place-items-center rounded-lg bg-slate-100 text-slate-400"><List size={18}/></div><strong className="mt-3 block text-sm">{title}</strong><p className="mx-auto mt-1 max-w-md text-sm text-slate-500">{detail}</p>{action&&<div className="mt-4">{action}</div>}</div></div>}
export function WorkspaceError({message,retry}:{message:string;retry:()=>void}){return <div className="flex items-center gap-3 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertCircle size={18}/><span className="flex-1">{message} No unsaved record changes were committed.</span><Button size="sm" variant="outline" onClick={retry}>Retry</Button></div>}
export function Pagination({page,pages,onPage}:{page:number;pages:number;onPage:(page:number)=>void}){return <div className="flex items-center justify-between border-t px-4 py-3 text-xs text-slate-500"><span>Page {page} of {Math.max(1,pages)}</span><div className="flex gap-1"><Button size="icon" variant="ghost" disabled={page<=1} onClick={()=>onPage(page-1)}><ChevronLeft size={16}/></Button><Button size="icon" variant="ghost" disabled={page>=pages} onClick={()=>onPage(page+1)}><ChevronRight size={16}/></Button></div></div>}
export function Panel({children,className="",rounded="lg"}:{children:React.ReactNode;className?:string;rounded?:"lg"|"2xl"}){return <section className={`${rounded==="2xl"?"rounded-2xl":"rounded-lg"} border bg-white shadow-[0_1px_2px_rgba(15,23,42,.03)] ${className}`}>{children}</section>}
export function Heading({eyebrow,title,detail,action}:{eyebrow:string;title:string;detail?:string;action?:React.ReactNode}){return <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-1 text-sm font-semibold text-[#3968ff]">{eyebrow}</div><h1 className="text-2xl font-semibold tracking-[-.025em] md:text-[30px]">{title}</h1>{detail&&<p className="mt-1 max-w-3xl text-sm text-slate-500">{detail}</p>}</div>{action}</div>}
export function Field({label,className="",...props}:{label:string;className?:string}&React.InputHTMLAttributes<HTMLInputElement>){return <label className={`grid gap-1 text-sm font-medium ${className}`}>{label}<Input {...props}/></label>}
