type Row=Record<string,unknown>;
export type AnalysisFinding={kind:string;title:string;detail:string;severity:"Low"|"Medium"|"High";evidence:string[]};
export type WorkspaceAnalysis={headline:string;summary:string;findings:AnalysisFinding[];recommendations:string[];confidence:"Low"|"Medium"|"High";explanation:string;dataGaps:string[];records?:Row[]};
const clean=(value:unknown,max=3000)=>String(value??"").trim().slice(0,max);
const list=(value:unknown,max=16)=>Array.isArray(value)?value.map(item=>clean(item,2000)).filter(Boolean).slice(0,max):[];
const words=(value:unknown)=>clean(value,12000).toLowerCase();
const evidence=(items:unknown[])=>items.map(item=>clean(item,400)).filter(Boolean).slice(0,4);
const severity=(value:unknown)=>{const item=clean(value,20);return item==="High"||item==="Low"?item:"Medium" as const};
export function normalizeWorkspaceAnalysis(value:unknown):WorkspaceAnalysis{
 const row=(value&&typeof value==="object"?value:{}) as Row,findings=Array.isArray(row.findings)?row.findings.map(item=>{const itemRow=(item&&typeof item==="object"?item:{}) as Row;return {kind:clean(itemRow.kind,80)||"Finding",title:clean(itemRow.title,240)||"CRM finding",detail:clean(itemRow.detail,2000),severity:severity(itemRow.severity),evidence:list(itemRow.evidence,6)}}).filter(item=>item.title).slice(0,20):[];
 const confidence=clean(row.confidence,20);return {headline:clean(row.headline,300)||"CRM analysis",summary:clean(row.summary,4000),findings,recommendations:list(row.recommendations,10),confidence:confidence==="High"||confidence==="Medium"?confidence:"Low",explanation:clean(row.explanation,3000),dataGaps:list(row.dataGaps,12),records:Array.isArray(row.records)?row.records.slice(0,80).filter(item=>item&&typeof item==="object") as Row[]:undefined};
}
export function conversationAnalysis(input:{deal:Row;messages:Row[];activities:Row[];meetings:Row[]}){
 const corpus=[...input.messages.map(item=>`${item.subject||""} ${item.body||""}`),...input.activities.map(item=>`${item.subject||""} ${item.body||""} ${item.outcome||""}`),...input.meetings.map(item=>`${item.summary||""} ${item.decisions_json||""} ${item.next_steps_json||""}`)].join("\n"),lower=words(corpus),findings:AnalysisFinding[]=[];
 const add=(kind:string,title:string,detail:string,level:AnalysisFinding["severity"],terms:string[])=>{if(terms.some(term=>lower.includes(term)))findings.push({kind,title,detail,severity:level,evidence:evidence([...input.messages,...input.activities,...input.meetings].map(item=>item.subject||item.body||item.summary))});};
 add("Commitment","Customer commitment detected","Review the underlying conversation and record an owner and due date before relying on it.","Medium",["we will","i will","we'll","i'll","commit"]);
 add("Objection","Potential objection or concern","Review the cited conversation and decide whether this should become an open deal objection.","High",["concern","worried","issue","blocker","not sure","cannot","can't"]);
 add("Competitor","Competitor reference detected","Confirm whether a competitor is active and add it to the deal intelligence record if material.","Medium",["competitor","alternative","other vendor","evaluating"]);
 add("Pricing","Pricing pressure detected","Review pricing, discount, procurement, or budget language before the next commercial step.","High",["price","pricing","discount","budget","cost","expensive"]);
 add("Buying signal","Positive buying signal detected","Use the source conversation to validate timing, process, and next action.","Medium",["proposal","contract","legal","procurement","move forward","next steps"]);
 const gaps:string[]=[];if(!input.messages.length&&!input.activities.length&&!input.meetings.length)gaps.push("No linked emails, activities, or meetings are available for this deal.");if(!findings.length&&corpus)gaps.push("No structured signal terms were detected; review the raw conversation before assuming a signal.");
 return normalizeWorkspaceAnalysis({headline:`Conversation intelligence for ${clean(input.deal.name,220)||"this deal"}`,summary:`Reviewed ${input.messages.length} email${input.messages.length===1?"":"s"}, ${input.activities.length} deal activit${input.activities.length===1?"y":"ies"}, and ${input.meetings.length} meeting${input.meetings.length===1?"":"s"}. Findings are suggestions, not changes to the deal.`,findings,recommendations:findings.length?["Review each finding against the source conversation before adding it to the deal record.","Convert confirmed commitments into an owner, due date, and next step."]:["Associate emails and completed meetings with this deal to strengthen future analysis."],confidence:gaps.length?"Low":findings.length?"Medium":"Low",explanation:"This source-backed analysis classifies recorded email, activity, and meeting text. It does not infer intent beyond the recorded language.",dataGaps:gaps});
}
export function hygieneAnalysis(input:{contacts:Row[];companies:Row[];deals:Row[];duplicates:Row[]}){
 const findings:AnalysisFinding[]=[];const missingOwners=input.deals.filter(item=>!clean(item.owner,240)),noNext=input.deals.filter(item=>clean(item.status,40)==="Open"&&!clean(item.next_step,600)),passed=input.deals.filter(item=>clean(item.status,40)==="Open"&&clean(item.close_date,20)&&clean(item.close_date,20)<new Date().toISOString().slice(0,10)),incomplete=input.companies.filter(item=>!clean(item.domain,240)||!clean(item.owner,240)||!clean(item.industry,240));
 if(input.duplicates.length)findings.push({kind:"Duplicate",title:`${input.duplicates.length} possible company duplicate${input.duplicates.length===1?"":"s"}`,detail:"Match candidates by name or domain, then use the existing merge control after review.",severity:"High",evidence:input.duplicates.slice(0,4).map(item=>`${clean(item.a_name||item.aName,160)} ↔ ${clean(item.b_name||item.bName,160)}`)});
 if(missingOwners.length)findings.push({kind:"Ownership",title:`${missingOwners.length} open deal${missingOwners.length===1?"":"s"} missing an owner`,detail:"Assign an accountable owner before relying on pipeline or forecast reporting.",severity:"High",evidence:missingOwners.slice(0,5).map(item=>clean(item.name,180))});
 if(noNext.length)findings.push({kind:"Next step",title:`${noNext.length} open deal${noNext.length===1?"":"s"} without a next step`,detail:"Record a specific customer-facing action, owner, and date.",severity:"Medium",evidence:noNext.slice(0,5).map(item=>clean(item.name,180))});
 if(passed.length)findings.push({kind:"Close date",title:`${passed.length} passed close date${passed.length===1?"":"s"}`,detail:"Update the close date or close the deal with a recorded reason.",severity:"High",evidence:passed.slice(0,5).map(item=>`${clean(item.name,180)} · ${clean(item.close_date,20)}`)});
 if(incomplete.length)findings.push({kind:"Company completeness",title:`${incomplete.length} incomplete company profile${incomplete.length===1?"":"s"}`,detail:"Complete company domain, owner, and industry before using the record for routing or segmentation.",severity:"Low",evidence:incomplete.slice(0,5).map(item=>clean(item.name,180))});
 return normalizeWorkspaceAnalysis({headline:"CRM hygiene review",summary:`Reviewed ${input.contacts.length} contacts, ${input.companies.length} companies, and ${input.deals.length} deals. No records are changed automatically.`,findings,recommendations:[findings.some(item=>item.kind==="Duplicate")?"Review duplicate candidates in Cleanup before merging.":"",missingOwners.length?"Assign owners to unowned open deals.":"",noNext.length?"Record next steps on open deals before the next forecast review.":""].filter(Boolean),confidence:"High",explanation:"This review uses deterministic completeness, duplicate, ownership, date, and next-step checks across current CRM records.",dataGaps:[]});
}
export function accountPlanAnalysis(input:{company:Row;contacts:Row[];deals:Row[];signals:Row[];documents:Row[];plan:Row|null}){
 const customer=clean(input.company.name,220)||"This account",stakeholders=input.contacts.slice(0,6).map(item=>`${clean(item.first_name,80)} ${clean(item.last_name,80)}${clean(item.title,120)?` · ${clean(item.title,120)}`:""}`.trim()),open=input.deals.filter(item=>clean(item.status,30)==="Open"),risks=open.filter(item=>!clean(item.next_step,300)).map(item=>`${clean(item.name,180)} has no next step.`),gaps:string[]=[];
 if(!stakeholders.length)gaps.push("No contacts are linked to this company.");if(!input.signals.length)gaps.push("No account signals are recorded.");if(!input.documents.length)gaps.push("No client documents are linked to this company.");
 const findings:AnalysisFinding[]=[{kind:"Objectives",title:"Account objectives",detail:clean(input.plan?.objectives_json,1400)||"Confirm the customer’s business objectives, success measures, and executive priorities.",severity:"Medium",evidence:[customer]},{kind:"Stakeholder coverage",title:`${stakeholders.length} known stakeholder${stakeholders.length===1?"":"s"}`,detail:stakeholders.join("; ")||"Add customer contacts and assign their relationship roles.",severity:stakeholders.length<2?"High":"Low",evidence:stakeholders.slice(0,4)},{kind:"Whitespace",title:"Expansion and renewal whitespace",detail:`${open.length} open commercial opportunity${open.length===1?"":"ies"} and ${input.signals.length} recorded account signal${input.signals.length===1?"":"s"}.`,severity:"Medium",evidence:open.slice(0,4).map(item=>clean(item.name,180))}];
 if(risks.length)findings.push({kind:"Risk",title:"Account-plan risks",detail:risks.join(" "),severity:"High",evidence:risks});
 return normalizeWorkspaceAnalysis({headline:`Living account plan: ${customer}`,summary:"A source-backed account plan that brings together account context, contacts, deals, signals, documents, and customer-success data. Review and turn confirmed items into the formal account plan.",findings,recommendations:["Confirm the account objectives and executive sponsor.",stakeholders.length<2?"Add and role-map more stakeholders.":"",open.length?"Review open opportunities and their next executive touchpoint.":""].filter(Boolean),confidence:gaps.length>1?"Low":"Medium",explanation:"This draft uses only records associated with the selected company. It does not add objectives, relationship claims, or expansion opportunities that are not in the CRM.",dataGaps:gaps});
}
export function negotiationAnalysis(input:{deal:Row;proposals:Row[];lineItems:Row[];insights:Row[];documents:Row[]}){
 const latest=input.proposals[0],previous=input.proposals[1],findings:AnalysisFinding[]=[];if(latest)findings.push({kind:"Proposal",title:`Latest proposal: ${clean(latest.title,220)||"Untitled"}`,detail:`Status: ${clean(latest.status,80)||"Draft"}. Amount: $${(Number(latest.amount||0)/100).toLocaleString("en-US")}.`,severity:clean(latest.status,80)==="Expired"?"High":"Low",evidence:[clean(latest.updated_at||latest.created_at,80)]});
 if(latest&&previous&&Number(latest.amount||0)<Number(previous.amount||0))findings.push({kind:"Concession",title:"Commercial concession detected",detail:`Latest proposal is $${((Number(previous.amount||0)-Number(latest.amount||0))/100).toLocaleString("en-US")} below the previous version. Confirm the reason and approval path.`,severity:"High",evidence:[clean(previous.title,180),clean(latest.title,180)]});
 const discounts=input.lineItems.filter(item=>Number(item.discount_percent||0)>0);if(discounts.length)findings.push({kind:"Discount",title:`${discounts.length} discounted line item${discounts.length===1?"":"s"}`,detail:"Review discount authority, trade-offs, and expiry before sending the next commercial version.",severity:"Medium",evidence:discounts.slice(0,4).map(item=>`${clean(item.name,180)} · ${Number(item.discount_percent||0)}%`)});
 input.insights.filter(item=>["Risk","Objection"].includes(clean(item.kind,80))&&clean(item.status,80)!=="Resolved").slice(0,4).forEach(item=>findings.push({kind:clean(item.kind,80),title:clean(item.title,220),detail:clean(item.detail,1200),severity:severity(item.severity),evidence:[clean(item.owner,160)]}));
 const contractDocs=input.documents.filter(item=>/contract|agreement|msa|nda|order/i.test(clean(item.title||item.filename,240)));if(contractDocs.length)findings.push({kind:"Terms",title:`${contractDocs.length} contract-related document${contractDocs.length===1?"":"s"}`,detail:"Open the source document to review redlines and non-standard terms; this release identifies the document but does not claim to interpret legal language.",severity:"Medium",evidence:contractDocs.slice(0,4).map(item=>clean(item.title||item.filename,180))});
 return normalizeWorkspaceAnalysis({headline:`Proposal & negotiation brief: ${clean(input.deal.name,220)||"deal"}`,summary:"Compares recorded proposal versions and commercial context. It flags potential concessions and open objections; it does not provide legal advice or send anything.",findings,recommendations:[discounts.length?"Confirm discount approval and the give/get before the next proposal.":"",contractDocs.length?"Have the appropriate reviewer assess non-standard contract terms.":"",!latest?"Create or save a proposal before preparing a negotiation brief.":""].filter(Boolean),confidence:latest?"Medium":"Low",explanation:"This analysis uses proposal metadata and body versions, line-item discounts, open risks or objections, and document metadata. It does not interpret document text as legal advice.",dataGaps:latest?[]:["No proposal is saved against this deal."]});
}
export const workspaceAnalysisSchema={type:"object",additionalProperties:false,properties:{headline:{type:"string"},summary:{type:"string"},findings:{type:"array",items:{type:"object",additionalProperties:false,properties:{kind:{type:"string"},title:{type:"string"},detail:{type:"string"},severity:{type:"string",enum:["Low","Medium","High"]},evidence:{type:"array",items:{type:"string"}}},required:["kind","title","detail","severity","evidence"]}},recommendations:{type:"array",items:{type:"string"}},confidence:{type:"string",enum:["Low","Medium","High"]},explanation:{type:"string"},dataGaps:{type:"array",items:{type:"string"}}},required:["headline","summary","findings","recommendations","confidence","explanation","dataGaps"]} as const;
