import { env } from "cloudflare:workers";
import { audit, type CRMUser } from "@/lib/crm-auth";

type Row=Record<string,unknown>;
const clean=(value:unknown,max=8000)=>String(value??"").trim().slice(0,max);
const number=(value:unknown,min=0,max=100)=>Math.max(min,Math.min(max,Math.round(Number(value)||0)));
const id=(value:unknown)=>{const result=Number(value);if(!Number.isInteger(result)||result<1)throw new Error("Choose a valid company.");return result};
const objectives=(value:unknown)=>Array.isArray(value)?value.map(item=>clean(item,360)).filter(Boolean).slice(0,30):clean(value,8000).split(/\n|;/).map(item=>clean(item,360)).filter(Boolean).slice(0,30);
const date=(value:unknown)=>{const valueText=clean(value,32);return /^\d{4}-\d{2}-\d{2}$/.test(valueText)?valueText:null};

export async function saveCustomerSuccessPlan(input:Row,user:CRMUser){
  const companyId=id(input.companyId),company=await env.DB.prepare("SELECT id,name,owner FROM companies WHERE id=?").bind(companyId).first<Row>();if(!company)throw new Error("Company not found.");
  const now=new Date().toISOString(),existing=await env.DB.prepare("SELECT * FROM customer_success_plans WHERE company_id=?").bind(companyId).first<Row>(),owner=clean(input.owner,200)||clean(company.owner,200)||user.email,status=["Onboarding","Active","Renewing","At risk","Churned"].includes(clean(input.status,60))?clean(input.status,60):"Onboarding",healthScore=number(input.healthScore),adoptionScore=number(input.adoptionScore),churnRisk=["Low","Medium","High","Critical"].includes(clean(input.churnRisk,30))?clean(input.churnRisk,30):"Low",expansionPotential=["Unknown","None","Low","Medium","High"].includes(clean(input.expansionPotential,30))?clean(input.expansionPotential,30):"Unknown";
  const values=[owner,status,date(input.onboardingStart),date(input.onboardingTarget),healthScore,adoptionScore,date(input.renewalDate),Math.max(0,Math.round(Number(input.annualValue)||0)),expansionPotential,churnRisk,JSON.stringify(objectives(input.objectives)),clean(input.stakeholderNotes),clean(input.risks),date(input.nextExecutiveTouchpoint),clean(input.notes),now,companyId] as (string|number|null)[];
  let planId=existing?String(existing.id):crypto.randomUUID();
  if(existing)await env.DB.prepare("UPDATE customer_success_plans SET owner=?,status=?,onboarding_start=?,onboarding_target=?,health_score=?,adoption_score=?,renewal_date=?,annual_value=?,expansion_potential=?,churn_risk=?,objectives_json=?,stakeholder_notes=?,risks=?,next_executive_touchpoint=?,notes=?,updated_at=? WHERE company_id=?").bind(...values).run();
  else await env.DB.prepare("INSERT INTO customer_success_plans(id,company_id,owner,status,onboarding_start,onboarding_target,health_score,adoption_score,renewal_date,annual_value,expansion_potential,churn_risk,objectives_json,stakeholder_notes,risks,next_executive_touchpoint,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(planId,companyId,...values.slice(0,-1),now).run();
  await audit(user,existing?"customer_success.update":"customer_success.create","customer_success_plan",planId,`${existing?"Updated":"Created"} customer plan for ${company.name}`,{companyId,status,healthScore,adoptionScore,churnRisk,renewalDate:date(input.renewalDate)});
  return {id:planId,companyId};
}

export async function createRenewalDeal(planId:string,user:CRMUser){
 const plan=await env.DB.prepare("SELECT p.*,c.name AS company_name,c.primary_contact_id AS contact_id FROM customer_success_plans p JOIN companies c ON c.id=p.company_id WHERE p.id=?").bind(planId).first<Row>();if(!plan)throw new Error("Customer plan not found.");if(plan.renewal_deal_id)return {dealId:Number(plan.renewal_deal_id),existing:true};
 const now=new Date().toISOString(),renewalDate=clean(plan.renewal_date,20)||new Date(Date.now()+90*86400000).toISOString().slice(0,10),name=`${String(plan.company_name)} renewal`,created=await env.DB.prepare("INSERT INTO deals(pipeline_key,stage_key,stage_entered_at,name,company,company_id,contact_id,stage,owner,value,probability,next_step,close_date,lead_source,status,campaign,partner,forecast_category,created_at,updated_at) VALUES ('renewals','renewal-due',?,?,?,?,?,'Renewal due',?,?,70,'Confirm renewal plan and executive sponsor',?,'Customer success','Open','','','Best case',?,?)").bind(now,name,String(plan.company_name),plan.company_id,plan.contact_id||null,clean(plan.owner,200)||user.email,Number(plan.annual_value)||0,renewalDate,now,now).run();
 const dealId=Number(created.meta.last_row_id);await env.DB.prepare("UPDATE customer_success_plans SET status='Renewing',renewal_deal_id=?,updated_at=? WHERE id=?").bind(dealId,now,planId).run();await env.DB.prepare("INSERT OR IGNORE INTO sales_pipelines(id,name,stages,updated_at) VALUES ('renewals','Renewals','[{\"key\":\"renewal-due\",\"name\":\"Renewal due\",\"probability\":70},{\"key\":\"negotiation\",\"name\":\"Negotiation\",\"probability\":85},{\"key\":\"renewed\",\"name\":\"Renewed\",\"probability\":100},{\"key\":\"churned\",\"name\":\"Churned\",\"probability\":0}]',?)").bind(now).run();await audit(user,"customer_success.renewal","deal",dealId,`Created renewal deal for ${plan.company_name}`,{planId,renewalDate});return {dealId,existing:false};
}

export async function runCustomerSuccessAlerts(){
 const plans=(await env.DB.prepare("SELECT p.*,c.name AS company_name FROM customer_success_plans p JOIN companies c ON c.id=p.company_id WHERE p.status NOT IN ('Churned') AND ((p.renewal_date IS NOT NULL AND date(p.renewal_date)<=date('now','+90 days')) OR p.churn_risk IN ('High','Critical') OR p.health_score<40)").all<Row>()).results;let created=0;
 for(const plan of plans){const reasons:string[]=[];if(plan.renewal_date&&String(plan.renewal_date)<=new Date(Date.now()+90*86400000).toISOString().slice(0,10))reasons.push(`renewal ${plan.renewal_date}`);if(Number(plan.health_score)<40)reasons.push(`health ${plan.health_score}`);if(["High","Critical"].includes(String(plan.churn_risk)))reasons.push(`${plan.churn_risk} churn risk`);const key=`customer_success:${plan.id}:${new Date().toISOString().slice(0,10)}`,exists=await env.DB.prepare("SELECT id FROM notifications WHERE kind='customer_success_alert' AND entity_id=? AND created_at>=datetime('now','-1 day')").bind(key).first();if(exists)continue;await env.DB.prepare("INSERT INTO notifications(owner_email,kind,title,body,entity_type,entity_id,action_url,created_at) VALUES (?,'customer_success_alert',?,?, 'company',?,'/?view=customers',datetime('now'))").bind(plan.owner,`${plan.company_name} needs customer-success attention`,reasons.join(" · "),key).run();created++;}return created;
}
