import { env } from "cloudflare:workers";

export const googleConfigured=()=>Boolean(env.GOOGLE_CLIENT_ID&&env.GOOGLE_CLIENT_SECRET&&env.CRM_TOKEN_ENCRYPTION_KEY);
export const googleRedirect=(origin:string)=>`${origin}/api/google/callback`;
export function googleAuthorizeUrl(origin:string,state:string){const url=new URL("https://accounts.google.com/o/oauth2/v2/auth");url.searchParams.set("client_id",String(env.GOOGLE_CLIENT_ID));url.searchParams.set("redirect_uri",googleRedirect(origin));url.searchParams.set("response_type","code");url.searchParams.set("access_type","offline");url.searchParams.set("prompt","consent");url.searchParams.set("include_granted_scopes","true");url.searchParams.set("scope","openid email https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/calendar.readonly");url.searchParams.set("state",state);return url.toString();}
async function tokenRequest(body:URLSearchParams){const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body});const data=await response.json() as Record<string,unknown>;if(!response.ok)throw new Error(String(data.error_description||data.error||"Google authorization failed."));return data;}
export function exchangeGoogleCode(origin:string,code:string){return tokenRequest(new URLSearchParams({client_id:String(env.GOOGLE_CLIENT_ID),client_secret:String(env.GOOGLE_CLIENT_SECRET),code,grant_type:"authorization_code",redirect_uri:googleRedirect(origin)}));}
export function refreshGoogleToken(refreshToken:string){return tokenRequest(new URLSearchParams({client_id:String(env.GOOGLE_CLIENT_ID),client_secret:String(env.GOOGLE_CLIENT_SECRET),refresh_token:refreshToken,grant_type:"refresh_token"}));}
export async function googleApi(url:string,token:string){const response=await fetch(url,{headers:{authorization:`Bearer ${token}`}});const data=await response.json() as Record<string,unknown>;if(!response.ok)throw new Error(String((data.error as {message?:string}|undefined)?.message||"Google API request failed."));return data;}
export async function revokeGoogleToken(token:string){const response=await fetch(`https://oauth2.googleapis.com/revoke?token=${encodeURIComponent(token)}`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"}});if(!response.ok)throw new Error(`Google token revocation returned ${response.status}.`);}
