import { meaningfulInteraction, type HealthRow } from "@/lib/relationship-health";
import type { StakeholderCoverageResult } from "@/lib/stakeholder-coverage";

export type RecommendationPriority="Critical"|"High"|"Medium"|"Normal";
export type RecommendationCandidate={ruleKey:string;rank:number;action:string;reason:string;evidence:string[];priority:RecommendationPriority;suggestedOwner:string;suggestedDueDate:string;fingerprint:string;taskId?:number|null};
type Input={deal:HealthRow;tasks:HealthRow[];reviews:HealthRow[];proposals:HealthRow[];insights:HealthRow[];activities:HealthRow[];coverage:StakeholderCoverageResult;now?:Date};

const day=86400000;
const value=(row:HealthRow,...keys:string[])=>{for(const key of keys)if(row[key]!==undefined)return row[key];return undefined};
const string=(row:HealthRow,...keys:string[])=>String(value(row,...keys)??"").trim();
const truthy=(row:HealthRow,...keys:string[])=>{const current=value(row,...keys);return current===true||current===1||current==="1"||current==="true"};
const dateOnly=(date:Date)=>date.toISOString().slice(0,10);
const addDays=(now:Date,days:number)=>dateOnly(new Date(now.getTime()+days*day));
const ageDays=(date:string,now:number)=>Number.isFinite(Date.parse(date))?Math.floor(Math.max(0,(now-Date.parse(date))/day)):0;

export function generateRecommendationCandidates(input:Input):RecommendationCandidate[]{
  if(string(input.deal,"status").toLowerCase()!=="open")return [];
  const now=input.now||new Date(),nowMs=now.getTime(),today=dateOnly(now),owner=string(input.deal,"owner")||"Unassigned",candidates:RecommendationCandidate[]=[];
  const add=(candidate:Omit<RecommendationCandidate,"suggestedOwner">&{suggestedOwner?:string})=>candidates.push({...candidate,suggestedOwner:candidate.suggestedOwner||owner});

  const overdue=input.tasks.filter(task=>!truthy(task,"completed")&&string(task,"due_date","dueDate")<today).map(task=>({...task,daysOverdue:ageDays(`${string(task,"due_date","dueDate")}T00:00:00Z`,nowMs)})).filter(task=>task.daysOverdue>=7).sort((a,b)=>b.daysOverdue-a.daysOverdue)[0];
  if(overdue)add({ruleKey:"overdue-follow-up",rank:1,action:`Complete overdue follow-up: ${string(overdue,"title")||"Deal follow-up"}`,reason:`This follow-up is ${overdue.daysOverdue} days overdue and is the highest-priority execution gap.`,evidence:[`Task #${String(value(overdue,"id")??"")} was due ${string(overdue,"due_date","dueDate")}.`,`${String(overdue.daysOverdue)} days overdue.`],priority:"Critical",suggestedOwner:string(overdue,"owner")||owner,suggestedDueDate:today,fingerprint:`overdue-follow-up:${String(value(overdue,"id")??"")}:${string(overdue,"due_date","dueDate")}`,taskId:Number(value(overdue,"id"))||null});

  const approval=input.reviews.filter(review=>{const status=string(review,"status").toLowerCase(),requested=string(review,"requested_at","requestedAt");return status==="rejected"||status==="blocked"||(status==="requested"&&ageDays(requested,nowMs)>=3)}).sort((a,b)=>{const blocked=(row:HealthRow)=>["rejected","blocked"].includes(string(row,"status").toLowerCase())?0:1;return blocked(a)-blocked(b)||string(a,"requested_at","requestedAt").localeCompare(string(b,"requested_at","requestedAt"))})[0];
  if(approval){const status=string(approval,"status"),days=ageDays(string(approval,"requested_at","requestedAt"),nowMs);add({ruleKey:"approval",rank:2,action:`Escalate ${status.toLowerCase()==="requested"?"overdue":"blocked"} approval: ${string(approval,"review_type","reviewType")||"Deal review"}`,reason:status.toLowerCase()==="requested"?`The approval has been waiting ${days} days.`:`The approval is ${status.toLowerCase()} and blocks progress.`,evidence:[`Approval #${String(value(approval,"id")??"")} · ${status}.`,`Approver: ${string(approval,"approver")||"Not assigned"}.`],priority:"Critical",suggestedDueDate:addDays(now,1),fingerprint:`approval:${String(value(approval,"id")??"")}:${status}:${string(approval,"requested_at","requestedAt")}`})}

  const expired=input.proposals.filter(proposal=>{const status=string(proposal,"status").toLowerCase(),valid=string(proposal,"valid_until","validUntil");return status==="expired"||(Boolean(valid)&&valid<today&&!['accepted','declined'].includes(status))}).sort((a,b)=>string(a,"valid_until","validUntil").localeCompare(string(b,"valid_until","validUntil")))[0];
  if(expired)add({ruleKey:"expired-proposal",rank:3,action:`Update expired proposal: ${string(expired,"title")||"Proposal"}`,reason:"The current commercial document is no longer valid, so the buyer cannot act on it confidently.",evidence:[`Proposal #${String(value(expired,"id")??"")} · ${string(expired,"status")}.`,string(expired,"valid_until","validUntil")?`Valid until ${string(expired,"valid_until","validUntil")}.`:"Proposal is marked expired."],priority:"High",suggestedDueDate:addDays(now,2),fingerprint:`expired-proposal:${String(value(expired,"id")??"")}:${string(expired,"status")}:${string(expired,"valid_until","validUntil")}`});

  const risk=input.insights.filter(item=>["risk","objection"].includes(string(item,"kind").toLowerCase())&&string(item,"severity").toLowerCase()==="high"&&!['resolved','closed'].includes(string(item,"status").toLowerCase())).sort((a,b)=>string(a,"created_at","createdAt").localeCompare(string(b,"created_at","createdAt")))[0];
  if(risk)add({ruleKey:"high-risk",rank:4,action:`Address ${string(risk,"kind").toLowerCase()}: ${string(risk,"title")||"Open deal risk"}`,reason:"A high-severity issue remains unresolved and may prevent the deal from advancing.",evidence:[`${string(risk,"kind")} #${String(value(risk,"id")??"")} · ${string(risk,"severity")} severity.`,string(risk,"detail")||`Status: ${string(risk,"status")}.`],priority:"High",suggestedOwner:string(risk,"owner")||owner,suggestedDueDate:addDays(now,2),fingerprint:`high-risk:${String(value(risk,"id")??"")}:${string(risk,"status")}:${string(risk,"updated_at","updatedAt")}`});

  const missing=input.coverage.findings.find(finding=>["missing-decision-maker","missing-champion","missing-economic-buyer"].includes(finding.key));
  if(missing)add({ruleKey:"missing-stakeholder",rank:5,action:missing.key==="missing-decision-maker"?"Add or engage the decision-maker":missing.key==="missing-champion"?"Develop an internal champion":"Add or engage the economic buyer",reason:missing.reason,evidence:missing.evidence,priority:missing.severity==="Critical"?"High":"Medium",suggestedDueDate:addDays(now,5),fingerprint:`missing-stakeholder:${missing.key}:${input.coverage.stage.key}:${input.coverage.stage.progress}`});

  const stale=input.coverage.keyStakeholders.filter(person=>person.engagement!=="Recent").sort((a,b)=>(b.daysSinceLastEngagement??9999)-(a.daysSinceLastEngagement??9999))[0];
  if(stale)add({ruleKey:"reengage-stakeholder",rank:6,action:`Re-engage ${stale.name} (${stale.role})`,reason:"A key stakeholder has no meaningful customer interaction in the last 30 days.",evidence:[stale.daysSinceLastEngagement==null?"No meaningful interaction is recorded for this stakeholder.":`Last meaningful interaction was ${stale.daysSinceLastEngagement} days ago.`,`Current role: ${stale.role}.`],priority:input.coverage.stage.phase==="Late"||input.coverage.stage.phase==="Contracting"?"High":"Medium",suggestedDueDate:addDays(now,3),fingerprint:`reengage-stakeholder:${stale.id}:${stale.lastEngagedAt||"none"}`});

  const meaningful=input.activities.map(activity=>meaningfulInteraction(activity,nowMs)).filter((item):item is NonNullable<typeof item>=>Boolean(item)),technical=meaningful.filter(item=>["Demonstration","Proposal review"].includes(item.kind)).sort((a,b)=>b.date.localeCompare(a.date))[0],technicalRecent=technical&&ageDays(technical.date,nowMs)<=30;
  if(input.coverage.stage.technical&&!technicalRecent)add({ruleKey:"technical-review",rank:7,action:"Schedule a technical review",reason:"The deal is in a technical stage without a demonstration or proposal review in the last 30 days.",evidence:[`Current stage: ${input.coverage.stage.name}.`,technical?`Last technical interaction was ${ageDays(technical.date,nowMs)} days ago.`:"No qualifying technical review is recorded."],priority:input.coverage.stage.contracting?"High":"Medium",suggestedDueDate:addDays(now,5),fingerprint:`technical-review:${input.coverage.stage.key}:${technical?.date||"none"}`});

  const closeDate=string(input.deal,"close_date","closeDate"),lastMeaningful=meaningful.sort((a,b)=>b.date.localeCompare(a.date))[0],unsupported=Boolean(closeDate)&&(!lastMeaningful||ageDays(lastMeaningful.date,nowMs)>30||!string(input.deal,"next_step","nextStep"));
  if(!closeDate||closeDate<today||unsupported){const passed=Boolean(closeDate)&&closeDate<today;add({ruleKey:"close-date",rank:8,action:!closeDate?"Set an evidence-based expected close date":"Revise the expected close date",reason:!closeDate?"The open deal has no expected close date.":passed?`The expected close date passed on ${closeDate}.`:"The close date is not supported by recent engagement and a recorded next step.",evidence:[closeDate?`Current close date: ${closeDate}.`:"No close date is recorded.",lastMeaningful?`Last meaningful interaction: ${lastMeaningful.kind} on ${dateOnly(new Date(lastMeaningful.date))}.`:"No meaningful interaction is recorded."],priority:passed?"High":"Medium",suggestedDueDate:addDays(now,1),fingerprint:`close-date:${closeDate||"missing"}:${lastMeaningful?.date||"none"}:${string(input.deal,"next_step","nextStep")}`})}

  const nextStep=string(input.deal,"next_step","nextStep");
  add({ruleKey:"next-step",rank:9,action:nextStep?`Complete next step: ${nextStep}`:"Record the deal's next step",reason:nextStep?"This is the next action already committed on the deal.":"An open deal needs one explicit next action before it can progress.",evidence:[nextStep?`Recorded next step: ${nextStep}.`:"The deal next-step field is empty.",`Current stage: ${input.coverage.stage.name}.`],priority:"Normal",suggestedDueDate:addDays(now,3),fingerprint:`next-step:${nextStep||"missing"}:${string(input.deal,"updated_at","updatedAt")}`});
  return candidates.sort((a,b)=>a.rank-b.rank||a.action.localeCompare(b.action));
}
