import { env } from "cloudflare:workers";
import { decryptToken, encryptToken } from "@/lib/microsoft";

type Row=Record<string,unknown>;
const endpoint=()=>String(env.QUICKBOOKS_ENVIRONMENT||"").toLowerCase()==="sandbox"?"https://sandbox-quickbooks.api.intuit.com":"https://quickbooks.api.intuit.com";
const basic=()=>`Basic ${btoa(`${String(env.QUICKBOOKS_CLIENT_ID)}:${String(env.QUICKBOOKS_CLIENT_SECRET)}`)}`;
export const quickbooksConfigured=()=>Boolean(env.QUICKBOOKS_CLIENT_ID&&env.QUICKBOOKS_CLIENT_SECRET&&env.CRM_TOKEN_ENCRYPTION_KEY);
export const quickbooksItemConfigured=()=>Boolean(env.QUICKBOOKS_DEFAULT_ITEM_ID);
export const quickbooksRedirect=(origin:string)=>`${origin}/api/quickbooks/callback`;
export function quickbooksAuthorizeUrl(origin:string,state:string){const url=new URL("https://appcenter.intuit.com/connect/oauth2");url.searchParams.set("client_id",String(env.QUICKBOOKS_CLIENT_ID));url.searchParams.set("response_type","code");url.searchParams.set("scope","com.intuit.quickbooks.accounting");url.searchParams.set("redirect_uri",quickbooksRedirect(origin));url.searchParams.set("state",state);return url.toString();}
async function tokenRequest(body:URLSearchParams){const response=await fetch("https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",{method:"POST",headers:{authorization:basic(),"content-type":"application/x-www-form-urlencoded",accept:"application/json"},body});const data=await response.json() as Row;if(!response.ok)throw new Error(String(data.error_description||data.error||"QuickBooks authorization failed."));return data;}
export const exchangeQuickbooksCode=(origin:string,code:string)=>tokenRequest(new URLSearchParams({grant_type:"authorization_code",code,redirect_uri:quickbooksRedirect(origin)}));
async function refreshQuickbooks(refreshToken:string){return tokenRequest(new URLSearchParams({grant_type:"refresh_token",refresh_token:refreshToken}));}
function metadata(row:Row){try{return JSON.parse(String(row.metadata_json||"{}")) as Row}catch{return {}}}
async function account(){const row=await env.DB.prepare("SELECT * FROM integration_accounts WHERE provider='quickbooks'").first<Row>();if(!row)throw new Error("Connect QuickBooks before creating invoices.");const realmId=String(metadata(row).realmId||"");if(!realmId)throw new Error("QuickBooks connection is missing its company identifier. Reconnect QuickBooks.");return {row,realmId};}
async function tokenFor(current:Row){let access=await decryptToken(String(current.access_token));if(new Date(String(current.expires_at)).getTime()>Date.now()+60_000)return access;const refreshed=await refreshQuickbooks(await decryptToken(String(current.refresh_token)));access=String(refreshed.access_token||"");if(!access)throw new Error("QuickBooks did not return a new access token.");await env.DB.prepare("UPDATE integration_accounts SET access_token=?,refresh_token=?,expires_at=?,updated_at=datetime('now') WHERE provider='quickbooks'").bind(await encryptToken(access),refreshed.refresh_token?await encryptToken(String(refreshed.refresh_token)):current.refresh_token,new Date(Date.now()+Number(refreshed.expires_in||3600)*1000).toISOString()).run();return access;}
export async function quickbooksApi(path:string,init:RequestInit={}){const {row,realmId}=await account();let access=await tokenFor(row);const call=async()=>fetch(`${endpoint()}/v3/company/${realmId}/${path}${path.includes("?")?"&":"?"}minorversion=75`,{...init,headers:{accept:"application/json",authorization:`Bearer ${access}`,"content-type":"application/json",...(init.headers||{})}});let response=await call();if(response.status===401){const refreshed=await refreshQuickbooks(await decryptToken(String(row.refresh_token)));access=String(refreshed.access_token||"");await env.DB.prepare("UPDATE integration_accounts SET access_token=?,refresh_token=?,expires_at=?,updated_at=datetime('now') WHERE provider='quickbooks'").bind(await encryptToken(access),refreshed.refresh_token?await encryptToken(String(refreshed.refresh_token)):row.refresh_token,new Date(Date.now()+Number(refreshed.expires_in||3600)*1000).toISOString()).run();response=await call();}const data=await response.json() as Row;if(!response.ok)throw new Error(String((data.Fault as Row|undefined)?.Error&&JSON.stringify((data.Fault as Row).Error)||data.error||"QuickBooks request failed."));return data;}
export async function quickbooksCompanyInfo(realmId:string,accessToken:string){const response=await fetch(`${endpoint()}/v3/company/${realmId}/companyinfo/${realmId}?minorversion=75`,{headers:{accept:"application/json",authorization:`Bearer ${accessToken}`}});const data=await response.json() as Row;if(!response.ok)throw new Error("QuickBooks company details could not be read.");return data;}
export async function revokeQuickbooksToken(token:string){const response=await fetch("https://developer.api.intuit.com/v2/oauth2/tokens/revoke",{method:"POST",headers:{authorization:basic(),accept:"application/json","content-type":"application/json"},body:JSON.stringify({token})});if(!response.ok)throw new Error(`QuickBooks token revocation returned ${response.status}.`);}
