import { env } from "cloudflare:workers";
import { sha256 } from "@/lib/crm-auth";

type Row=Record<string,unknown>;
const clean=(value:unknown,max=12000)=>String(value??"").trim().slice(0,max);
const rows=async(sql:string,...args:(string|number|null)[])=>(await env.DB.prepare(sql).bind(...args).all()).results as Row[];
async function access(request:Request){const url=new URL(request.url),token=clean(request.headers.get("x-portal-token")||url.searchParams.get("token"),200);if(!token.startsWith("crp_"))return null;return env.DB.prepare("SELECT pa.*,c.email,c.first_name AS first_name,c.last_name AS last_name,co.name AS company_name FROM customer_portal_access pa JOIN contacts c ON c.id=pa.contact_id JOIN companies co ON co.id=pa.company_id WHERE pa.token_hash=? AND pa.status='Active' AND (pa.expires_at IS NULL OR datetime(pa.expires_at)>datetime('now'))").bind(await sha256(token)).first<Row>()}

export async function GET(request:Request){try{const grant=await access(request);if(!grant)return Response.json({error:"This portal link is invalid or expired."},{status:401});await env.DB.prepare("UPDATE customer_portal_access SET last_used_at=datetime('now') WHERE id=?").bind(grant.id).run();const permissions=JSON.parse(String(grant.permissions_json||"[]")) as string[],companyId=Number(grant.company_id),contactId=Number(grant.contact_id),[cases,documents,plan,articles]=await Promise.all([
 permissions.includes("cases")?rows("SELECT id,case_number AS caseNumber,subject,description,priority,status,product,created_at AS createdAt,updated_at AS updatedAt FROM service_cases WHERE portal_visible=1 AND (company_id=? OR contact_id=?) ORDER BY created_at DESC",companyId,contactId):[],
 permissions.includes("documents")?rows("SELECT d.id,d.title,d.category,d.updated_at AS updatedAt,v.filename,v.size FROM client_documents d JOIN document_versions v ON v.document_id=d.id AND v.version=d.latest_version WHERE d.status='Active' AND d.sensitive=0 AND (d.company_id=? OR d.contact_id=?) ORDER BY d.updated_at DESC",companyId,contactId):[],
 permissions.includes("onboarding")?env.DB.prepare("SELECT status,onboarding_start AS onboardingStart,onboarding_target AS onboardingTarget,health_score AS healthScore,adoption_score AS adoptionScore,objectives_json AS objectives,renewal_date AS renewalDate,next_executive_touchpoint AS nextTouchpoint FROM customer_success_plans WHERE company_id=?").bind(companyId).first<Row>():null,
 permissions.includes("knowledge")?rows("SELECT id,title,slug,summary,body,category,updated_at AS updatedAt FROM knowledge_articles WHERE status='Published' AND audience IN ('Customers','Public') ORDER BY category,title"):[],
]);return Response.json({customer:{firstName:grant.first_name,lastName:grant.last_name,email:grant.email,company:grant.company_name},permissions,cases,documents,plan:plan?{...plan,objectives:JSON.parse(String(plan.objectives||"[]"))}:null,articles});}catch(error){console.error(error);return Response.json({error:"The customer portal could not load."},{status:503})}}

export async function POST(request:Request){try{const grant=await access(request);if(!grant)return Response.json({error:"This portal link is invalid or expired."},{status:401});const permissions=JSON.parse(String(grant.permissions_json||"[]")) as string[];if(!permissions.includes("cases"))return Response.json({error:"Case submission is not enabled for this portal."},{status:403});const body=await request.json() as Row,subject=clean(body.subject,500),description=clean(body.description);if(!subject||!description)throw new Error("Subject and description are required.");const priority=["Low","Normal","High","Urgent"].includes(clean(body.priority,40))?clean(body.priority,40):"Normal",now=new Date().toISOString(),id=crypto.randomUUID(),caseNumber=`CR-${Date.now().toString().slice(-8)}`,responseHours=priority==="Urgent"?1:priority==="High"?4:priority==="Low"?24:8,resolutionHours=priority==="Urgent"?8:priority==="High"?24:priority==="Low"?120:72;await env.DB.prepare("INSERT INTO service_cases(id,case_number,source,subject,description,priority,queue,status,owner,skills_json,contact_id,company_id,product,response_due_at,resolution_due_at,portal_visible,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,caseNumber,"Portal",subject,description,priority,"Customer support","New","","[]",grant.contact_id,grant.company_id,clean(body.product,240),new Date(Date.now()+responseHours*3600000).toISOString(),new Date(Date.now()+resolutionHours*3600000).toISOString(),1,now,now).run();return Response.json({id,caseNumber},{status:201});}catch(error){return Response.json({error:error instanceof Error?error.message:"The request could not be submitted."},{status:400})}}
