import { env } from "cloudflare:workers";
import { audit, can, crmUser } from "@/lib/crm-auth";
import { bytesFromBase64, saveCommunicationAttachment } from "@/lib/client-documents";
import { decryptToken, encryptToken } from "@/lib/microsoft";
import { googleApi, refreshGoogleToken } from "@/lib/google";
import { notify, stopSequencesForReply, systemEvent } from "@/lib/operations";
import { communicationCandidates, queueCommunicationReview } from "@/lib/communication-review";

type Row=Record<string,unknown>;type Contact={id:number;email:string;companyId:number|null;company:string};
const addresses=(value:string)=>Array.from(value.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)).map(match=>match[0].toLowerCase());
function parts(payload:unknown):Row[]{const row=(payload||{}) as Row,children=Array.isArray(row.parts)?row.parts as Row[]:[];return [row,...children.flatMap(child=>parts(child))]}

export async function POST(request:Request){
 const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});if(!can(user,"integrations.manage"))return Response.json({error:"Integration management permission is required to sync the connected mailbox."},{status:403});
 try{
  const account=await env.DB.prepare("SELECT * FROM integration_accounts WHERE provider='google'").first<Row>();if(!account)return Response.json({error:"Connect Google Workspace first."},{status:409});let access=await decryptToken(String(account.access_token));const refresh=account.refresh_token?await decryptToken(String(account.refresh_token)):"";
  if(new Date(String(account.expires_at)).getTime()<Date.now()+120000){if(!refresh)throw new Error("Reconnect Google Workspace to refresh access.");const next=await refreshGoogleToken(refresh);access=String(next.access_token);await env.DB.prepare("UPDATE integration_accounts SET access_token=?,expires_at=?,updated_at=datetime('now') WHERE provider='google'").bind(await encryptToken(access),new Date(Date.now()+Number(next.expires_in||3600)*1000).toISOString()).run();}
  const contacts=(await env.DB.prepare("SELECT c.id,lower(c.email) AS email,c.company,co.id AS companyId FROM contacts c LEFT JOIN companies co ON lower(co.name)=lower(c.company)").all<Contact>()).results,byEmail=new Map(contacts.map(c=>[c.email,c])),deals=(await env.DB.prepare("SELECT id,contact_id AS contactId,company_id AS companyId,company FROM deals WHERE status='Open'").all<Row>()).results;
	  const dealMatches=(contact:Contact)=>deals.filter(deal=>Number(deal.contactId)===contact.id||(contact.companyId&&Number(deal.companyId)===contact.companyId)||(!deal.companyId&&contact.company&&String(deal.company).toLowerCase()===contact.company.toLowerCase()));
	  const linkedDeal=(contact:Contact)=>{const matches=dealMatches(contact);return matches.length===1?Number(matches[0].id):null};
  let messages=0,meetings=0,replies=0,tasks=0,linked=0,attachments=0;
  if(account.sync_email){const list=await googleApi("https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=50&q=newer_than%3A30d",access);for(const stub of (list.messages as Row[]||[])){
	   const item=await googleApi(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${stub.id}?format=full`,access),headers=((item.payload as {headers?:Array<{name:string;value:string}>})?.headers||[]),header=(name:string)=>headers.find(h=>h.name.toLowerCase()===name.toLowerCase())?.value||"",from=addresses(header("From")),to=addresses(header("To")),all=[...from,...to],match=all.find(email=>byEmail.has(email));if(!match){const own=String(account.account_email||"").toLowerCase(),unknown=all.find(email=>email!==own)||all[0],externalId=String(item.id),candidate=unknown?await communicationCandidates(unknown):{companies:[],deals:[]};if(unknown)await queueCommunicationReview({source:"Google",sourceId:externalId,kind:"Unknown contact",senderEmail:unknown,subject:header("Subject")||"Email",evidence:{occurredAt:new Date(Number(item.internalDate||Date.now())).toISOString(),threadId:String(item.threadId||item.id)},suggestedContact:{email:unknown,companyDomain:unknown.split("@")[1]||""},companyCandidates:candidate.companies,dealCandidates:candidate.deals,confidence:candidate.companies.length===1?75:50});continue;}
	   const contact=byEmail.get(match)!,matches=dealMatches(contact),dealId=linkedDeal(contact),occurred=new Date(Number(item.internalDate||Date.now())).toISOString(),externalId=String(item.id),threadKey=`google:${String(item.threadId||item.id)}`,insert=await env.DB.prepare("INSERT OR IGNORE INTO sync_records(provider,external_id,item_type,contact_id,deal_id,thread_key,occurred_at,created_at) VALUES ('google',?,'email',?,?,?,?,datetime('now'))").bind(externalId,contact.id,dealId,threadKey,occurred).run();if(!insert.meta.changes)continue;if(matches.length>1)await queueCommunicationReview({source:"Google",sourceId:externalId,kind:"Ambiguous deal",senderEmail:match,subject:header("Subject")||"Email",evidence:{occurredAt:occurred,threadKey},contactId:contact.id,companyId:contact.companyId,dealCandidates:matches,confidence:45});
   const inbound=from.includes(match),subject=header("Subject")||"Email",responseDue=inbound?new Date(new Date(occurred).getTime()+24*3600000).toISOString():null;await env.DB.batch([env.DB.prepare("INSERT INTO activities(contact_id,type,note,happened_at) VALUES (?,?,?,?)").bind(contact.id,inbound?"Email received":"Email sent",subject,occurred),env.DB.prepare("INSERT OR IGNORE INTO inbox_messages(id,provider,external_id,direction,from_email,from_name,to_emails,subject,body,attachments_json,thread_key,response_due_at,status,owner,contact_id,company_id,deal_id,occurred_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(`google:${externalId}`,"Google",externalId,inbound?"Inbound":"Outbound",inbound?(from[0]||""):String(account.account_email||""),"",JSON.stringify(inbound?to:from),subject,subject,"[]",threadKey,responseDue,inbound?"Matched":"Awaiting reply",user.email,contact.id,contact.companyId,dealId,occurred,new Date().toISOString(),new Date().toISOString())]);messages++;
   if(dealId){await env.DB.prepare("INSERT INTO deal_activities(deal_id,company_id,contact_id,type,subject,body,owner,outcome,happened_at,source,thread_key,external_id,response_expected,pinned,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,'Google',?,?,?,0,datetime('now'),datetime('now'))").bind(dealId,contact.companyId,contact.id,inbound?"Email received":"Email sent",subject,subject,user.email,inbound?"Reply received":"Sent",occurred,threadKey,externalId,inbound?0:1).run();linked++;
    for(const part of parts(item.payload)){const filename=String(part.filename||""),body=(part.body||{}) as Row;if(!filename)continue;let data=String(body.data||"");if(!data&&body.attachmentId){const attachment=await googleApi(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${externalId}/attachments/${body.attachmentId}`,access);data=String(attachment.data||"")}if(!data)continue;const bytes=bytesFromBase64(data);if(await saveCommunicationAttachment({filename,contentType:String(part.mimeType||"application/octet-stream"),bytes,dealId,contactId:contact.id,companyId:contact.companyId,actor:user.email,source:"Google"}))attachments++}
   }
   if(inbound){const stopped=await stopSequencesForReply(contact.id,`Reply: ${subject}`);if(stopped){await notify(user.email,"reply","Prospect replied",subject,"contact",contact.id,"/?view=today");replies++;}}
  }}
  if(account.sync_calendar){const min=new Date(Date.now()-30*86400000).toISOString(),max=new Date(Date.now()+180*86400000).toISOString(),calendar=await googleApi(`https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=true&orderBy=startTime&maxResults=100&timeMin=${encodeURIComponent(min)}&timeMax=${encodeURIComponent(max)}`,access);for(const item of (calendar.items as Row[]||[])){if(item.status==="cancelled")continue;const organizer=String((item.organizer as {email?:string})?.email||"").toLowerCase(),attendees=(item.attendees as Array<{email?:string}>||[]).map(a=>String(a.email||"").toLowerCase()),match=[organizer,...attendees].find(email=>byEmail.has(email));if(!match)continue;const contact=byEmail.get(match)!,dealId=linkedDeal(contact),start=String((item.start as {dateTime?:string;date?:string})?.dateTime||(item.start as {date?:string})?.date||new Date().toISOString()),end=String((item.end as {dateTime?:string;date?:string})?.dateTime||(item.end as {date?:string})?.date||start),externalId=String(item.id),threadKey=`google-calendar:${externalId}`,insert=await env.DB.prepare("INSERT OR IGNORE INTO sync_records(provider,external_id,item_type,contact_id,deal_id,thread_key,occurred_at,created_at) VALUES ('google',?,'meeting',?,?,?,?,datetime('now'))").bind(externalId,contact.id,dealId,threadKey,start).run();if(!insert.meta.changes)continue;const subject=String(item.summary||"Calendar meeting");await env.DB.prepare("INSERT INTO activities(contact_id,type,note,happened_at) VALUES (?,'Calendar meeting',?,?)").bind(contact.id,subject,start).run();meetings++;if(dealId){await env.DB.prepare("INSERT INTO deal_activities(deal_id,company_id,contact_id,type,subject,body,owner,outcome,happened_at,source,thread_key,external_id,pinned,created_at,updated_at) VALUES (?,?,?,'Meeting',?,?,?,?,?,'Google',?,?,0,datetime('now'),datetime('now'))").bind(dealId,contact.companyId,contact.id,subject,subject,user.email,new Date(end).getTime()<Date.now()?"Completed":"Scheduled",start,threadKey,externalId).run();linked++}if(account.auto_tasks&&new Date(end).getTime()<Date.now()&&new Date(end).getTime()>Date.now()-7*86400000){if(dealId)await env.DB.prepare("INSERT INTO deal_tasks(deal_id,title,due_date,owner,created_at) VALUES (?,?,date('now','+1 day'),?,datetime('now'))").bind(dealId,`Follow up: ${subject}`,user.email).run();else await env.DB.prepare("INSERT INTO tasks(contact_id,title,due_date,owner,status,completed) VALUES (?,?,date('now','+1 day'),?,'Open',0)").bind(contact.id,`Follow up: ${subject}`,user.email).run();tasks++;}}}
  await env.DB.prepare("UPDATE integration_accounts SET last_synced_at=datetime('now'),updated_at=datetime('now') WHERE provider='google'").run();await audit(user,"integration.sync","integration","google",`Synced ${messages} emails and ${meetings} meetings`,{messages,meetings,replies,tasks,linked,attachments});return Response.json({messages,meetings,replies,tasks,linked,attachments});
 }catch(error){const message=error instanceof Error?error.message:"Google synchronization failed.";await systemEvent("error","integration","google",message);return Response.json({error:message},{status:500})}
}
