import { env } from "cloudflare:workers";
import { audit, can, crmUser } from "@/lib/crm-auth";
import { decryptToken, encryptToken } from "@/lib/microsoft";
import { googleApi, refreshGoogleToken } from "@/lib/google";
import { notify, stopSequencesForReply, systemEvent } from "@/lib/operations";
type Row=Record<string,unknown>;type Contact={id:number;email:string};
const addresses=(value:string)=>Array.from(value.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)).map(match=>match[0].toLowerCase());
export async function POST(request:Request){const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});if(!can(user,"records.edit"))return Response.json({error:"Edit access is required."},{status:403});try{const account=await env.DB.prepare("SELECT * FROM integration_accounts WHERE provider='google'").first<Row>();if(!account)return Response.json({error:"Connect Google Workspace first."},{status:409});let access=await decryptToken(String(account.access_token));const refresh=account.refresh_token?await decryptToken(String(account.refresh_token)):"";if(new Date(String(account.expires_at)).getTime()<Date.now()+120000){if(!refresh)throw new Error("Reconnect Google Workspace to refresh access.");const next=await refreshGoogleToken(refresh);access=String(next.access_token);await env.DB.prepare("UPDATE integration_accounts SET access_token=?,expires_at=?,updated_at=datetime('now') WHERE provider='google'").bind(await encryptToken(access),new Date(Date.now()+Number(next.expires_in||3600)*1000).toISOString()).run();}const contacts=(await env.DB.prepare("SELECT id,lower(email) AS email FROM contacts").all<Contact>()).results,byEmail=new Map(contacts.map(c=>[c.email,c.id]));let messages=0,meetings=0,replies=0,tasks=0;
if(account.sync_email){const list=await googleApi("https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=50&q=newer_than%3A30d",access);for(const stub of (list.messages as Row[]||[])){const item=await googleApi(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${stub.id}?format=metadata&metadataHeaders=From&metadataHeaders=To&metadataHeaders=Subject&metadataHeaders=Date`,access),headers=((item.payload as {headers?:Array<{name:string;value:string}>})?.headers||[]),header=(name:string)=>headers.find(h=>h.name.toLowerCase()===name.toLowerCase())?.value||"",from=addresses(header("From")),to=addresses(header("To")),match=[...from,...to].find(email=>byEmail.has(email));if(!match)continue;const contactId=Number(byEmail.get(match)),occurred=new Date(Number(item.internalDate||Date.now())).toISOString(),insert=await env.DB.prepare("INSERT OR IGNORE INTO sync_records(provider,external_id,item_type,contact_id,occurred_at,created_at) VALUES ('google',?,'email',?,?,datetime('now'))").bind(String(item.id),contactId,occurred).run();if(insert.meta.changes){const inbound=from.includes(match);await env.DB.prepare("INSERT INTO activities(contact_id,type,note,happened_at) VALUES (?,?,?,?)").bind(contactId,inbound?"Email received":"Email sent",header("Subject")||"Email",occurred).run();messages++;if(inbound){const stopped=await stopSequencesForReply(contactId,`Reply: ${header("Subject")||"Email"}`);if(stopped){await notify(user.email,"reply","Prospect replied",header("Subject")||"Email reply","contact",contactId,"/?view=today");replies++;}}}}}
if(account.sync_calendar){const min=new Date(Date.now()-30*86400000).toISOString(),max=new Date(Date.now()+180*86400000).toISOString(),calendar=await googleApi(`https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=true&orderBy=startTime&maxResults=100&timeMin=${encodeURIComponent(min)}&timeMax=${encodeURIComponent(max)}`,access);for(const item of (calendar.items as Row[]||[])){if(item.status==="cancelled")continue;const organizer=String((item.organizer as {email?:string})?.email||"").toLowerCase(),attendees=(item.attendees as Array<{email?:string}>||[]).map(a=>String(a.email||"").toLowerCase()),match=[organizer,...attendees].find(email=>byEmail.has(email));if(!match)continue;const contactId=Number(byEmail.get(match)),start=String((item.start as {dateTime?:string;date?:string})?.dateTime||(item.start as {date?:string})?.date||new Date().toISOString()),end=String((item.end as {dateTime?:string;date?:string})?.dateTime||(item.end as {date?:string})?.date||start),insert=await env.DB.prepare("INSERT OR IGNORE INTO sync_records(provider,external_id,item_type,contact_id,occurred_at,created_at) VALUES ('google',?,'meeting',?,?,datetime('now'))").bind(String(item.id),contactId,start).run();if(insert.meta.changes){await env.DB.prepare("INSERT INTO activities(contact_id,type,note,happened_at) VALUES (?,'Calendar meeting',?,?)").bind(contactId,String(item.summary||"Calendar meeting"),start).run();meetings++;if(account.auto_tasks&&new Date(end).getTime()<Date.now()&&new Date(end).getTime()>Date.now()-7*86400000){await env.DB.prepare("INSERT INTO tasks(contact_id,title,due_date,owner,status,completed) VALUES (?,?,date('now','+1 day'),?,'Open',0)").bind(contactId,`Follow up: ${String(item.summary||"meeting")}`,user.email).run();tasks++;}}}}
await env.DB.prepare("UPDATE integration_accounts SET last_synced_at=datetime('now'),updated_at=datetime('now') WHERE provider='google'").run();await audit(user,"integration.sync","integration","google",`Synced ${messages} emails and ${meetings} meetings`,{messages,meetings,replies,tasks});return Response.json({messages,meetings,replies,tasks});}catch(error){const message=error instanceof Error?error.message:"Google synchronization failed.";await systemEvent("error","integration","google",message);return Response.json({error:message},{status:500});}}
