import assert from "node:assert/strict";
import { applyMigrations, createD1, createModuleLoader, createSqlite, migrationFiles } from "./test-helpers.mjs";
// Upgrade path: 0006_rainy_microchip adds account/pipeline columns (fit/intent scores, temperature,
// pipeline_key, stage_key, ...) to existing companies and deals. Seed pre-0006 rows, then apply it.
const UPGRADE_MIGRATION="0006_rainy_microchip.sql";
const migrations=migrationFiles(),upgradeIndex=migrations.indexOf(UPGRADE_MIGRATION);
assert.ok(upgradeIndex>0,"missing "+UPGRADE_MIGRATION);
const sqlite=createSqlite({migrations:migrations.slice(0,upgradeIndex)});
sqlite.exec("INSERT INTO contacts(id,first_name,last_name,email,company,created_at) VALUES (1,'Test','Contact','test@example.com','Legacy','2026-01-01')");
sqlite.exec("INSERT INTO companies(id,name,updated_at) VALUES(1,'Legacy','2026-01-01')");
sqlite.exec("INSERT INTO deals(id,name,company,stage,status,created_at,updated_at) VALUES(1,'Legacy deal','Legacy','Qualified','Open','2026-01-01','2026-01-01')");
applyMigrations(sqlite,[UPGRADE_MIGRATION]);
assert.equal(sqlite.prepare("SELECT name FROM deals WHERE id=1").get().name,"Legacy deal");
assert.deepEqual({...sqlite.prepare("SELECT pipeline_key,stage_key FROM deals WHERE id=1").get()},{pipeline_key:"default",stage_key:null});
assert.equal(sqlite.prepare("SELECT temperature FROM companies WHERE id=1").get().temperature,"Cold");
applyMigrations(sqlite,migrations.slice(upgradeIndex+1));
const env={DB:createD1(sqlite),CRM_ALLOWED_EMAILS:"owner@example.com",TRUST_PLATFORM_IDENTITY_HEADERS:"true"};
const load=createModuleLoader(env);
const {POST,GET}=load("app/api/sales/route.ts");
const rules=load("lib/sales-rules.ts");
let checks=1;
const headers=email=>email?{"oai-authenticated-user-id":"test-user","oai-authenticated-user-email":email,"content-type":"application/json"}:{};
async function post(action,p={},expected=200,email="owner@example.com"){const old=console.error;console.error=()=>{};let response;try{response=await POST(new Request("https://test/api/sales",{method:"POST",headers:headers(email),body:JSON.stringify({action,...p})}))}finally{console.error=old}const body=await response.json();assert.equal(response.status,expected,JSON.stringify(body));checks++;return body;}
const one=(sql)=>sqlite.prepare(sql).get();
await post("saveAccount",{},401,null);
sqlite.exec("INSERT INTO team_members(email,role,created_at,updated_at) VALUES ('viewer@example.com','viewer','now','now'),('editor@example.com','editor','now','now')");
await post("saveAccount",{},403,"viewer@example.com");
await post("savePipeline",{},403,"editor@example.com");
sqlite.exec("INSERT INTO custom_field_definitions(id,entity_type,name,field_key,field_type,options,created_at) VALUES (1,'company','Customer segment','customer_segment','select','[\"Enterprise\",\"SMB\"]','2026-01-01')");
const account={name:"Legacy",owner:"editor@example.com",fit_score:70,fit_reason:"Strong industry fit",tags:"strategic,priority",customField_1:"Enterprise"};
await post("saveAccount",account);
assert.equal(one("SELECT value FROM custom_field_values WHERE definition_id=1 AND entity_type='company' AND entity_id=1").value,"Enterprise");
await post("saveAccount",{...account,customField_1:"SMB"});
assert.equal(one("SELECT value FROM custom_field_values WHERE definition_id=1 AND entity_type='company' AND entity_id=1").value,"SMB");
await post("saveAccount",{...account,customField_1:"Invalid"},400);
await post("saveAccount",{name:"New account",owner:"owner@example.com",fit_score:0});
assert.equal(one("SELECT COUNT(*) n FROM companies").n,2);
await post("saveStakeholder",{company_id:1,contact_id:1,role:"Champion",notes:"Sponsor"});
await post("saveStakeholder",{company_id:1,contact_id:1,role:"Decision-maker"});
assert.equal(one("SELECT COUNT(*) n FROM account_stakeholders").n,1);
const signal={company_id:1,summary:"Confirmed project",evidence:"Meeting reference",occurred_at:"2026-01-01"};
await post("saveSignal",{...signal,kind:"General news"});
assert.equal(one("SELECT temperature FROM companies WHERE id=1").temperature,"Cold");
await post("saveSignal",{...signal,kind:"Demo request"});
assert.equal(one("SELECT temperature FROM companies WHERE id=1").temperature,"Lukewarm");
await post("saveSignal",{...signal,kind:"Budget confirmed"});
assert.equal(one("SELECT temperature FROM companies WHERE id=1").temperature,"Hot");
assert.equal(one("SELECT COUNT(*) n FROM qualification_alerts").n,2);
await post("saveAccount",{...account,fit_score:20});
assert.equal(one("SELECT temperature FROM companies WHERE id=1").temperature,"Lukewarm");
await post("saveAccount",{...account,fit_score:70});
const demo=one("SELECT id FROM account_signals WHERE kind='Demo request'").id;
await post("withdrawSignal",{id:demo});
assert.equal(one("SELECT intent_score FROM companies WHERE id=1").intent_score,30);
await post("saveSignal",{...signal,kind:"Project paused"});
assert.equal(one("SELECT intent_score FROM companies WHERE id=1").intent_score,0);
await post("saveSignal",{...signal,company_id:999,kind:"Demo request"},400);
assert.equal(one("SELECT COUNT(*) n FROM account_signals WHERE company_id=999").n,0);
await post("saveSignal",{...signal,kind:"General news",evidence:""},400);
const stages=rules.defaultPipeline.stages.map(s=>({...s}));
stages[0].name="Validated fit";stages[0].probability=30;
await post("savePipeline",{id:"default",name:"New business",stages});
assert.equal(one("SELECT stage_key FROM deals WHERE id=1").stage_key,"Qualified");
assert.equal(one("SELECT stage FROM deals WHERE id=1").stage,"Validated fit");
await post("savePipeline",{id:"default",name:"Bad",stages:stages.slice(1)},400);
await post("savePipeline",{id:"partner",name:"Partners",stages});
const deal={name:"New opportunity",company:"Legacy",contact_id:1,pipeline_key:"partner",stage_key:"Qualified",owner:"editor@example.com",next_step:"Discovery meeting",value:1250};
await post("saveDeal",{...deal,next_step:""},400);
await post("saveDeal",deal);
const id=one("SELECT id FROM deals WHERE name='New opportunity'").id;
assert.equal(one("SELECT deal_id FROM deal_stage_history ORDER BY id DESC").deal_id,id);
await post("saveDeal",{...deal,id,stage_key:"Won"},400);
await post("saveDeal",{...deal,id,stage_key:"Won",closed_reason:"Signed agreement"});
assert.equal(one("SELECT status FROM deals WHERE id="+id).status,"Won");
assert.equal(one("SELECT probability FROM deals WHERE id="+id).probability,100);
await post("saveDeal",{...deal,id,pipeline_key:"missing"},400);
await post("saveTask",{deal_id:id,title:"Kickoff",owner:"editor@example.com",due_date:"2026-01-01"});
await post("completeTask",{id:1,completed:true});
assert.equal(one("SELECT completed FROM deal_tasks WHERE id=1").completed,1);
const data=await (await GET(new Request("https://test/api/sales",{headers:headers("editor@example.com")}))).json();
assert.ok(data.alerts.every(a=>a.owner==="editor@example.com"));
assert.equal(data.customFields[0].name,"Customer segment");
assert.equal(data.customFieldValues[0].value,"Enterprise");
const timeline=await (await GET(new Request("https://test/api/sales?account=1",{headers:headers("owner@example.com")}))).json();
assert.ok(timeline.timeline.some(t=>t.type==="Signal"));
assert.ok(timeline.timeline.some(t=>t.type==="Deal stage"));
assert.ok(one("SELECT COUNT(*) n FROM audit_logs").n>10);
assert.equal(rules.qualification(50,60),"Hot");
assert.equal(rules.qualification(49,60),"Lukewarm");
assert.equal(rules.qualification(100,19),"Cold");
assert.throws(()=>rules.validateStages([]));
assert.equal(sqlite.prepare("PRAGMA foreign_key_check").all().length,0);
console.log("PASS: "+checks+" route checks plus account custom fields, migration preservation, stakeholder upsert, scoring, alerts, stage history, tasks, timeline, permissions and FK integrity.");
