import { env } from "cloudflare:workers";
import { sha256 } from "@/lib/crm-auth";
import { rateLimit } from "@/lib/rate-limit";

type Row=Record<string,unknown>;
const clean=(value:unknown,max=24000)=>String(value??"").trim().slice(0,max);
const email=(value:unknown)=>clean(value,320).toLowerCase();
const token=(value:unknown)=>clean(value,160);
const accepted=(row:Row)=>Boolean(row.accepted_at);

async function record(shareToken:string){return env.DB.prepare("SELECT p.*,d.name AS deal_name,d.company,c.name AS company_name,b.business_name AS businessName,b.logo_url AS logoUrl,b.physical_address AS physicalAddress,a.signer_name AS signerName,a.signer_email AS signerEmail,a.signer_title AS signerTitle,a.accepted_at AS signatureAcceptedAt FROM deal_proposals p JOIN deals d ON d.id=p.deal_id LEFT JOIN companies c ON c.id=d.company_id LEFT JOIN brand_settings b ON b.id=1 LEFT JOIN proposal_acceptances a ON a.proposal_id=p.id WHERE p.share_token=?").bind(shareToken).first<Row>()}
function unavailable(row:Row){return !row||row.contract_status==="Link revoked"||Boolean(row.share_expires_at&&new Date(String(row.share_expires_at)).getTime()<Date.now())}
function payload(row:Row){return {proposal:{id:row.id,title:row.title,amount:row.amount,status:row.status,validUntil:row.valid_until,bodyMarkdown:row.body_markdown,contractStartDate:row.contract_start_date,contractEndDate:row.contract_end_date,renewalTermMonths:row.renewal_term_months,renewalNoticeDays:row.renewal_notice_days,autoRenew:Boolean(row.auto_renew),contractTerms:row.contract_terms,contractStatus:row.contract_status,acceptedAt:row.accepted_at,acceptedBy:row.accepted_by,signerName:row.signerName,signerEmail:row.signerEmail,signerTitle:row.signerTitle},deal:{name:row.deal_name,company:row.company||row.company_name||""},brand:{businessName:row.businessName||"ClientRecord",logoUrl:row.logoUrl||"",physicalAddress:row.physicalAddress||""}}}

export async function GET(request:Request){
 const limited=await rateLimit(request,"proposal",30);if(limited)return limited;
 const shareToken=token(new URL(request.url).searchParams.get("token"));if(!shareToken)return Response.json({error:"Proposal link is invalid."},{status:404});try{const row=await record(shareToken);if(!row||unavailable(row))return Response.json({error:"This proposal link is unavailable or has expired."},{status:410});const now=new Date().toISOString();if(!accepted(row)){await env.DB.batch([env.DB.prepare("UPDATE deal_proposals SET opened_at=COALESCE(opened_at,?),status=CASE WHEN status='Sent' THEN 'Opened' ELSE status END,contract_status=CASE WHEN contract_status='Sent for signature' THEN 'Viewed' ELSE contract_status END,updated_at=? WHERE id=?").bind(now,now,row.id),env.DB.prepare("INSERT INTO proposal_share_events(proposal_id,type,recipient,metadata_json,occurred_at) VALUES (?,'Opened','',?,?)").bind(row.id,JSON.stringify({userAgent:clean(request.headers.get("user-agent"),300)}),now)]);}return Response.json(payload(row));}catch(error){console.error(error);return Response.json({error:"The proposal could not be opened."},{status:503})}
}

export async function POST(request:Request){
 const limited=await rateLimit(request,"proposal",30);if(limited)return limited;
 try{const body=await request.json() as Row,shareToken=token(body.token),row=await record(shareToken);if(!row||unavailable(row))return Response.json({error:"This proposal link is unavailable or has expired."},{status:410});if(accepted(row))return Response.json({error:"This proposal has already been accepted."},{status:409});const signerName=clean(body.signerName,240),signerEmail=email(body.signerEmail),signerTitle=clean(body.signerTitle,240),signatureText=clean(body.signatureText,240);if(!signerName||!signatureText)throw new Error("Enter your full legal name to sign.");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(signerEmail))throw new Error("Enter a valid business email.");if(signerName.toLowerCase()!==signatureText.toLowerCase())throw new Error("Your typed signature must match your full name.");if(body.acceptTerms!==true)throw new Error("Confirm that you are authorized and accept the proposal terms.");if(row.sent_to&&signerEmail!==email(row.sent_to))throw new Error("Use the email address that received this proposal.");const now=new Date().toISOString(),ip=clean(request.headers.get("cf-connecting-ip"),120),ipHash=ip?await sha256(ip):"",termsSnapshot=JSON.stringify({title:row.title,amount:row.amount,bodyMarkdown:row.body_markdown,contractStartDate:row.contract_start_date,contractEndDate:row.contract_end_date,renewalTermMonths:row.renewal_term_months,renewalNoticeDays:row.renewal_notice_days,autoRenew:Boolean(row.auto_renew),contractTerms:row.contract_terms,shareToken});
 await env.DB.batch([env.DB.prepare("INSERT INTO proposal_acceptances(id,proposal_id,signer_name,signer_email,signer_title,signature_text,terms_snapshot,ip_hash,user_agent,accepted_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),row.id,signerName,signerEmail,signerTitle,signatureText,termsSnapshot,ipHash,clean(request.headers.get("user-agent"),1000),now),env.DB.prepare("UPDATE deal_proposals SET status='Accepted',accepted_at=?,accepted_by=?,contract_status='Signed',updated_at=? WHERE id=?").bind(now,signerEmail,now,row.id),env.DB.prepare("INSERT INTO proposal_share_events(proposal_id,type,recipient,metadata_json,occurred_at) VALUES (?,'Accepted',?,?,?)").bind(row.id,signerEmail,JSON.stringify({signerName,signerTitle,ipHash}),now)]);return Response.json({ok:true,acceptedAt:now});
 }catch(error){return Response.json({error:error instanceof Error?error.message:"The proposal could not be accepted."},{status:400});}
}
