import { env } from "cloudflare:workers";
import { audit, can, crmUser, type CRMUser } from "@/lib/crm-auth";
import { fromEmail, resend, sendingIdentity } from "@/lib/resend";
import { stopSequencesForReply } from "@/lib/operations";

type Row=Record<string,unknown>;
const clean=(value:unknown,max=24000)=>String(value??"").trim().slice(0,max);
const id=(value:unknown,label="record")=>{const result=Number(value);if(!Number.isInteger(result)||result<1)throw new Error(`Choose a valid ${label}.`);return result};
const email=(value:unknown)=>clean(value,320).toLowerCase();
const addresses=(value:unknown)=>Array.isArray(value)?value.map(email).filter(Boolean):clean(value,2000).split(/[;,]/).map(email).filter(Boolean);
const rows=async(sql:string,...args:(string|number|null)[])=>(await env.DB.prepare(sql).bind(...args).all()).results as Row[];
const toBase64=(buffer:ArrayBuffer)=>{const bytes=new Uint8Array(buffer);let output="";for(let index=0;index<bytes.length;index+=0x8000)output+=String.fromCharCode(...bytes.subarray(index,index+0x8000));return btoa(output)};
function attachmentIds(value:unknown){return Array.isArray(value)?value.map(item=>clean(item,100)).filter(Boolean).slice(0,8):[]}

// Attaching a document emails it outside the CRM, so apply the same access rules as downloading it.
async function messageDocuments(user:CRMUser,ids:string[]){
 if(!ids.length)return [] as {filename:string;content:string}[];if(!can(user,"documents.view"))throw new Error("You do not have permission to attach client documents.");const files:{filename:string;content:string}[]=[];let total=0;
 for(const documentId of ids){const row=await env.DB.prepare("SELECT d.id,d.sensitive,v.filename,v.object_key AS objectKey,v.size FROM client_documents d JOIN document_versions v ON v.document_id=d.id AND v.version=d.latest_version WHERE d.id=? AND d.status='Active'").bind(documentId).first<Row>();if(!row)throw new Error("An attached client document is unavailable.");if(row.sensitive&&!can(user,"documents.manage_sensitive"))throw new Error("Sensitive-document permission is required to email this document.");total+=Number(row.size||0);if(total>10*1024*1024)throw new Error("Email attachments must total 10 MB or less.");const object=await env.BUCKET.get(String(row.objectKey));if(!object)throw new Error("An attached file is unavailable from secure storage.");files.push({filename:String(row.filename),content:toBase64(await object.arrayBuffer())});}return files;
}

async function inboxData(user:CRMUser){
 await env.DB.prepare("UPDATE inbox_messages SET status='Overdue',updated_at=datetime('now') WHERE direction='Inbound' AND status NOT IN ('Resolved','Overdue') AND response_due_at IS NOT NULL AND datetime(response_due_at)<datetime('now')").run();
 // Contacts/companies are chosen with server-side search pickers (GET /api/crm?resource=search) rather than shipped here.
 const [messages,deals,documents,identity]=await Promise.all([
  rows("SELECT m.*,c.first_name||' '||c.last_name AS contact_name,c.email AS contact_email,co.name AS company_name,d.name AS deal_name FROM inbox_messages m LEFT JOIN contacts c ON c.id=m.contact_id LEFT JOIN companies co ON co.id=m.company_id LEFT JOIN deals d ON d.id=m.deal_id ORDER BY COALESCE(m.thread_key,m.id),m.occurred_at DESC LIMIT 400"),
  rows("SELECT id,name,company,company_id AS companyId,contact_id AS contactId,owner FROM deals WHERE status='Open' ORDER BY updated_at DESC LIMIT 800"),
  rows("SELECT d.id,d.title,d.category,v.filename,d.company_id AS companyId,d.contact_id AS contactId,d.deal_id AS dealId FROM client_documents d JOIN document_versions v ON v.document_id=d.id AND v.version=d.latest_version WHERE d.status='Active' AND (?=1 OR d.sensitive=0) AND ?=1 ORDER BY d.updated_at DESC LIMIT 800",can(user,"documents.manage_sensitive")?1:0,can(user,"documents.view")?1:0),
  env.DB.prepare("SELECT from_name AS fromName,from_email AS fromEmail,reply_to_email AS replyToEmail FROM brand_settings WHERE id=1").first<Row>(),
 ]);
 const overdue=messages.filter(message=>String(message.direction)==="Inbound"&&String(message.status)==="Overdue").length;
 return {messages,deals,documents,overdue,identity:{fromName:String(identity?.fromName||""),fromEmail:String(identity?.fromEmail||""),replyToEmail:String(identity?.replyToEmail||"")},account:{email:user.email}};
}

export async function GET(request:Request){const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});if(!can(user,"records.view"))return Response.json({error:"View access is required."},{status:403});try{return Response.json(await inboxData(user))}catch(error){console.error(error);return Response.json({error:"Shared inbox could not load."},{status:503})}}

export async function POST(request:Request){
 const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});if(!can(user,"records.edit"))return Response.json({error:"Edit access is required."},{status:403});
 try{const body=await request.json() as Row,action=clean(body.action,80),now=new Date().toISOString();
  if(action==="send"||action==="reply"){
   const recipients=addresses(body.to),subject=clean(body.subject,500),bodyText=clean(body.body,24000);if(!recipients.length||recipients.some(value=>!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)))throw new Error("Enter at least one valid recipient email.");if(!subject)throw new Error("Enter an email subject.");if(!bodyText)throw new Error("Write an email message.");
   const contactId=body.contactId?id(body.contactId,"contact"):null,contact=contactId?await env.DB.prepare("SELECT * FROM contacts WHERE id=?").bind(contactId).first<Row>():null,companyId=body.companyId?id(body.companyId,"company"):contact?Number((await env.DB.prepare("SELECT id FROM companies WHERE lower(name)=lower(?)").bind(contact.company).first<Row>())?.id||0)||null:null,dealId=body.dealId?id(body.dealId,"deal"):contact?Number((await env.DB.prepare("SELECT id FROM deals WHERE status='Open' AND (contact_id=? OR company_id=?) ORDER BY updated_at DESC LIMIT 1").bind(contactId,companyId).first<Row>())?.id||0)||null:null;
   const replied=clean(body.replyToMessageId,100),previous=replied?await env.DB.prepare("SELECT * FROM inbox_messages WHERE id=?").bind(replied).first<Row>():null;if(action==="reply"&&!previous)throw new Error("The email you are replying to is no longer available.");const threadKey=clean(previous?.thread_key,160)||clean(previous?.id,160)||crypto.randomUUID(),documentIds=attachmentIds(body.attachmentDocumentIds),attachments=await messageDocuments(user,documentIds),identity=await sendingIdentity(),sent=await resend("/emails",{method:"POST",body:JSON.stringify({from:fromEmail(identity),to:recipients,reply_to:identity.replyToEmail||undefined,subject:action==="reply"&&!/^re:/i.test(subject)?`Re: ${subject}`:subject,html:`<div style=\"font:16px Arial,sans-serif;line-height:1.6;white-space:pre-wrap\">${bodyText.replace(/[&<>]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[char]||char)).replaceAll("\n","<br/>")}</div>`,text:bodyText,attachments:attachments.length?attachments:undefined})}) as Row;
   const messageId=crypto.randomUUID(),emailSubject=action==="reply"&&!/^re:/i.test(subject)?`Re: ${subject}`:subject,attachmentMeta=attachments.map((file,index)=>({documentId:documentIds[index],filename:file.filename})),dueHours=Math.max(1,Math.min(240,Number(body.responseDueHours)||48)),responseDueAt=new Date(Date.now()+dueHours*3600000).toISOString();
   await env.DB.prepare("INSERT INTO inbox_messages(id,provider,external_id,direction,from_email,from_name,to_emails,subject,body,attachments_json,thread_key,in_reply_to,response_due_at,status,owner,contact_id,company_id,deal_id,occurred_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(messageId,"Resend",clean(sent.id,240)||null,"Outbound",identity.fromEmail,identity.fromName,JSON.stringify(recipients),emailSubject,bodyText,JSON.stringify(attachmentMeta),threadKey,previous?String(previous.id):null,responseDueAt,"Awaiting reply",clean(body.owner,200)||user.email,contactId,companyId,dealId,now,now,now).run();
   const changes=[env.DB.prepare("INSERT INTO delivery_logs(provider,kind,status,recipient,subject,external_id,error,context,created_at) VALUES ('resend','shared_inbox','Sent',?,?,?,'',?,datetime('now'))").bind(recipients[0],emailSubject,clean(sent.id,240),JSON.stringify({messageId,threadKey,dealId,attachments:attachmentMeta.length})),contactId?env.DB.prepare("INSERT INTO activities(contact_id,type,note,happened_at) VALUES (?,'Email sent',?,?)").bind(contactId,emailSubject,now):null,dealId?env.DB.prepare("INSERT INTO deal_activities(deal_id,company_id,contact_id,type,subject,body,owner,outcome,happened_at,source,thread_key,external_id,response_expected,pinned,created_at,updated_at) VALUES (?,?,?,'Email sent',?,?,?,?,?,'Shared inbox',?,?,1,0,?,?)").bind(dealId,companyId,contactId,emailSubject,bodyText,clean(body.owner,200)||user.email,"Sent",now,threadKey,messageId,now,now):null].filter(Boolean) as D1PreparedStatement[];if(previous)changes.push(env.DB.prepare("UPDATE inbox_messages SET status='Resolved',first_response_at=COALESCE(first_response_at,?),updated_at=? WHERE id=?").bind(now,now,previous.id));await env.DB.batch(changes);await audit(user,"inbox.send","inbox_message",messageId,`${action==="reply"?"Replied from":"Sent from"} shared inbox`,{recipients,contactId,companyId,dealId,threadKey,attachments:attachmentMeta.length});return Response.json({id:messageId,providerId:sent.id},{status:201});
  }
  if(action==="assign"){
   const messageId=clean(body.id,100),message=await env.DB.prepare("SELECT * FROM inbox_messages WHERE id=?").bind(messageId).first<Row>();if(!message)throw new Error("Inbox email not found.");const contactId=id(body.contactId,"contact"),companyId=body.companyId?id(body.companyId,"company"):null,dealId=body.dealId?id(body.dealId,"deal"):null,owner=clean(body.owner,200)||user.email;
   await env.DB.prepare("UPDATE inbox_messages SET contact_id=?,company_id=?,deal_id=?,owner=?,status='Assigned',updated_at=? WHERE id=?").bind(contactId,companyId,dealId,owner,now,messageId).run();if(dealId)await env.DB.prepare("INSERT INTO deal_activities(deal_id,company_id,contact_id,type,subject,body,owner,outcome,happened_at,source,thread_key,external_id,pinned,created_at,updated_at) VALUES (?,?,?,'Email associated',?,?,?,?,?,'Shared inbox',?,?,0,?,?)").bind(dealId,companyId,contactId,message.subject,message.body,owner,"Associated",message.occurred_at,message.thread_key||message.id,messageId,now,now).run();await audit(user,"inbox.assign","inbox_message",messageId,"Assigned shared inbox email",{contactId,companyId,dealId,owner});
  }else if(action==="resolve"){const messageId=clean(body.id,100);await env.DB.prepare("UPDATE inbox_messages SET status='Resolved',updated_at=? WHERE id=?").bind(now,messageId).run();await audit(user,"inbox.resolve","inbox_message",messageId,"Resolved shared inbox email",{});
  }else throw new Error("Unknown shared inbox action.");return Response.json({ok:true});
 }catch(error){return Response.json({error:error instanceof Error?error.message:"The inbox change could not be saved."},{status:400});}
}
