import { audit, can, displayName, type CRMUser } from "@/lib/crm-auth";
import { companyDetail, companyQuery, contactDetail, contactQuery, listCompanies, listContacts, searchRecords } from "@/lib/crm-records";
import { completeContactTask, createContact, createContactTask, logContactActivity, updateContact } from "@/lib/services/contacts";
import { appendCompanyNote, saveCompany } from "@/lib/services/companies";
import { addDealNote, createDealTask, dealRecord, logDealActivity, pipelines, saveDeal, setDealTaskCompleted } from "@/lib/services/deals";
import { dealDetail, listDeals, listTasks, pipelineSummary } from "@/lib/services/read-models";
import { ServiceError } from "@/lib/services/errors";

type Row = Record<string, unknown>;
export type ToolContext = { db: D1Database; user: CRMUser; client: string; now?: string };
export type ToolDefinition = { name: string; description: string; inputSchema: Record<string, unknown>; annotations: { readOnlyHint: boolean; destructiveHint: false; idempotentHint: boolean; openWorldHint: false }; permission: "records.view" | "records.edit"; run(ctx: ToolContext, args: Row): Promise<unknown> };

const MAX_TEXT = 2000, MAX_ARRAY = 50, SECRET_KEY = /token|secret|hash|password|share/i;
export function sanitize(value: unknown): unknown {
  if (typeof value === "string") return value.length > MAX_TEXT ? value.slice(0, MAX_TEXT) + "…" : value;
  if (Array.isArray(value)) return value.slice(0, MAX_ARRAY).map(sanitize);
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Row).filter(([k]) => !SECRET_KEY.test(k)).map(([k, v]) => [k, sanitize(v)]));
  return value;
}

const str = (a: Row, k: string, max = 4000) => { const v = a[k]; if (v === undefined || v === null) return undefined; if (typeof v !== "string") throw new ServiceError(`${k} must be text.`); return v.trim().slice(0, max); };
const int = (a: Row, k: string, required = true) => { const v = a[k]; if (v === undefined || v === null || v === "") { if (required) throw new ServiceError(`${k} is required.`); return undefined; } const n = typeof v === "number" ? v : typeof v === "string" && /^\d+$/.test(v) ? Number(v) : NaN; if (!Number.isSafeInteger(n) || n < 1) throw new ServiceError(`${k} must be a positive whole number.`); return n; };
const num = (a: Row, k: string) => { const v = a[k]; if (v === undefined || v === null || v === "") return undefined; const n = Number(v); if (!Number.isFinite(n) || n < 0) throw new ServiceError(`${k} must be a non-negative number.`); return n; };
const oneOf = <T extends string>(a: Row, k: string, values: readonly T[], fallback?: T) => { const v = a[k] ?? fallback; if (v === undefined) throw new ServiceError(`${k} is required.`); if (!values.includes(v as T)) throw new ServiceError(`${k} must be one of: ${values.join(", ")}.`); return v as T; };
const list = (a: Row, k: string) => { const v = a[k]; if (v === undefined) return undefined; if (!Array.isArray(v) || v.some(x => typeof x !== "string")) throw new ServiceError(`${k} must be a list of text values.`); return (v as string[]).slice(0, 30); };
const day = (a: Row, k: string) => { const v = str(a, k, 40); if (!v) return undefined; const t = Date.parse(v + "T00:00:00Z"); if (!/^\d{4}-\d{2}-\d{2}$/.test(v) || !Number.isFinite(t) || new Date(t).toISOString().slice(0, 10) !== v) throw new ServiceError(`${k} must be a real date in YYYY-MM-DD form.`); return v; };
const when = (a: Row, k: string) => { const v = str(a, k, 40); if (!v) return undefined; const t = Date.parse(v); if (!Number.isFinite(t)) throw new ServiceError(`${k} must be a date or date/time, e.g. 2026-10-01T15:00:00Z.`); return new Date(t).toISOString(); };
const mustExist = async (ctx: ToolContext, table: "contacts" | "companies", rowId: number | undefined) => { if (rowId !== undefined && !(await ctx.db.prepare(`SELECT id FROM ${table} WHERE id=?`).bind(rowId).first())) throw new ServiceError(`${table === "contacts" ? "Contact" : "Company"} not found.`, 404); return rowId; };
const jsonList = (v: unknown) => { try { const parsed = JSON.parse(String(v || "[]")); return Array.isArray(parsed) ? parsed.map(String) : []; } catch { return []; } };
const S = (description: string, properties: Row, required: string[] = []) => ({ type: "object", description, properties, required, additionalProperties: false });
const text = (description: string) => ({ type: "string", description });
const id = (description = "Record id") => ({ type: "integer", minimum: 1, description });
const READ = { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } as const;
const WRITE = { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } as const;
const who = async (ctx: ToolContext) => displayName(ctx.user);
const record = async (ctx: ToolContext, name: string, entity: string, entityId: unknown, summary: string, details: Row) => audit(ctx.user, `mcp.${name}`, entity, entityId, summary, { ...details, via: "mcp", client: ctx.client });
const contactRowToInput = (c: Row) => ({ firstName: String(c.firstName || ""), lastName: String(c.lastName || ""), email: String(c.email || ""), company: String(c.company || ""), title: String(c.title || ""), phone: String(c.phone || ""), location: String(c.location || ""), notes: String(c.notes || ""), leadSource: String(c.leadSource || ""), stage: String(c.stage || ""), tags: (c.tags as string[]) || [] });

export const TOOLS: ToolDefinition[] = [
  { name: "search_crm", description: "Search contacts, companies and deals by name, email or company. Returns up to 20 matches of each type.", permission: "records.view", annotations: READ,
    inputSchema: S("Search", { query: text("Search text"), types: { type: "array", items: { enum: ["contact", "company", "deal"] }, description: "Record types to include (default: all)" } }, ["query"]),
    run: async (ctx, a) => searchRecords(ctx.db, { q: str(a, "query", 200) || "", limit: 20, types: (list(a, "types") || ["contact", "company", "deal"]).join(",") }) },
  { name: "get_contact", description: "Get one contact with recent activity, campaign history, custom fields and likely duplicates.", permission: "records.view", annotations: READ,
    inputSchema: S("Contact", { id: id("Contact id") }, ["id"]),
    run: async (ctx, a) => { const d = await contactDetail(ctx.db, int(a, "id")!); if (!d) throw new ServiceError("Contact not found.", 404); return d; } },
  { name: "get_company", description: "Get one company with its people.", permission: "records.view", annotations: READ,
    inputSchema: S("Company", { id: id("Company id") }, ["id"]),
    run: async (ctx, a) => { const d = await companyDetail(ctx.db, { id: int(a, "id") }); if (!d?.company) throw new ServiceError("Company not found.", 404); return d; } },
  { name: "get_deal", description: "Get one deal (value in dollars) with notes, recent activity, open tasks, stakeholders and stage history.", permission: "records.view", annotations: READ,
    inputSchema: S("Deal", { id: id("Deal id") }, ["id"]),
    run: async (ctx, a) => { const d = await dealDetail(ctx.db, int(a, "id")!); if (!d) throw new ServiceError("Deal not found.", 404); return d; } },
  { name: "list_contacts", description: "List contacts, 25 per page, with the CRM's filters.", permission: "records.view", annotations: READ,
    inputSchema: S("Filters", { query: text("Search text"), stage: text("Lifecycle stage, e.g. Lead or Customer"), tag: text("Tag"), view: { enum: ["All contacts", "Customers", "Needs follow-up", "Quiet 30+ days"] }, sort: { enum: ["name", "recent", "followup", "newest"] }, offset: { type: "integer", minimum: 0 } }),
    run: async (ctx, a) => listContacts(ctx.db, { ...contactQuery({ q: str(a, "query", 200) || "", stage: str(a, "stage", 80) || "", tag: str(a, "tag", 80) || "", view: str(a, "view", 40) || "", sort: str(a, "sort", 20) || "", offset: Number(a.offset) || 0 }), limit: 25 }) },
  { name: "list_companies", description: "List companies, 25 per page.", permission: "records.view", annotations: READ,
    inputSchema: S("Filters", { query: text("Search text"), temperature: { enum: ["Cold", "Lukewarm", "Hot"] }, offset: { type: "integer", minimum: 0 } }),
    run: async (ctx, a) => listCompanies(ctx.db, { ...companyQuery({ q: str(a, "query", 200) || "", temperature: str(a, "temperature", 20) || "", offset: Number(a.offset) || 0 }), limit: 25 }) },
  { name: "list_deals", description: "List deals (values in dollars), 25 per page. Defaults to open deals.", permission: "records.view", annotations: READ,
    inputSchema: S("Filters", { query: text("Deal or company name"), stage: text("Stage name"), owner: text("Owner"), status: { enum: ["Open", "Won", "Lost", "All"] }, closingWithinDays: { type: "integer", minimum: 1, maximum: 365, description: "Only deals with a close date from today through today + N days" }, stalledOnly: { type: "boolean" }, offset: { type: "integer", minimum: 0 }, limit: { type: "integer", minimum: 1, maximum: 25 } }),
    run: async (ctx, a) => listDeals(ctx.db, { q: str(a, "query", 200), stage: str(a, "stage", 80), owner: str(a, "owner", 200), status: oneOf(a, "status", ["Open", "Won", "Lost", "All"] as const, "Open"), closingWithinDays: num(a, "closingWithinDays"), stalledOnly: a.stalledOnly === true, offset: Number(a.offset) || 0, limit: Number(a.limit) || 25 }) },
  { name: "list_tasks", description: "List open tasks: mine, overdue, due in the next 7 days, all, or for one contact or deal.", permission: "records.view", annotations: READ,
    inputSchema: S("Filters", { scope: { enum: ["mine", "overdue", "due_soon", "all"] }, contactId: id("Only this contact's tasks"), dealId: id("Only this deal's tasks") }),
    run: async (ctx, a) => listTasks(ctx.db, { scope: oneOf(a, "scope", ["mine", "overdue", "due_soon", "all"] as const, "mine"), owners: [ctx.user.email, await who(ctx)], contactId: int(a, "contactId", false), dealId: int(a, "dealId", false) }) },
  { name: "pipeline_summary", description: "Open pipeline totals per pipeline (each pipeline's stages in its own order, with open value and weighted forecast), overall totals and stalled deals (dollars).", permission: "records.view", annotations: READ,
    inputSchema: S("No inputs", {}), run: async ctx => pipelineSummary(ctx.db) },

  { name: "create_contact", description: "Create a contact. Fails if the email already exists. Suppressed emails stay unsubscribed.", permission: "records.edit", annotations: WRITE,
    inputSchema: S("Contact", { firstName: text("First name"), lastName: text("Last name"), email: text("Email"), company: text("Company name"), title: text("Job title"), phone: text("Phone"), location: text("Location"), notes: text("Notes"), stage: text("Lifecycle stage (default Lead)"), tags: { type: "array", items: { type: "string" } } }, ["firstName", "lastName", "email"]),
    run: async (ctx, a) => { const input = { firstName: str(a, "firstName", 200) || "", lastName: str(a, "lastName", 200) || "", email: str(a, "email", 320) || "", company: str(a, "company", 300), title: str(a, "title", 300), phone: str(a, "phone", 80), location: str(a, "location", 300), notes: str(a, "notes", 20000), stage: str(a, "stage", 80), tags: list(a, "tags") }; const r = await createContact(ctx.db, input); await record(ctx, "create_contact", "contact", r.id, `Created contact ${input.email}`, { email: input.email }); return r; } },
  { name: "update_contact", description: "Update a contact. Only the fields you pass change. Fails if the new email belongs to another contact.", permission: "records.edit", annotations: WRITE,
    inputSchema: S("Changes", { id: id("Contact id"), firstName: text("First name"), lastName: text("Last name"), email: text("Email"), company: text("Company name"), title: text("Job title"), phone: text("Phone"), location: text("Location"), stage: text("Lifecycle stage"), tags: { type: "array", items: { type: "string" } } }, ["id"]),
    run: async (ctx, a) => { const contactId = int(a, "id")!; const d = await contactDetail(ctx.db, contactId); if (!d) throw new ServiceError("Contact not found.", 404); const current = contactRowToInput(d.contact as Row); const changes = Object.fromEntries(Object.entries({ firstName: str(a, "firstName", 200), lastName: str(a, "lastName", 200), email: str(a, "email", 320), company: str(a, "company", 300), title: str(a, "title", 300), phone: str(a, "phone", 80), location: str(a, "location", 300), stage: str(a, "stage", 80), tags: list(a, "tags") }).filter(([, v]) => v !== undefined)); if (changes.email && await ctx.db.prepare("SELECT id FROM contacts WHERE lower(email)=lower(?) AND id<>?").bind(changes.email, contactId).first()) throw new ServiceError("A contact with that email already exists.", 409); await updateContact(ctx.db, contactId, { ...current, ...changes }, [], { enrollOnlyOnStageChange: true }); await record(ctx, "update_contact", "contact", contactId, "Updated contact", { fields: Object.keys(changes) }); return { id: contactId, updated: Object.keys(changes) }; } },
  { name: "create_company", description: "Create a company. Owner defaults to you.", permission: "records.edit", annotations: WRITE,
    inputSchema: S("Company", { name: text("Company name"), ownerEmail: text("Owner email (default: you)"), stage: text("Stage (default Prospect)"), website: text("https:// URL"), domain: text("Domain"), industry: text("Industry"), notes: text("Notes") }, ["name"]),
    run: async (ctx, a) => { const name = str(a, "name", 300) || ""; if (await ctx.db.prepare("SELECT id FROM companies WHERE lower(name)=lower(?)").bind(name).first()) throw new ServiceError("A company with that name already exists.", 409); const r = await saveCompany(ctx.db, { name, owner: str(a, "ownerEmail", 320) || ctx.user.email, stage: str(a, "stage", 80), website: str(a, "website", 500), domain: str(a, "domain", 300), industry: str(a, "industry", 200), notes: str(a, "notes", 20000) }, ctx.user.email, ctx.now); await record(ctx, "create_company", "company", r.id, `Created company ${name}`, { name }); return { id: r.id }; } },
  { name: "update_company", description: "Update a company. Only the fields you pass change.", permission: "records.edit", annotations: WRITE,
    inputSchema: S("Changes", { id: id("Company id"), ownerEmail: text("Owner email"), stage: text("Stage"), website: text("https:// URL"), domain: text("Domain"), industry: text("Industry"), tier: text("Tier"), territory: text("Territory"), summary: text("Summary") }, ["id"]),
    run: async (ctx, a) => { const companyId = int(a, "id")!; const c = await ctx.db.prepare("SELECT * FROM companies WHERE id=?").bind(companyId).first<Row>(); if (!c) throw new ServiceError("Company not found.", 404); const pick = (k: string, col: string, max = 4000) => str(a, k, max) ?? String(c[col] ?? ""); const owner = str(a, "ownerEmail", 320) ?? String(c.owner || ""); await saveCompany(ctx.db, { name: String(c.name), owner: owner || ctx.user.email, stage: pick("stage", "stage", 80), website: pick("website", "website", 500), domain: pick("domain", "domain", 300), industry: pick("industry", "industry", 200), tier: pick("tier", "tier", 80), territory: pick("territory", "territory", 200), summary: pick("summary", "summary"), notes: String(c.notes ?? ""), headquarters: String(c.headquarters || ""), linkedin_url: String(c.linkedin_url || ""), logo_url: String(c.logo_url || ""), employee_range: String(c.employee_range || ""), fit_score: Number(c.fit_score || 0), fit_reason: String(c.fit_reason || ""), tags: jsonList(c.tags) }, ctx.user.email, ctx.now); await record(ctx, "update_company", "company", companyId, "Updated company", { fields: Object.keys(a).filter(k => k !== "id") }); return { id: companyId }; } },
  { name: "create_deal", description: "Create a deal. Value is in dollars. Pipeline (id or name) defaults to the first saved pipeline, or the built-in default when none are saved; stage (name) is matched within that pipeline and defaults to its first open stage.", permission: "records.edit", annotations: WRITE,
    inputSchema: S("Deal", { name: text("Deal name"), companyId: id("Company id"), contactId: id("Primary contact id"), value: { type: "number", minimum: 0 }, pipeline: text("Pipeline id or name (default: the first saved pipeline)"), stage: text("Stage name within the pipeline"), nextStep: text("Next action (required for open deals)"), closeDate: text("YYYY-MM-DD"), owner: text("Owner (default: you)") }, ["name", "nextStep"]),
    run: async (ctx, a) => { const all = await pipelines(ctx.db), wanted = str(a, "pipeline", 120)?.toLowerCase(), firstSaved = wanted ? undefined : (await ctx.db.prepare("SELECT id FROM sales_pipelines ORDER BY rowid LIMIT 1").first<Row>())?.id; const pipe = wanted ? all.find(p => p.id.toLowerCase() === wanted || p.name.toLowerCase() === wanted) : all.find(p => p.id === String(firstSaved ?? "default")) ?? all.find(p => p.id === "default"); if (!pipe) throw new ServiceError(`Unknown pipeline. Pipelines: ${all.map(p => p.name).join(", ")}.`); const stageName = str(a, "stage", 80); const stage = stageName ? pipe.stages.find(s => s.name.toLowerCase() === stageName.toLowerCase() || s.key.toLowerCase() === stageName.toLowerCase()) : pipe.stages.find(s => s.kind === "Open"); if (!stage) throw new ServiceError(`Unknown stage. Stages: ${pipe.stages.map(s => s.name).join(", ")}.`); const companyId = await mustExist(ctx, "companies", int(a, "companyId", false)), contactId = await mustExist(ctx, "contacts", int(a, "contactId", false)); const r = await saveDeal(ctx.db, { name: str(a, "name", 300) || "", owner: str(a, "owner", 200) || await who(ctx), pipeline_key: pipe.id, stage_key: stage.key, value: num(a, "value") ?? 0, company_id: companyId ?? null, contact_id: contactId ?? null, next_step: str(a, "nextStep", 1000), close_date: day(a, "closeDate") }, ctx.user.email, ctx.now); await record(ctx, "create_deal", "deal", r.id, "Created deal", { name: a.name, pipeline: pipe.id, stage: stage.name }); return { id: r.id, pipeline: pipe.name, stage: stage.name }; } },
  { name: "update_deal", description: "Update a deal or move its stage. Only the fields you pass change. Won/Lost need a closedReason; stage rules are enforced.", permission: "records.edit", annotations: WRITE,
    inputSchema: S("Changes", { id: id("Deal id"), name: text("Deal name"), stage: text("Stage name"), value: { type: "number", minimum: 0 }, nextStep: text("Next action"), closeDate: text("YYYY-MM-DD"), closedReason: text("Won/lost reason"), owner: text("Owner"), contactId: id("Primary contact id"), companyId: id("Company id") }, ["id"]),
    run: async (ctx, a) => { const dealId = int(a, "id")!; const d = await dealRecord(ctx.db, dealId); const pipe = (await pipelines(ctx.db)).find(p => p.id === String(d.pipeline_key || "default")); if (!pipe) throw new ServiceError("This deal's pipeline no longer exists.", 409); const stageName = str(a, "stage", 80); const stage = stageName ? pipe.stages.find(s => s.name.toLowerCase() === stageName.toLowerCase() || s.key.toLowerCase() === stageName.toLowerCase()) : pipe.stages.find(s => s.key === String(d.stage_key || d.stage)); if (!stage) throw new ServiceError(`Unknown stage. Stages: ${pipe.stages.map(s => s.name).join(", ")}.`); const companyId = await mustExist(ctx, "companies", int(a, "companyId", false)), contactId = await mustExist(ctx, "contacts", int(a, "contactId", false)); const r = await saveDeal(ctx.db, { id: dealId, name: str(a, "name", 300) ?? String(d.name), owner: str(a, "owner", 200) ?? String(d.owner), pipeline_key: pipe.id, stage_key: stage.key, value: num(a, "value") ?? Number(d.value || 0) / 100, contact_id: contactId ?? (d.contact_id ? Number(d.contact_id) : null), company_id: companyId ?? (d.company_id ? Number(d.company_id) : null), company: String(d.company || ""), close_date: day(a, "closeDate") ?? String(d.close_date || ""), next_step: str(a, "nextStep", 1000) ?? String(d.next_step || ""), closed_reason: str(a, "closedReason", 1000) ?? String(d.closed_reason || ""), lead_source: String(d.lead_source || ""), campaign: String(d.campaign || ""), partner: String(d.partner || ""), forecast_category: String(d.forecast_category || "") }, ctx.user.email, ctx.now); await record(ctx, "update_deal", "deal", dealId, r.changed ? `Moved deal to ${stage.name}` : "Updated deal", { fields: Object.keys(a).filter(k => k !== "id"), stage: stage.name }); return { id: dealId, stage: stage.name, stageChanged: r.changed }; } },
  { name: "add_note", description: "Add a note to a contact, company or deal.", permission: "records.edit", annotations: WRITE,
    inputSchema: S("Note", { recordType: { enum: ["contact", "company", "deal"] }, id: id("Record id"), note: text("Note text") }, ["recordType", "id", "note"]),
    run: async (ctx, a) => { const type = oneOf(a, "recordType", ["contact", "company", "deal"] as const), recordId = int(a, "id")!, note = str(a, "note", 20000) || ""; if (type === "deal") await addDealNote(ctx.db, { dealId: recordId, body: note, owner: ctx.user.email, now: ctx.now }); else if (type === "company") await appendCompanyNote(ctx.db, recordId, note, await who(ctx), ctx.now); else await logContactActivity(ctx.db, { contactId: recordId, type: "Note", note, owner: await who(ctx), now: ctx.now }); await record(ctx, "add_note", type, recordId, `Added a ${type} note`, {}); return { ok: true }; } },
  { name: "log_activity", description: "Log a call, meeting or email that already happened on a contact or deal, optionally with a follow-up date.", permission: "records.edit", annotations: WRITE,
    inputSchema: S("Activity", { recordType: { enum: ["contact", "deal"] }, id: id("Record id"), type: { enum: ["Call", "Meeting", "Email", "Note"] }, details: text("What happened"), subject: text("Short subject (deals)"), happenedAt: text("ISO date/time (default now)"), followUpDate: text("YYYY-MM-DD") }, ["recordType", "id", "type", "details"]),
    run: async (ctx, a) => { const type = oneOf(a, "recordType", ["contact", "deal"] as const), recordId = int(a, "id")!, kind = oneOf(a, "type", ["Call", "Meeting", "Email", "Note"] as const), details = str(a, "details", 20000) || "", followUp = day(a, "followUpDate"), happenedAt = when(a, "happenedAt"); if (type === "deal") await logDealActivity(ctx.db, { dealId: recordId, type: kind, body: details, subject: str(a, "subject", 240), happenedAt, followUpAt: followUp, owner: ctx.user.email, now: ctx.now }); else await logContactActivity(ctx.db, { contactId: recordId, type: kind, note: details, nextFollowUp: followUp, owner: await who(ctx), now: happenedAt ?? ctx.now }); await record(ctx, "log_activity", type, recordId, `Logged ${kind}`, { type: kind }); return { ok: true }; } },
  { name: "create_task", description: "Create a follow-up task on a contact or deal.", permission: "records.edit", annotations: WRITE,
    inputSchema: S("Task", { recordType: { enum: ["contact", "deal"] }, id: id("Record id"), title: text("Task"), dueDate: text("YYYY-MM-DD"), owner: text("Owner (default: you)") }, ["recordType", "id", "title", "dueDate"]),
    run: async (ctx, a) => { const type = oneOf(a, "recordType", ["contact", "deal"] as const), recordId = int(a, "id")!, owner = str(a, "owner", 200) || await who(ctx), title = str(a, "title", 240) || "", dueDate = day(a, "dueDate") || ""; const r = type === "deal" ? await createDealTask(ctx.db, { dealId: recordId, title, owner, dueDate, now: ctx.now }) : await createContactTask(ctx.db, { contactId: recordId, title, owner, dueDate }); await record(ctx, "create_task", `${type}_task`, r.id, "Created task", { recordType: type, recordId }); return { id: r.id, taskType: type }; } },
  { name: "complete_task", description: "Mark a task done. Use the taskType and id returned by list_tasks or create_task.", permission: "records.edit", annotations: { ...WRITE, idempotentHint: true },
    inputSchema: S("Task", { taskType: { enum: ["contact", "deal"] }, id: id("Task id") }, ["taskType", "id"]),
    run: async (ctx, a) => { const type = oneOf(a, "taskType", ["contact", "deal"] as const), taskId = int(a, "id")!; const found = type === "deal" ? await setDealTaskCompleted(ctx.db, taskId, true) : await completeContactTask(ctx.db, taskId); if (!found) throw new ServiceError("Task not found.", 404); await record(ctx, "complete_task", `${type}_task`, taskId, "Completed task", {}); return { ok: true }; } },
];

const BY_NAME = new Map(TOOLS.map(t => [t.name, t]));
export async function callTool(ctx: ToolContext, name: string, args: unknown): Promise<{ ok: true; result: unknown } | { ok: false; error: string; status: number }> {
  const tool = BY_NAME.get(name); if (!tool) return { ok: false, error: `Unknown tool ${name}.`, status: 404 };
  if (!can(ctx.user, tool.permission)) return { ok: false, error: tool.permission === "records.edit" ? "You don't have permission to change CRM records." : "You don't have permission to view CRM records.", status: 403 };
  if (args === undefined || args === null) args = {};
  if (typeof args !== "object" || Array.isArray(args)) return { ok: false, error: "Tool arguments must be an object.", status: 400 };
  const allowed = (tool.inputSchema.properties || {}) as Row, unknown = Object.keys(args as Row).filter(k => !Object.hasOwn(allowed, k));
  if (unknown.length) return { ok: false, error: `Unknown argument${unknown.length > 1 ? "s" : ""} for ${name}: ${unknown.slice(0, 5).map(k => k.slice(0, 60)).join(", ")}.`, status: 400 };
  try { return { ok: true, result: sanitize(await tool.run(ctx, args as Row)) }; }
  catch (error) { if (error instanceof ServiceError) return { ok: false, error: error.message, status: error.status }; console.error("MCP tool failed", name, error); return { ok: false, error: "The CRM couldn't complete that request.", status: 500 }; }
}
