import { env } from "cloudflare:workers";
import { audit, can, crmUser } from "@/lib/crm-auth";

type Row=Record<string,unknown>;
const clean=(value:unknown,max=8000)=>String(value??"").trim().slice(0,max);
const number=(value:unknown)=>{const result=Number(value);return Number.isFinite(result)?result:0};
const optionalId=(value:unknown)=>{const result=Number(value);return Number.isInteger(result)&&result>0?result:null};
const parse=(value:unknown,fallback:unknown={})=>{try{return JSON.parse(String(value??""))}catch{return fallback}};

async function undoable(actor:string,action:string,entityType:string,entityId:string|number,before:unknown,after:unknown){const id=crypto.randomUUID(),now=new Date().toISOString(),expires=new Date(Date.now()+15*60_000).toISOString();await env.DB.prepare("INSERT INTO action_undo_log(id,action,entity_type,entity_id,before_json,after_json,actor,expires_at,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(id,action,entityType,String(entityId),JSON.stringify(before||{}),JSON.stringify(after||{}),actor,expires,now).run();return id;}
function names(value:string){const parts=value.trim().split(/\s+/).filter(Boolean);return {firstName:parts[0]||"Unknown",lastName:parts.slice(1).join(" ")||"Contact"};}
async function duplicateMatches(email:string,name:string){const normalized=email.toLowerCase(),tokens=name.toLowerCase().split(/\s+/).filter(Boolean),like=`%${tokens.join("%")}%`;return (await env.DB.prepare("SELECT id,first_name AS firstName,last_name AS lastName,email,company,title FROM contacts WHERE lower(email)=? OR lower(first_name||' '||last_name) LIKE ? ORDER BY CASE WHEN lower(email)=? THEN 0 ELSE 1 END LIMIT 8").bind(normalized||"__none__",like||"__none__",normalized||"__none__").all<Row>()).results;}

async function createFromDraft(draft:Row,userEmail:string){const kind=clean(draft.kind,40).toLowerCase(),now=new Date().toISOString();
 if(kind==="contact"){const email=clean(draft.email,320).toLowerCase(),fullName=clean(draft.name,240),split=names(fullName),firstName=clean(draft.firstName,120)||split.firstName,lastName=clean(draft.lastName,120)||split.lastName;if(!email.match(/^[^\s@]+@[^\s@]+\.[^\s@]+$/))throw new Error("A valid email address is required.");const matches=await duplicateMatches(email,`${firstName} ${lastName}`);if(matches.some(item=>clean(item.email).toLowerCase()===email))throw new Error("A contact with that email already exists.");const result=await env.DB.prepare("INSERT INTO contacts(first_name,last_name,email,company,title,phone,location,notes,lead_source,stage,tags,subscribed,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,'[]',1,?,?)").bind(firstName,lastName,email,clean(draft.company,240),clean(draft.title,240),clean(draft.phone,80),clean(draft.location,240),clean(draft.notes,4000),clean(draft.leadSource,120)||"Direct",clean(draft.stage,80)||"Lead",now,now).run();const id=Number(result.meta.last_row_id);if(clean(draft.company)){await env.DB.prepare("INSERT INTO companies(name,stage,updated_at) VALUES (?,'Prospect',?) ON CONFLICT(name) DO UPDATE SET updated_at=excluded.updated_at").bind(clean(draft.company,240),now).run()}return {kind,id,undoToken:await undoable(userEmail,"create",kind,id,{},draft)};}
 if(kind==="deal"){const name=clean(draft.name,300);if(!name)throw new Error("Deal name is required.");const companyId=optionalId(draft.companyId),company=companyId?await env.DB.prepare("SELECT name FROM companies WHERE id=?").bind(companyId).first<Row>():null,pipeline=await env.DB.prepare("SELECT * FROM sales_pipelines ORDER BY rowid LIMIT 1").first<Row>(),stages=parse(pipeline?.stages,[]) as Row[],stage=stages[0]||{key:"qualified",name:"Qualified",probability:25},result=await env.DB.prepare("INSERT INTO deals(name,company,company_id,contact_id,stage,owner,value,probability,next_step,close_date,lead_source,campaign,partner,forecast_category,status,pipeline_key,stage_key,closed_reason,stage_entered_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(name,clean(company?.name||draft.company,240),companyId,optionalId(draft.contactId),clean(stage.name)||"Qualified",clean(draft.owner,200)||userEmail,Math.round(number(draft.value)*100),number(stage.probability)||25,clean(draft.nextStep,1000)||"Qualify opportunity",clean(draft.closeDate,40)||null,clean(draft.leadSource,120)||"Direct","","","Pipeline","Open",clean(pipeline?.id,120)||"default",clean(stage.key,120)||"qualified","",now,now,now).run(),id=Number(result.meta.last_row_id);return {kind,id,undoToken:await undoable(userEmail,"create",kind,id,{},draft)};}
 if(kind==="task"){const contactId=optionalId(draft.contactId),dealId=optionalId(draft.dealId),title=clean(draft.title||draft.name,500),due=clean(draft.dueDate,40)||new Date(Date.now()+86400000).toISOString().slice(0,10);if(!title||(!contactId&&!dealId))throw new Error("Choose a contact or deal and enter a task.");const result=dealId?await env.DB.prepare("INSERT INTO deal_tasks(deal_id,title,owner,due_date,completed,created_at) VALUES (?,?,?,?,0,?)").bind(dealId,title,clean(draft.owner,200)||userEmail,due,now).run():await env.DB.prepare("INSERT INTO tasks(contact_id,title,due_date,owner,status,completed) VALUES (?,?,?,?,'Open',0)").bind(contactId,title,due,clean(draft.owner,200)||userEmail).run(),id=Number(result.meta.last_row_id),entity=dealId?"deal_task":"task";return {kind:entity,id,undoToken:await undoable(userEmail,"create",entity,id,{},draft)};}
 if(kind==="activity"){const contactId=optionalId(draft.contactId),dealId=optionalId(draft.dealId),note=clean(draft.note||draft.body,8000),type=clean(draft.type,120)||"Note";if(!note||(!contactId&&!dealId))throw new Error("Choose a contact or deal and describe the activity.");let result;if(dealId){const deal=await env.DB.prepare("SELECT company_id,contact_id FROM deals WHERE id=?").bind(dealId).first<Row>();result=await env.DB.prepare("INSERT INTO deal_activities(deal_id,company_id,contact_id,type,subject,body,owner,outcome,happened_at,source,pinned,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,'Quick capture',0,?,?)").bind(dealId,deal?.company_id||null,contactId||deal?.contact_id||null,type,clean(draft.subject,500)||type,note,clean(draft.owner,200)||userEmail,clean(draft.outcome,240),now,now,now).run()}else{result=await env.DB.prepare("INSERT INTO activities(contact_id,type,note,happened_at) VALUES (?,?,?,?)").bind(contactId,type,note,now).run();await env.DB.prepare("UPDATE contacts SET last_contact=?,updated_at=? WHERE id=?").bind(now.slice(0,10),now,contactId).run()}const id=Number(result.meta.last_row_id),entity=dealId?"deal_activity":"activity";return {kind:entity,id,undoToken:await undoable(userEmail,"create",entity,id,{},draft)};}
 throw new Error("Choose a supported draft type.");
}

function proposalSet(body:Row){const text=clean(body.text,12000),contactId=optionalId(body.contactId),dealId=optionalId(body.dealId),preset=clean(body.preset,120),proposals:Row[]=[{id:crypto.randomUUID(),type:"activity",label:preset||"Record activity",selected:true,evidence:text||preset,payload:{kind:"activity",contactId,dealId,type:preset.includes("Meeting")?"Meeting":preset.includes("Email")?"Email":preset.includes("voicemail")||preset.includes("response")?"Call":"Note",outcome:preset,note:text||preset}}];const task=text.match(/(?:follow[ -]?up|task|next(?: step)?)[\s:,-]+(.+?)(?:\.|$)/i);if(task)proposals.push({id:crypto.randomUUID(),type:"task",label:`Create task: ${task[1]}`,selected:true,evidence:task[0],payload:{kind:"task",contactId,dealId,title:task[1],dueDate:new Date(Date.now()+86400000).toISOString().slice(0,10)}});if(dealId&&/\b(risk|blocked|concern|objection)\b/i.test(text))proposals.push({id:crypto.randomUUID(),type:"risk",label:"Add deal risk",selected:true,evidence:text,payload:{dealId,title:"Risk from activity",detail:text}});const close=text.match(/(?:close|closing|close date)\s+(?:on\s+)?(\d{4}-\d{2}-\d{2})/i);if(dealId&&close)proposals.push({id:crypto.randomUUID(),type:"deal_update",label:`Update close date to ${close[1]}`,selected:true,evidence:close[0],payload:{dealId,closeDate:close[1],nextStep:""}});return proposals;}

export async function GET(request:Request){const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});const url=new URL(request.url),email=clean(url.searchParams.get("email"),320),name=clean(url.searchParams.get("name"),240);return Response.json({matches:await duplicateMatches(email,name)});}

export async function POST(request:Request){const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});if(!can(user,"records.edit"))return Response.json({error:"Edit access is required."},{status:403});try{const body=await request.json() as Row,action=clean(body.action,80),now=new Date().toISOString();
 if(action==="commitDraft"){const result=await createFromDraft((body.draft||{}) as Row,user.email);await audit(user,"quick_capture.commit",String(result.kind),String(result.id),"Committed reviewed quick-capture draft",body.draft as Row);return Response.json(result,{status:201});}
 if(action==="composeActivity")return Response.json({proposals:proposalSet(body),mode:"Review-first rules"});
 if(action==="commitProposals"){const proposals=Array.isArray(body.proposals)?body.proposals as Row[]:[],results:Row[]=[];for(const proposal of proposals){const type=clean(proposal.type,40),payload=(proposal.payload||{}) as Row;if(type==="activity"||type==="task")results.push(await createFromDraft({...payload,kind:type},user.email));else if(type==="risk"){const dealId=optionalId(payload.dealId);if(!dealId)continue;const result=await env.DB.prepare("INSERT INTO deal_insights(deal_id,kind,title,detail,severity,status,owner,created_at,updated_at) VALUES (?,'Risk',?,?,'Medium','Open',?,?,?)").bind(dealId,clean(payload.title,500)||"Activity risk",clean(payload.detail,8000),user.email,now,now).run(),id=Number(result.meta.last_row_id);results.push({kind:"deal_insight",id,undoToken:await undoable(user.email,"create","deal_insight",id,{},payload)})}else if(type==="deal_update"){const dealId=optionalId(payload.dealId),before=dealId?await env.DB.prepare("SELECT close_date,next_step FROM deals WHERE id=?").bind(dealId).first<Row>():null;if(!dealId||!before)continue;await env.DB.prepare("UPDATE deals SET close_date=COALESCE(NULLIF(?,''),close_date),next_step=COALESCE(NULLIF(?,''),next_step),updated_at=? WHERE id=?").bind(clean(payload.closeDate,40),clean(payload.nextStep,1000),now,dealId).run();results.push({kind:"deal",id:dealId,undoToken:await undoable(user.email,"update","deal",dealId,before,payload)})}}const tokens=results.map(item=>clean(item.undoToken,100)).filter(Boolean),undoToken=tokens.length>1?await undoable(user.email,"batch","batch",crypto.randomUUID(),{}, {tokens}):tokens[0];await audit(user,"activity_composer.commit","activity","batch","Committed selected activity proposals",{count:results.length});return Response.json({results,undoToken},{status:201});}
 if(action==="undo"){const token=clean(body.token,100),entry=await env.DB.prepare("SELECT * FROM action_undo_log WHERE id=? AND actor=? AND undone_at IS NULL AND expires_at>datetime('now')").bind(token,user.email).first<Row>();if(!entry)throw new Error("That undo window has expired.");const table:Record<string,string>={contact:"contacts",deal:"deals",task:"tasks",deal_task:"deal_tasks",activity:"activities",deal_activity:"deal_activities",deal_insight:"deal_insights"};const reverse=async(item:Row)=>{const entity=clean(item.entity_type,80),id=clean(item.entity_id,100);if(item.action==="create"&&table[entity])await env.DB.prepare(`DELETE FROM ${table[entity]} WHERE id=?`).bind(id).run();else if(item.action==="update"&&entity==="deal"){const before=parse(item.before_json,{}) as Row;await env.DB.prepare("UPDATE deals SET close_date=?,next_step=?,updated_at=? WHERE id=?").bind(before.close_date||null,clean(before.next_step),now,id).run()}else throw new Error("This change cannot be undone automatically.")};if(entry.action==="batch"){const tokens=((parse(entry.after_json,{}) as Row).tokens||[]) as string[];for(const childToken of tokens.slice().reverse()){const child=await env.DB.prepare("SELECT * FROM action_undo_log WHERE id=? AND actor=? AND undone_at IS NULL").bind(childToken,user.email).first<Row>();if(child){await reverse(child);await env.DB.prepare("UPDATE action_undo_log SET undone_at=? WHERE id=?").bind(now,childToken).run()}}}else await reverse(entry);await env.DB.prepare("UPDATE action_undo_log SET undone_at=? WHERE id=?").bind(now,token).run();await audit(user,"quick_capture.undo",clean(entry.entity_type),clean(entry.entity_id),"Undid quick-capture change",{});return Response.json({ok:true});}
 throw new Error("Unknown quick-capture action.");
 }catch(error){return Response.json({error:error instanceof Error?error.message:"Quick capture could not be completed."},{status:400})}}
