import { env } from "cloudflare:workers";
import { audit, can, crmUser } from "@/lib/crm-auth";
import { quickbooksApi, quickbooksConfigured } from "@/lib/quickbooks";

type Row=Record<string,unknown>;
const clean=(value:unknown,max=240)=>String(value??"").trim().slice(0,max);
const id=(value:unknown)=>{const result=Number(value);if(!Number.isInteger(result)||result<1)throw new Error("Choose a valid proposal.");return result};
const date=(value:unknown)=>/^\d{4}-\d{2}-\d{2}$/.test(clean(value,20))?clean(value,20):null;
const cents=(value:unknown)=>Math.round(Number(value||0)*100);
function status(invoice:Row){const balance=Number(invoice.Balance||0),due=String(invoice.DueDate||"");return balance<=0?"Paid":due&&due<new Date().toISOString().slice(0,10)?"Overdue":"Open";}
async function proposal(proposalId:number){return env.DB.prepare("SELECT p.*,d.name AS deal_name,d.company,d.company_id,c.email AS contact_email FROM deal_proposals p JOIN deals d ON d.id=p.deal_id LEFT JOIN contacts c ON c.id=d.contact_id WHERE p.id=?").bind(proposalId).first<Row>();}
async function customer(record:Row){const display=clean(record.company||record.deal_name,100)||"ClientRecord customer",escaped=display.replaceAll("'","\\'");const found=await quickbooksApi(`query?query=${encodeURIComponent(`SELECT * FROM Customer WHERE DisplayName = '${escaped}' MAXRESULTS 1`)}`),existing=((found.QueryResponse as Row|undefined)?.Customer as Row[]|undefined)?.[0];if(existing)return existing;const created=await quickbooksApi("customer",{method:"POST",body:JSON.stringify({DisplayName:display,CompanyName:display,PrimaryEmailAddr:record.contact_email?{Address:clean(record.contact_email,320)}:undefined})});return created.Customer as Row;}
async function serviceItem(){const configured=clean(env.QUICKBOOKS_DEFAULT_ITEM_ID,80);if(configured)return configured;const found=await quickbooksApi(`query?query=${encodeURIComponent("SELECT * FROM Item WHERE Name = 'ClientRecord Services' MAXRESULTS 1")}`),existing=((found.QueryResponse as Row|undefined)?.Item as Row[]|undefined)?.[0];if(existing?.Id)return String(existing.Id);const accounts=await quickbooksApi(`query?query=${encodeURIComponent("SELECT * FROM Account WHERE AccountType = 'Income' AND Active = true MAXRESULTS 1")}`),income=((accounts.QueryResponse as Row|undefined)?.Account as Row[]|undefined)?.[0];if(!income?.Id)throw new Error("QuickBooks needs one active Income account before ClientRecord can create its service item.");const created=await quickbooksApi("item",{method:"POST",body:JSON.stringify({Name:"ClientRecord Services",Type:"Service",IncomeAccountRef:{value:String(income.Id)}})});if(!(created.Item as Row|undefined)?.Id)throw new Error("QuickBooks could not create the ClientRecord service item.");return String((created.Item as Row).Id);}

export async function GET(request:Request){const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});if(!can(user,"records.view"))return Response.json({error:"View access is required."},{status:403});const [connection,invoices]=await Promise.all([env.DB.prepare("SELECT account_email AS accountEmail FROM integration_accounts WHERE provider='quickbooks'").first<Row>(),env.DB.prepare("SELECT * FROM quickbooks_invoices ORDER BY updated_at DESC LIMIT 300").all<Row>()]);return Response.json({connection:{configured:quickbooksConfigured(),itemConfigured:true,connected:Boolean(connection),accountName:connection?.accountEmail||""},invoices:invoices.results});}

export async function POST(request:Request){const user=await crmUser(request);if(!user)return Response.json({error:"Sign in is required."},{status:401});if(!can(user,"integrations.manage"))return Response.json({error:"Accounting integration access is required."},{status:403});const body=await request.json().catch(()=>({})) as Row;try{const action=clean(body.action),proposalId=id(body.proposalId),record=await proposal(proposalId);if(!record)throw new Error("Proposal not found.");if(action==="createInvoice"){if(!record.accepted_at)throw new Error("Only signed proposals can be invoiced.");if(!quickbooksConfigured())throw new Error("QuickBooks credentials are not configured.");const existing=await env.DB.prepare("SELECT * FROM quickbooks_invoices WHERE proposal_id=?").bind(proposalId).first<Row>();if(existing?.quickbooks_invoice_id)throw new Error("This proposal already has a QuickBooks invoice.");const amount=Number(record.amount||0);if(amount<=0)throw new Error("The signed proposal needs a positive amount before it can be invoiced.");const dueDate=date(body.dueDate)||new Date(Date.now()+30*86400000).toISOString().slice(0,10),client=await customer(record),itemId=await serviceItem(),invoice=await quickbooksApi("invoice",{method:"POST",body:JSON.stringify({CustomerRef:{value:String(client.Id)},DocNumber:`CR-${proposalId}`,DueDate:dueDate,Line:[{Amount:amount/100,Description:clean(record.title,400),DetailType:"SalesItemLineDetail",SalesItemLineDetail:{ItemRef:{value:itemId},Qty:1,UnitPrice:amount/100}}]})}),remote=invoice.Invoice as Row,now=new Date().toISOString(),state=status(remote);await env.DB.prepare("INSERT INTO quickbooks_invoices(id,proposal_id,deal_id,company_id,quickbooks_customer_id,quickbooks_invoice_id,document_number,status,amount,balance,due_date,synced_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(proposal_id) DO UPDATE SET quickbooks_customer_id=excluded.quickbooks_customer_id,quickbooks_invoice_id=excluded.quickbooks_invoice_id,document_number=excluded.document_number,status=excluded.status,amount=excluded.amount,balance=excluded.balance,due_date=excluded.due_date,synced_at=excluded.synced_at,updated_at=excluded.updated_at").bind(crypto.randomUUID(),proposalId,record.deal_id,record.company_id||null,String(client.Id||""),String(remote.Id||""),String(remote.DocNumber||`CR-${proposalId}`),state,amount,cents(remote.Balance),String(remote.DueDate||dueDate),now,now,now).run();await audit(user,"quickbooks.invoice.create","deal_proposal",proposalId,"Created QuickBooks invoice from signed proposal",{quickbooksInvoiceId:remote.Id,dueDate,amount});return Response.json({ok:true,status:state});}
if(action==="syncInvoice"){const current=await env.DB.prepare("SELECT * FROM quickbooks_invoices WHERE proposal_id=?").bind(proposalId).first<Row>();if(!current?.quickbooks_invoice_id)throw new Error("No QuickBooks invoice exists for this proposal.");const remote=(await quickbooksApi(`invoice/${encodeURIComponent(String(current.quickbooks_invoice_id))}`)).Invoice as Row,now=new Date().toISOString(),state=status(remote);await env.DB.prepare("UPDATE quickbooks_invoices SET status=?,balance=?,due_date=?,synced_at=?,updated_at=? WHERE proposal_id=?").bind(state,cents(remote.Balance),String(remote.DueDate||current.due_date||"")||null,now,now,proposalId).run();await audit(user,"quickbooks.invoice.sync","deal_proposal",proposalId,"Updated QuickBooks invoice status",{status:state,balance:remote.Balance});return Response.json({ok:true,status:state});}
throw new Error("Unknown QuickBooks action.");}catch(error){console.error(error);return Response.json({error:error instanceof Error?error.message:"QuickBooks billing could not be updated."},{status:400});}}
